Repository tidev/titanium-sdk, pull requests merged in 2018-09, with the labels that each got.

#10296 [TIMOB-26344] iOS: Pass blocks with copy to retain them properly
  iphone/Classes/TiApp.m
Labels: bug 🐜, in-qe-testing 🕵️‍♂️, ios, no tests

#10302 TIMOB-26347 fix setRemoteBackup(flag) bug
  iphone/Classes/TiFilesystemFileProxy.m
Labels: community 🔥, ios, no tests

#10303 Fix for missing parameters of setContentOffset
  apidoc/Titanium/UI/ScrollView.yml
Labels: docs 📔

#10251 [TIMOB-26295] Android: Listview with template causes a nullpointer on itemclick
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/listview/ListItemProxy.java
Labels: android, community 🔥, in-qe-testing 🕵️‍♂️, no tests

#10306 Revert "[TIMOB-26349] iOS: Fix a couple of long-running issues with push notifications"
  apidoc/Titanium/App/iOS/iOS.yml
  iphone/Classes/NetworkModule.m
  iphone/Classes/TiApp.h
  iphone/Classes/TiApp.m
  iphone/Classes/TiAppiOSUserNotificationCenterProxy.m
  iphone/Classes/TiBase.h
  iphone/Classes/TiBase.m
Labels: docs 📔, ios, needs jira 🚨, no tests

#10280 [TIMOB-26333] Expose option to generate source maps when transpiling
  android/cli/commands/_build.js
  iphone/cli/commands/_build.js
  package-lock.json
  package.json
Labels: improvement

#10297 [TIMOB-26344] (7_4_X) iOS: Pass blocks with copy to retain them properly
  iphone/Classes/TiApp.m
Labels: bug 🐜, in-qe-testing 🕵️‍♂️, ios, no tests

#10298 [TIMOB-26344] (7_3_X) iOS: Pass blocks with copy to retain them properly
  iphone/Classes/TiApp.m
Labels: bug 🐜, in-qe-testing 🕵️‍♂️, ios, no tests

#10310 [TIMOB-26360] Fix documentation generation
  apidoc/Titanium/UI/Tab.yml
  apidoc/Titanium/UI/View.yml
  apidoc/docgen.js
  apidoc/lib/changes_generator.js
Labels: bug 🐜, docs 📔

#10307 [TIMOB-26261] Android: Compile with API Level 28 (Android P)
  android/.idea/misc.xml
  android/.idea/workspace.xml
  android/dev/TitaniumTest/project.properties
  android/modules/accelerometer/project.properties
  android/modules/analytics/project.properties
  android/modules/android/AndroidManifest.xml
  android/modules/android/project.properties
  android/modules/app/project.properties
  android/modules/appcompat/project.properties
  android/modules/calendar/project.properties
  android/modules/cardview/project.properties
  android/modules/compat/project.properties
  android/modules/contacts/project.properties
  android/modules/database/project.properties
  android/modules/design/project.properties
  android/modules/filesystem/project.properties
  android/modules/geolocation/project.properties
  android/modules/gesture/project.properties
  android/modules/locale/project.properties
  android/modules/media/project.properties
  android/modules/network/project.properties
  android/modules/platform/project.properties
  android/modules/ui/AndroidManifest.xml
  android/modules/ui/project.properties
  android/modules/utils/project.properties
  android/modules/xml/project.properties
  android/modules/yahoo/project.properties
  android/package.json
  android/titanium/AndroidManifest.xml
  android/titanium/project.properties
  build/androidsdk.js
Labels: android, improvement, in-qe-testing 🕵️‍♂️, no tests

#10311 [TIMOB-26253] Android: Fixed NotificationManager.notify() crash if screen is off and missing WAKE_LOCK permission
  android/modules/android/src/java/ti/modules/titanium/android/notificationmanager/NotificationManagerModule.java
Labels: android, bug 🐜, in-qe-testing 🕵️‍♂️, no tests

#10319 [TIMOB-26377] Android: Allow non-https requests to work when targeting Android P
  android/templates/build/AndroidManifest.xml
Labels: android, improvement, in-qe-testing 🕵️‍♂️, no tests

#9926 [TIMOB-26340] Android: Update V8 runtime to 6.9.x - V8 6.9.427.17 and NDK r16b
  Jenkinsfile
  android/kroll-apt/src/java/org/appcelerator/kroll/annotations/generator/ProxyBinding.fm
  android/kroll-apt/src/java/org/appcelerator/kroll/annotations/generator/ProxyBindingV8.cpp.fm
  android/kroll-apt/src/java/org/appcelerator/kroll/annotations/generator/ProxyBindingV8.h.fm
  android/package.json
  android/runtime/v8/src/java/org/appcelerator/kroll/runtime/v8/V8Runtime.java
  android/runtime/v8/src/native/Android.mk
  android/runtime/v8/src/native/EventEmitter.cpp
  android/runtime/v8/src/native/InspectorClient.cpp
  android/runtime/v8/src/native/JSDebugger.cpp
  android/runtime/v8/src/native/KrollBindings.cpp
  android/runtime/v8/src/native/Proxy.cpp
  android/runtime/v8/src/native/Proxy.h
  android/runtime/v8/src/native/ProxyFactory.cpp
  android/runtime/v8/src/native/TypeConverter.cpp
  android/runtime/v8/src/native/TypeConverter.h
  android/runtime/v8/src/native/V8Function.cpp
  android/runtime/v8/src/native/V8Object.cpp
  android/runtime/v8/src/native/V8Runtime.cpp
  android/runtime/v8/src/native/V8Util.cpp
  android/runtime/v8/src/native/V8Util.h
  android/runtime/v8/src/native/modules/APIModule.cpp
  android/runtime/v8/src/native/modules/AssetsModule.cpp
  android/runtime/v8/src/native/modules/ScriptsModule.cpp
  android/runtime/v8/src/ndk-modules/libv8/Android.mk
  android/templates/module/generated/{{ModuleIdAsIdentifier}}Bootstrap.cpp.ejs
  build/utils.js
  package.json
  support/module/packaged/modules.json
Labels: BREAKING CHANGES ⚠️, android, improvement, needs tests 🚨

#10322 [TIMOB-26388] (7_4_X) iOS 12: support iPhone XS Max and iPhone XR launch images
  iphone/Classes/ImageLoader.m
  iphone/Classes/TiDimension.m
  iphone/Classes/TiPlatformDisplayCaps.m
  iphone/Classes/TiRootViewController.m
  iphone/Classes/TiUtils.h
  iphone/Classes/TiUtils.m
  iphone/Classes/TiViewProxy.m
  iphone/Classes/UIImage+Resize.m
  iphone/cli/commands/_build.js
  iphone/iphone/Assets.xcassets/LaunchImage.launchimage/Contents.json
  iphone/iphone/Assets.xcassets/LaunchImage.launchimage/Default-Landscape-1792h@2x.png
  iphone/iphone/Assets.xcassets/LaunchImage.launchimage/Default-Landscape-2688h@3x.png
  iphone/iphone/Assets.xcassets/LaunchImage.launchimage/Default-Portrait-1792h@2x.png
  iphone/iphone/Assets.xcassets/LaunchImage.launchimage/Default-Portrait-2688h@3x.png
  iphone/templates/app/default/template/Resources/iphone/Default-Landscape-1792h@2x.png
  iphone/templates/app/default/template/Resources/iphone/Default-Landscape-2688h@3x.png
  iphone/templates/app/default/template/Resources/iphone/Default-Portrait-1792h@2x.png
  iphone/templates/app/default/template/Resources/iphone/Default-Portrait-2688h@3x.png
Labels: feature 🚀, ios, no tests

#10321 [TIMOB-26388] iOS 12: support iPhone XS Max and iPhone XR launch images
  iphone/Classes/ImageLoader.m
  iphone/Classes/TiDimension.m
  iphone/Classes/TiPlatformDisplayCaps.m
  iphone/Classes/TiRootViewController.m
  iphone/Classes/TiUtils.h
  iphone/Classes/TiUtils.m
  iphone/Classes/TiViewProxy.m
  iphone/Classes/UIImage+Resize.m
  iphone/cli/commands/_build.js
  iphone/iphone/Assets.xcassets/LaunchImage.launchimage/Contents.json
  iphone/iphone/Assets.xcassets/LaunchImage.launchimage/Default-Landscape-1792h@2x.png
  iphone/iphone/Assets.xcassets/LaunchImage.launchimage/Default-Landscape-2688h@3x.png
  iphone/iphone/Assets.xcassets/LaunchImage.launchimage/Default-Portrait-1792h@2x.png
  iphone/iphone/Assets.xcassets/LaunchImage.launchimage/Default-Portrait-2688h@3x.png
  iphone/templates/app/default/template/Resources/iphone/Default-Landscape-1792h@2x.png
  iphone/templates/app/default/template/Resources/iphone/Default-Landscape-2688h@3x.png
  iphone/templates/app/default/template/Resources/iphone/Default-Portrait-1792h@2x.png
  iphone/templates/app/default/template/Resources/iphone/Default-Portrait-2688h@3x.png
Labels: feature 🚀, ios, no tests

#10153 [TIMOB-26182] Android: Validate external storage temp directory
  android/runtime/common/src/java/org/appcelerator/kroll/util/TiTempFileHelper.java
Labels: android, bug 🐜, in-qe-testing 🕵️‍♂️, no tests

#10318 [TIMOB-26382] Android: Modified "appc run" to dismiss screen-lock before running built app
  android/cli/hooks/run.js
Labels: android, improvement, no tests

#10327 [TiMOB-26391](7_4_X) : iOS App randomly freezes on iOS 12 beta when using main-thread
  iphone/Classes/KrollTimer.m
Labels: in-qe-testing 🕵️‍♂️, ios, needs jira 🚨, no tests

#10253 [TIMOB-26297] Android: Fix MD5-hashing for Android 9
  android/.idea/libraries/common.xml
  android/.idea/workspace.xml
  android/dependency.json
  android/dev/TitaniumTest/.classpath
  android/modules/network/.classpath
  android/modules/utils/.classpath
  android/modules/utils/lib/commons-codec-1.10.jar
  android/modules/utils/src/java/ti/modules/titanium/utils/UtilsModule.java
  android/modules/utils/utils.iml
  android/titanium/.classpath
  android/titanium/lib/ti-commons-codec-1.3.jar
  android/titanium/src/java/org/appcelerator/titanium/util/TiDigestUtils.java
  android/titanium/src/java/org/appcelerator/titanium/util/TiDownloadManager.java
  android/titanium/src/java/org/appcelerator/titanium/util/TiResponseCache.java
  android/titanium/src/java/org/appcelerator/titanium/util/TiUIHelper.java
  support/android/lib/titanium-verify.jar
Labels: android, in-qe-testing 🕵️‍♂️, no tests

#10326 [TIMOB-26391]: iOS App randomly freezes on iOS 12 beta when using main-thread
  iphone/Classes/KrollTimer.m
Labels: in-qe-testing 🕵️‍♂️, ios, no tests

#10032 [TIMOB-24080] : iOS - Paragraph style support in attributed string
  apidoc/Titanium/UI/Attribute.yml
  apidoc/Titanium/UI/UI.yml
  iphone/Classes/TiUIAttributedStringProxy.h
  iphone/Classes/TiUIAttributedStringProxy.m
  iphone/Classes/UIModule.m
  tests/Resources/ti.ui.attributedstring.addontest.js
Labels: docs 📔, ios

#10112 [TIMOB-26015] Android/iOS: Refactored "app.js" launch handling
  android/cli/commands/_build.js
  android/modules/app/src/java/ti/modules/titanium/app/AppModule.java
  android/runtime/common/src/java/org/appcelerator/kroll/util/KrollAssetHelper.java
  android/runtime/common/src/js/module.js
  android/runtime/common/src/js/titanium.js
  android/runtime/v8/src/native/ProxyFactory.cpp
  android/templates/build/AssetCryptImpl.java
  android/titanium/src/java/org/appcelerator/titanium/TiApplication.java
  android/titanium/src/java/org/appcelerator/titanium/TiRootActivity.java
  android/titanium/src/java/org/appcelerator/titanium/io/TiResourceFile.java
  build/packager.js
  build/scons-build.js
  build/scons-cleanbuild.js
  common/README.md
  common/Resources/ti.internal/bootstrap.loader.js
  common/Resources/ti.internal/extensions/Error.js
  common/Resources/ti.main.js
  iphone/Classes/FilesystemModule.m
  iphone/Classes/TiApp.m
  iphone/Classes/TiFilesystemBlobProxy.m
  iphone/Classes/TiHost.m
  iphone/cli/commands/_build.js
  iphone/iphone/Titanium.xcodeproj/project.pbxproj
  tests/Resources/bootstraps/simple.bootstrap.js
  tests/Resources/bootstraps/ui.bootstrap.js
  tests/Resources/error.addontest.js
  tests/Resources/ti.bootstrap.addontest.js
  tests/Resources/ti.filesystem.file.2.addontest.js
Labels: android, bug 🐜, feature 🚀, in-qe-testing 🕵️‍♂️, ios, parity 👯‍♀️

#10330 [TIMOB-26399] iOS: Fix a couple of push-notifications related issues
  iphone/Classes/TiApp.m
  iphone/Classes/TiAppiOSUserNotificationCenterProxy.m
  iphone/cli/commands/_build.js
  tests/Resources/ti.ui.view.addontest.js
Labels: community 🔥, ios, no tests

#10328 [TIMOB-26399] (7_4_X) iOS: Fix a couple of push-notifications related issues
  iphone/Classes/TiApp.m
  iphone/Classes/TiAppiOSUserNotificationCenterProxy.m
  iphone/cli/commands/_build.js
Labels: community 🔥, ios, no tests

#10334 [TIMOB-26405] Android: update TitaniumDev after recent changes
  android/dev/TitaniumTest/assets/Resources/ti.internal/bootstrap.json
  android/dev/TitaniumTest/assets/Resources/ti.internal/bootstrap.loader.js
  android/dev/TitaniumTest/assets/Resources/ti.internal/extensions/Error.js
  android/dev/TitaniumTest/assets/Resources/ti.main.js
  android/dev/TitaniumTest/assets/index.json
  android/dev/TitaniumTest/src/com/titanium/test/AssetCryptImpl.java
  android/dev/TitaniumTest/src/com/titanium/test/TitaniumTestApplication.java
Labels: android, improvement, no tests

#10333 [7_4_X][TIMOB-26404] Update to hyperloop 3.1.3
  build/scons-modules-integrity.js
  support/module/packaged/modules.json
Labels: bug 🐜, ios

#10312 TIMOB-26369 Restored notification of unhandled exceptions in iOS
  iphone/Classes/AppModule.m
  iphone/Classes/TiExceptionHandler.m
Labels: community 🔥, ios, no tests

#10336 [TIMOB-24321] Android: Add anchorPoint to Ti.UI.View
  android/titanium/src/java/org/appcelerator/titanium/proxy/TiViewProxy.java
  android/titanium/src/java/org/appcelerator/titanium/view/TiUIView.java
  apidoc/Titanium/UI/View.yml
Labels: android, community 🔥, docs 📔, no tests, parity 👯‍♀️

#10338 [TIMOB-26030] Android: Fixed TCP read()/write() to not crash when JS running on main thread
  android/modules/network/src/java/ti/modules/titanium/network/socket/TCPProxy.java
Labels: android, bug 🐜, no tests

#10337 [TIMOB-26402] Maintain compatibility with Titanium 7.0.0 native modules
  android/kroll-apt/src/java/org/appcelerator/kroll/annotations/generator/ProxyBindingV8.cpp.fm
  android/kroll-apt/src/java/org/appcelerator/kroll/annotations/generator/ProxyBindingV8.h.fm
  android/package.json
  android/runtime/v8/src/native/Proxy.cpp
  android/runtime/v8/src/native/Proxy.h
  android/runtime/v8/src/native/TypeConverter.cpp
  android/runtime/v8/src/native/TypeConverter.h
  android/runtime/v8/src/native/V8Runtime.cpp
  android/runtime/v8/src/native/V8Util.cpp
  android/runtime/v8/src/native/V8Util.h
  package.json
  support/module/packaged/modules.json
Labels: android, improvement, no tests

#9889 [TIMOB-25862] Parity: Support async Ti.UI.Webview.evalJS call on Android & iOS
  android/modules/ui/src/java/ti/modules/titanium/ui/WebViewProxy.java
  apidoc/Titanium/UI/WebView.yml
  iphone/Classes/TiUIWebViewProxy.m
  tests/Resources/ti.ui.webview.addontest.js
Labels: android, docs 📔, improvement, ios, parity 👯‍♀️

#10264 [TIMOB-26314] Android: Add versionCode to tiapp.xml
  templates/app/angular-default/template/tiapp.xml
  templates/app/default/template/tiapp.xml
Labels: community 🔥

#10248 [TIMOB-26294] TiAPI: Notify app about user-interactions
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/TiUIText.java
  android/titanium/src/java/org/appcelerator/titanium/TiBaseActivity.java
  apidoc/Titanium/App/App.yml
  iphone/Classes/AppModule.m
  iphone/Classes/TiBase.h
  iphone/Classes/TiBase.m
  iphone/Classes/TiUIApplication.h
  iphone/Classes/TiUIApplication.m
  iphone/Classes/defines.h
  iphone/iphone/Titanium.xcodeproj/project.pbxproj
  iphone/iphone/main.m
  support/iphone/main.m
Labels: android, community 🔥, docs 📔, in-qe-testing 🕵️‍♂️, ios, no tests

#10104 [TIMOB-25942] : iOS 11: Screen orientation not working in navigation window
  iphone/Classes/TiRootViewController.m
  tests/Resources/ti.ui.window.addontest.js
Labels: ios

#10351 [TIMOB-26413] (7_4_X) iOS: Use correct dpi-scaling for launch-screens until Utils are refactored
  iphone/Classes/TiUtils.m
Labels: ios, no tests

#10350 [TIMOB-26413] iOS: Use correct dpi-scaling for launch-screens until Utils are refactored
  iphone/Classes/TiUtils.m
Labels: ios, no tests

#10352 [TIMOB-26391] Protect js objects for proxies
  iphone/Classes/KrollBridge.m
  iphone/Classes/TiBindingTiValue.m
Labels: ios, no tests

#10349 Update ActivityIndicatorStyle.yml
  apidoc/Titanium/UI/ActivityIndicatorStyle.yml
Labels: docs 📔, needs jira 🚨

#10346 Update View.yml
  apidoc/Titanium/UI/View.yml
Labels: docs 📔, needs jira 🚨

#10353 [TIMOB-26399] iOS: Fix notification update to trigger correct callback for default notification action
  iphone/Classes/TiApp.m
Labels: community 🔥, ios, no tests

#10357 [TIMOB-26399] (7_4_X) iOS: Fix notification categories on iOS 11+
  iphone/Classes/TiAppiOSUserNotificationCategoryProxy.m
Labels: community 🔥, ios, no tests

#10342 [DOC] Mark Titanium.Android.Calendar as removed.
  apidoc/Titanium/Android/Calendar/Alert.yml
  apidoc/Titanium/Android/Calendar/Calendar.yml
  apidoc/Titanium/Android/Calendar/CalendarProxy.yml
  apidoc/Titanium/Android/Calendar/Event.yml
  apidoc/Titanium/Android/Calendar/Reminder.yml
Labels: docs 📔, needs jira 🚨

#10345 [DOC] Titanium.UI.Android.ProgressIndicator
  apidoc/Titanium/UI/Android/ProgressIndicator.yml
Labels: docs 📔, needs jira 🚨

#10340 Remove notice of deprecation
  apidoc/Titanium/UI/iOS/SplitWindow.yml
Labels: docs 📔, needs jira 🚨, no tests

#10348 Update View.yml
  apidoc/Titanium/UI/View.yml
Labels: docs 📔, needs jira 🚨
