Repository tidev/titanium-sdk, pull requests merged in 2019-04, with the labels that each got.

#10810 fix(ios)(8_0_X): Cancel perform selector while cleaning up view
  iphone/Classes/TiUIListView.m
Labels: bug 🐜, customer, in-qe-testing 🕵, ios, no tests

#10811 fix(ios): Cancel perform selector while cleaning up view
  iphone/Classes/TiUIListView.m
Labels: bug 🐜, customer, in-qe-testing 🕵, ios, no tests

#10655 fix(android)(8_0_X): TabbedBar crash caused by setting properties before window opened
  android/modules/ui/src/java/ti/modules/titanium/ui/TabbedBarProxy.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/TiUITabbedBar.java
  tests/Resources/ti.ui.tabbedbar.addontest.js
Labels: android, bug 🐜, in-qe-testing 🕵, parity 👯‍♀️

#10710 fix(android): Do not show Up navigation button for NavigationWindow's root window.
  android/modules/ui/src/java/ti/modules/titanium/ui/NavigationWindowProxy.java
  android/modules/ui/src/java/ti/modules/titanium/ui/WindowProxy.java
Labels: android, bug 🐜, in-qe-testing 🕵, no tests

#10791 fix(android): Do not show Up navigation button for NavigationWindow's root window. (8_0_X)
  android/modules/ui/src/java/ti/modules/titanium/ui/NavigationWindowProxy.java
  android/modules/ui/src/java/ti/modules/titanium/ui/WindowProxy.java
Labels: android, bug 🐜, in-qe-testing 🕵, no tests

#10797 fix(ios): Unnecessary import removed and code wrapped inside proper macro
  iphone/Classes/MediaModule.h
  iphone/Classes/MediaModule.m
  iphone/Classes/TiMediaVideoPlayer.h
  iphone/Classes/TiMediaVideoPlayerProxy.h
Labels: bug 🐜, in-qe-testing 🕵, ios, no tests

#10798 fix(ios)(8_0_X): Unnecessary import removed and code wrapped inside proper macro
  iphone/Classes/MediaModule.h
  iphone/Classes/MediaModule.m
  iphone/Classes/TiMediaVideoPlayer.h
  iphone/Classes/TiMediaVideoPlayerProxy.h
Labels: bug 🐜, in-qe-testing 🕵, ios, no tests

#10793 fix(ios): Supported tel protocol similar to previous implementation
  iphone/Classes/TiUIWebView.m
Labels: bug 🐜, in-qe-testing 🕵, ios, no tests

#10794 fix(ios)(8_0_X): Supported tel protocol similar to previous implementation
  iphone/Classes/TiUIWebView.m
Labels: bug 🐜, in-qe-testing 🕵, ios, no tests

#10792 fix(android)(8_0_X): remove Ti.UI.currentWindow
  android/modules/ui/src/java/ti/modules/titanium/ui/UIModule.java
  android/runtime/common/src/js/module.js
  android/runtime/common/src/js/titanium.js
Labels: android, bug 🐜, in-qe-testing 🕵, no tests

#10749 [TIMOB-26239] Android: remove Ti.UI.currentWindow
  android/modules/ui/src/java/ti/modules/titanium/ui/UIModule.java
  android/runtime/common/src/js/module.js
  android/runtime/common/src/js/titanium.js
Labels: android, community 🔥, in-qe-testing 🕵, no tests

#10589 fix(android)(8_0_X): amend hasActivityTransitions() for transitions
  android/modules/ui/src/java/ti/modules/titanium/ui/WindowProxy.java
  android/titanium/src/java/org/appcelerator/titanium/proxy/TiWindowProxy.java
Labels: android, bug 🐜, in-qe-testing 🕵, no tests

#10405 [TIMOB-25678] Android: Amend hasActivityTransitions() for transitions
  android/modules/ui/src/java/ti/modules/titanium/ui/WindowProxy.java
  android/titanium/src/java/org/appcelerator/titanium/proxy/TiWindowProxy.java
Labels: android, bug 🐜, in-qe-testing 🕵, no tests

#10786 fix(ios): cookie support for ios while using wkwebview (8_0_X)
  iphone/Classes/TiUIWebView.m
  iphone/Classes/TiUIWebViewProxy.m
Labels: bug 🐜, in-qe-testing 🕵, ios, no tests

#10785 fix(ios): cookie support for ios while using wkwebview
  iphone/Classes/TiUIWebView.m
  iphone/Classes/TiUIWebViewProxy.m
Labels: bug 🐜, in-qe-testing 🕵, ios, no tests

#10834 refactor(common): organize our js extensions, polyfills and apis
  common/Resources/ti.internal/extensions/index.js
  common/Resources/ti.internal/extensions/js/Error.js
  common/Resources/ti.internal/extensions/js/index.js
  common/Resources/ti.internal/extensions/node/assert.js
  common/Resources/ti.internal/extensions/node/index.js
  common/Resources/ti.internal/extensions/node/os.js
  common/Resources/ti.internal/extensions/node/path.js
  common/Resources/ti.internal/extensions/node/process.js
  common/Resources/ti.internal/extensions/node/tty.js
  common/Resources/ti.internal/extensions/node/util.js
  common/Resources/ti.internal/extensions/ti/index.js
  common/Resources/ti.internal/extensions/ti/ti.blob.js
  common/Resources/ti.main.js
Labels: needs jira 🚨, needs tests 🚨

#10842 fix(android): module clean should delete only generated libraries
  android/cli/commands/_cleanModule.js
Labels: bug 🐜, cli 📟

#10840 fix(ios): module builds broken
  build/lib/ios.js
  build/lib/utils.js
  iphone/cli/commands/_buildModule.js
  iphone/templates/module/objc/template/ios/titanium.xcconfig.ejs
  iphone/templates/module/swift/template/ios/titanium.xcconfig.ejs
Labels: bug 🐜, no tests

#10835 fix(build): ensure titanium_prep executables have executable permission set
  build/lib/packager.js
  support/android/titanium_prep.linux32
  support/android/titanium_prep.linux64
Labels: no tests

#10814 fix(ios): fix extension app group and entitlements support (8_0_X)
  iphone/cli/commands/_build.js
Labels: bug 🐜, in-qe-testing 🕵, ios

#10850 chore(deps): update dev dependencies
  package-lock.json
  package.json
Labels: needs jira 🚨

#10845 chore(android): cleanup snapshot generation
  build/lib/android/index.js
  build/lib/android/snapshot.js
Labels: android, no tests

#10838 fix(ios): fix for ‘target="_blank”’in html
  iphone/Classes/TiUIWebView.m
Labels: bug 🐜, in-qe-testing 🕵, ios, needs tests 🚨

#10839 fix(ios): fix for ‘target="_blank”’in html (8_0_X)
  iphone/Classes/TiUIWebView.m
Labels: bug 🐜, in-qe-testing 🕵, ios, needs tests 🚨

#10813 fix(ios): fix extension app group and entitlements support
  iphone/cli/commands/_build.js
Labels: bug 🐜, in-qe-testing 🕵, ios

#10819 fix(ios)(8_0_X): In local html make the base url as file url
  iphone/Classes/TiUIWebView.m
Labels: bug 🐜, in-qe-testing 🕵, ios, needs tests 🚨

#10832 fix(android): amend hasActivityTransitions() for transitions
  android/modules/ui/src/java/ti/modules/titanium/ui/TabGroupProxy.java
  android/titanium/src/java/org/appcelerator/titanium/TiLaunchActivity.java
  android/titanium/src/java/org/appcelerator/titanium/proxy/TiWindowProxy.java
Labels: android, bug 🐜, in-qe-testing 🕵, no tests

#10833 fix(android)(8_0_X): amend hasActivityTransitions() for transitions
  android/modules/ui/src/java/ti/modules/titanium/ui/TabGroupProxy.java
  android/titanium/src/java/org/appcelerator/titanium/TiLaunchActivity.java
  android/titanium/src/java/org/appcelerator/titanium/proxy/TiWindowProxy.java
Labels: android, bug 🐜, in-qe-testing 🕵, no tests

#10818 fix(ios): In local html make the base url as file url
  iphone/Classes/TiUIWebView.m
Labels: bug 🐜, in-qe-testing 🕵, ios, needs tests 🚨

#10795 feat(android): Re-added "baseURL" support to WebView.setHtml() method
  android/modules/ui/src/java/ti/modules/titanium/ui/WebViewProxy.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/webview/TiUIWebView.java
  apidoc/Titanium/UI/WebView.yml
Labels: android, docs 📔, improvement, in-qe-testing 🕵, no tests, parity 👯‍♀️

#10648 [TIMOB-4041] feat(android): support ListView.separatorStyle
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/listview/TiListView.java
  apidoc/Titanium/UI/ListView.yml
Labels: android, community 🔥, docs 📔, in-qe-testing 🕵, no tests

#10729 fix(ios): add missing runtime checks
  iphone/Classes/MediaModule.m
Labels: bug 🐜, in-qe-testing 🕵, ios, no tests

#10816 fix(ios): Give a time delay to scroll if search view is hiding on selection
  iphone/Classes/TiUITableView.h
  iphone/Classes/TiUITableView.m
  iphone/Classes/TiUITableViewProxy.m
Labels: bug 🐜, in-qe-testing 🕵, ios, no tests

#10564 feat(iOS): enable dampingRatio and springVelocity
  apidoc/Titanium/UI/Animation.yml
  iphone/TitaniumKit/TitaniumKit/Sources/API/TiAnimation.h
  iphone/TitaniumKit/TitaniumKit/Sources/API/TiAnimation.m
Labels: community 🔥, docs 📔, in-qe-testing 🕵, ios, no tests

#10425 [TIMOB-26523] iOS 11+: Expose UIFontTextStyleLargeTitle for dynamic fonts
  apidoc/Titanium/UI/UI.yml
  iphone/Classes/UIModule.h
  iphone/Classes/UIModule.m
  iphone/TitaniumKit/TitaniumKit/Sources/API/WebFont.h
  iphone/TitaniumKit/TitaniumKit/Sources/API/WebFont.m
  tests/Resources/ti.ui.addontest.js
Labels: community 🔥, docs 📔, improvement, in-qe-testing 🕵, ios

#10858 chore(package): update node-titanium-sdk to 3.1.0
  package-lock.json
  package.json
Labels: cli 📟, feature 🚀

#10812 fix(ios): remove hacky kroll-leftovers on app-termination
  iphone/TitaniumKit/TitaniumKit/Sources/API/TiApp.m
Labels: community 🔥, in-qe-testing 🕵, ios, no tests

#10760 [TIMOB-26885] fix(ios): prevent VC from being pushed twice
  iphone/Classes/TiUINavigationWindowProxy.m
  iphone/Classes/TiUITabProxy.m
Labels: bug 🐜, community 🔥, in-qe-testing 🕵, ios, no tests

#10849 fix(android)(8_0_X): Fixed bug where setting SearchBar "hintText" after window open crashes as of 7.0.0
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/TiUIText.java
  tests/Resources/ti.ui.searchbar.addontest.js
Labels: android, bug 🐜, in-qe-testing 🕵

#10848 fix(android): Fixed bug where setting SearchBar "hintText" after window open crashes as of 7.0.0
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/TiUIText.java
  tests/Resources/ti.ui.searchbar.addontest.js
Labels: android, bug 🐜, in-qe-testing 🕵

#10632 Android: WebView null exception fix
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/webview/TiUIWebView.java
Labels: android, community 🔥, in-qe-testing 🕵, no tests

#10645 feat(android): hide radio buttons OptionDialog
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/TiUIDialog.java
  apidoc/Titanium/UI/OptionDialog.yml
Labels: android, community 🔥, docs 📔, in-qe-testing 🕵, no tests

#10723 fix(ios) : delay push of window if navigation controller is not created
  iphone/Classes/TiUINavigationWindowProxy.m
  tests/Resources/ti.ui.navigationwindow.addontest.js
Labels: bug 🐜, in-qe-testing 🕵, ios

#10380 fix(android): optimize imageAsResized
  android/titanium/src/java/org/appcelerator/titanium/TiBlob.java
Labels: android, community 🔥, in-qe-testing 🕵, no tests

#10829 fix(android): Refactored activity/fragment restore handling
  android/modules/ui/src/java/ti/modules/titanium/ui/TabGroupProxy.java
  android/modules/ui/src/java/ti/modules/titanium/ui/WindowProxy.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/TiUIDialog.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/TiUIProgressIndicator.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/TiUIScrollableView.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/TiUITableView.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/listview/TiListView.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/searchbar/TiUISearchBar.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/tabgroup/TiUIAbstractTabGroup.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/tableview/TiTableView.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/tableview/TiTableViewHeaderItem.java
  android/titanium/src/java/org/appcelerator/titanium/TiActivity.java
  android/titanium/src/java/org/appcelerator/titanium/TiActivityWindow.java
  android/titanium/src/java/org/appcelerator/titanium/TiActivityWindows.java
  android/titanium/src/java/org/appcelerator/titanium/TiApplication.java
  android/titanium/src/java/org/appcelerator/titanium/TiBaseActivity.java
  android/titanium/src/java/org/appcelerator/titanium/TiC.java
  android/titanium/src/java/org/appcelerator/titanium/TiRootActivity.java
  android/titanium/src/java/org/appcelerator/titanium/proxy/TiWindowProxy.java
  android/titanium/src/java/org/appcelerator/titanium/util/TiUIHelper.java
  android/titanium/src/java/org/appcelerator/titanium/view/TiUIFragment.java
  android/titanium/src/java/org/appcelerator/titanium/view/TiUIView.java
Labels: android, bug 🐜, in-qe-testing 🕵, no tests

#10868 fix(android)(8_0_X): Refactored activity/fragment restore handling
  android/modules/ui/src/java/ti/modules/titanium/ui/TabGroupProxy.java
  android/modules/ui/src/java/ti/modules/titanium/ui/WindowProxy.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/TiUIDialog.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/TiUIProgressIndicator.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/TiUIScrollableView.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/TiUITableView.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/listview/TiListView.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/searchbar/TiUISearchBar.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/tabgroup/TiUIAbstractTabGroup.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/tableview/TiTableView.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/tableview/TiTableViewHeaderItem.java
  android/titanium/src/java/org/appcelerator/titanium/TiActivity.java
  android/titanium/src/java/org/appcelerator/titanium/TiActivityWindow.java
  android/titanium/src/java/org/appcelerator/titanium/TiActivityWindows.java
  android/titanium/src/java/org/appcelerator/titanium/TiApplication.java
  android/titanium/src/java/org/appcelerator/titanium/TiBaseActivity.java
  android/titanium/src/java/org/appcelerator/titanium/TiC.java
  android/titanium/src/java/org/appcelerator/titanium/TiRootActivity.java
  android/titanium/src/java/org/appcelerator/titanium/proxy/TiWindowProxy.java
  android/titanium/src/java/org/appcelerator/titanium/util/TiUIHelper.java
  android/titanium/src/java/org/appcelerator/titanium/view/TiUIFragment.java
  android/titanium/src/java/org/appcelerator/titanium/view/TiUIView.java
Labels: android, bug 🐜, in-qe-testing 🕵, no tests

#10859 fix(ios)(8_0_x): maintain native module proxies
  iphone/TitaniumKit/TitaniumKit/Sources/API/TiModule.m
Labels: ios, no tests
