Repository tidev/titanium-sdk, pull requests merged in 2019-02, with the labels that each got.

#10676 fix(android): skip inclusion of soasta module
  android/cli/commands/_build.js
Labels: android, in-qe-testing 🕵, no tests

#10677 fix(android)(8_0_X): skip inclusion of soasta module
  android/cli/commands/_build.js
Labels: android, in-qe-testing 🕵, no tests

#10674 fix(ios) : Doc updated to make Ti.UI.ShortcutItem android only
  apidoc/Titanium/UI/ShortcutItem.yml
  iphone/Classes/TiUIiOSProxy.h
  iphone/Classes/TiUIiOSProxy.m
Labels: docs 📔, in-qe-testing 🕵, ios, no tests

#10673 fix(ios) : Doc updated to make Ti.UI.ShortcutItem android only
  apidoc/Titanium/UI/ShortcutItem.yml
  iphone/Classes/TiUIiOSProxy.h
  iphone/Classes/TiUIiOSProxy.m
Labels: docs 📔, in-qe-testing 🕵, ios, no tests

#10686 fix(ios): fix stacktrace formatting
  iphone/TitaniumKit/TitaniumKit/Sources/API/TiExceptionHandler.m
Labels: bug 🐜, in-qe-testing 🕵, ios, no tests

#10688 fix(ios)(8_0_X): fix stacktrace formatting
  iphone/TitaniumKit/TitaniumKit/Sources/API/TiExceptionHandler.m
Labels: bug 🐜, in-qe-testing 🕵, ios, no tests

#10694 chore(deps): update to liveview@1.4.5
  package-lock.json
  package.json
Labels: in-qe-testing 🕵

#10692 chore(package): update to node-titanium-sdk 2.0.0
  package-lock.json
  package.json
Labels: needs jira 🚨

#10659 fix(ios): memory leak in require
  iphone/TitaniumKit/TitaniumKit/Sources/API/KrollBridge.m
Labels: bug 🐜, in-qe-testing 🕵, ios, no tests

#10685 fix(ios): rememberProxy call on overlay proxy for main thread
  iphone/Classes/MediaModule.m
Labels: bug 🐜, in-qe-testing 🕵, ios, no tests

#10678 fix(android)(7_5_X): Restored pre-7.5.0 behavior where "app.js" should be re-executed when launched via data intent while backgrounded
  common/Resources/ti.main.js
Labels: android, bug 🐜, no tests

#10701 chore: update facebook module to latest version (8_0_X)
  support/module/packaged/modules.json
Labels: BREAKING CHANGES ⚠️, android, ios

#10698 fix(ios): swift module’s app.js template made correct
  iphone/templates/module/swift/template/ios/Classes/{{ModuleIdAsIdentifier}}Module.swift.ejs
Labels: bug 🐜, ios, no tests

#10699 fix(iOS): swift module’s app.js template made correct (8_0_X)
  iphone/templates/module/swift/template/ios/Classes/{{ModuleIdAsIdentifier}}Module.swift.ejs
Labels: bug 🐜, in-qe-testing 🕵, ios, no tests

#10703 fix(android)(8_0_X): fix copying of resources
  android/cli/commands/_build.js
Labels: android, bug 🐜, in-qe-testing 🕵, no tests

#10700 chore: update facebook module to latest version
  support/module/packaged/modules.json
Labels: BREAKING CHANGES ⚠️, android, in-qe-testing 🕵, ios

#10702 fix(android): fix copying of resources
  android/cli/commands/_build.js
Labels: android, bug 🐜, in-qe-testing 🕵, no tests

#10714 doc(android): Updated "Ti.UI.NavigationWindow" to indicate Android support
  apidoc/Titanium/UI/NavigationWindow.yml
Labels: android, docs 📔

#10720 fix(android)(7_5_X): update ti.cloudpush to 6.0.0
  support/module/packaged/modules.json
Labels: android, bug 🐜, no tests

#10721 fix(ios)(7_5_X): avoid multiple dismiss calls of UISearchController
  iphone/Classes/TiUIListView.m
Labels: bug 🐜, ios, no tests

#10724 chore(android)(7_5_X): update ti.playservices to 16.1.2
  support/module/packaged/modules.json
Labels: android, needs jira 🚨, no tests

#10707 fix(ios): cancel pending local notifications (7_5_X)
  apidoc/Titanium/App/iOS/UserNotificationCenter.yml
  iphone/Classes/TiApp.m
  iphone/Classes/TiAppiOSProxy.m
  iphone/Classes/TiAppiOSUserNotificationCenterProxy.m
Labels: bug 🐜, docs 📔, ios, no tests

#10716 fix(android): update ti.cloudpush to 6.0.0
  support/module/packaged/modules.json
Labels: android, bug 🐜, no tests

#10726 fix(android,ios)(7_5_X): reject non-string defaults for Ti.Locale.getString()
  android/modules/locale/src/java/ti/modules/titanium/locale/LocaleModule.java
  android/modules/locale/src/js/locale.js
  android/runtime/common/src/js/titanium.js
  android/titanium/src/java/org/appcelerator/titanium/TiBaseActivity.java
  android/titanium/src/java/org/appcelerator/titanium/proxy/ActivityProxy.java
  android/titanium/src/java/org/appcelerator/titanium/util/TiLocaleManager.java
  apidoc/Titanium/Android/Activity.yml
  apidoc/Titanium/Locale/Locale.yml
  iphone/Classes/KrollContext.m
  iphone/Classes/LocaleModule.m
  tests/Resources/ti.locale.test.js
Labels: android, bug 🐜, docs 📔, ios, no tests

#10727 fix(android)(7_5_X): update ti.playservices integrity hash
  support/module/packaged/modules.json
Labels: android, needs jira 🚨, no tests

#10717 fix(android)(8_0_X): update ti.cloudpush to 6.0.0
  support/module/packaged/modules.json
Labels: android, bug 🐜, no tests

#10693 feat(android): Add "barColor" property of Ti.UI.Window to Android.
  android/modules/ui/src/java/ti/modules/titanium/ui/WindowProxy.java
  apidoc/Titanium/UI/Window.yml
Labels: android, docs 📔, feature 🚀, no tests, parity 👯‍♀️

#10735 fix: remove unmarking of @babel/polyfill during android build
  android/cli/commands/_build.js
Labels: android, bug 🐜, cli 📟, in-qe-testing 🕵

#10730 build(jenkins): target android-23-x86 emulator
  Jenkinsfile
Labels: needs jira 🚨
