Repository tidev/titanium-sdk, pull requests merged in 2019-11, with the labels that each got.

#11313 ci(jenkins): try to record clang and java compile warnings
  Jenkinsfile
Labels: needs jira 🚨

#11302 fix(android): do not set properties on recycled proxy
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/TiUIDialog.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/listview/ListSectionProxy.java
  android/titanium/src/java/org/appcelerator/kroll/KrollProxy.java
  android/titanium/src/java/org/appcelerator/titanium/proxy/MenuItemProxy.java
  android/titanium/src/java/org/appcelerator/titanium/view/TiUIView.java
Labels: android, bug 🐜, in-qe-testing 🕵, no tests

#11309 fix(android): amend constants for showSoftKeyboard()
  android/titanium/src/java/org/appcelerator/titanium/util/TiUIHelper.java
Labels: android, bug 🐜, in-qe-testing 🕵, no tests

#11311 fix(ios): fix webview basic authentication
  iphone/Classes/TiUIWebViewProxy.m
  tests/Resources/ti.ui.webview.addontest.js
Labels: bug 🐜, community 🔥, in-qe-testing 🕵, ios

#11305 docs: add missing comma
  apidoc/Titanium/UI/Picker.yml
Labels: community 🔥, docs 📔, needs jira 🚨

#11303 fix(ios): ipad popover crash
  iphone/TitaniumKit/TitaniumKit/Sources/API/TiRootViewController.m
Labels: bug 🐜, in-qe-testing 🕵, ios, needs tests 🚨

#11319 fix(android): do not modify original ListView proxy
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/listview/ListItemProxy.java
Labels: android, bug 🐜, no tests

#11323 fix(android)(8_3_X): do not modify original ListView proxy
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/listview/ListItemProxy.java
Labels: android, bug 🐜, no tests

#11324 fix(ios): setting last index of tabbedBar after initialization not work
  iphone/Classes/TiUIButtonBar.m
Labels: bug 🐜, in-qe-testing 🕵, ios, no tests

#11325 fix(iOS)(8_3_X): setting last index of tabbedBar after initialization not work
  iphone/Classes/TiUIButtonBar.m
Labels: android, bug 🐜, in-qe-testing 🕵, ios, no tests

#11334 fix(windows): fire analyzeJsFile hook for Windows
  cli/lib/tasks/process-js-task.js
Labels: bug 🐜, in-qe-testing 🕵, windows

#11337 fix(android)(8_3_X): amend load app info order
  android/templates/build/App.java
Labels: android, bug 🐜, in-qe-testing 🕵, no tests

#11338 fix(android)(8_3_X): softRestart() must account for snapshots
  android/titanium/src/java/org/appcelerator/titanium/TiApplication.java
  android/titanium/src/java/org/appcelerator/titanium/TiLaunchActivity.java
  build/lib/android/startup.ejs
Labels: android, bug 🐜, in-qe-testing 🕵, no tests

#11333 fix(windows): fire analyzeJsFile hook for Windows
  cli/lib/tasks/process-js-task.js
Labels: bug 🐜, in-qe-testing 🕵, windows

#11340 chore: update ti.cloak
  support/ti.cloak.zip
Labels: bug 🐜, in-qe-testing 🕵, no tests, windows

#11341 chore(8_3_X): update ti.cloak
  support/ti.cloak.zip
Labels: no tests

#11336 build(node): drop node 8, support node 10.13+, node 12
  Jenkinsfile
  package.json
Labels: in-qe-testing 🕵

#11335 docs(changelog): update script to include bundled module versions
  changelog/config.js
  changelog/templates/modules.hbs
  changelog/templates/template.hbs
Labels: docs 📔, needs jira 🚨

#11344 fix(android)(8_3_X): add extension to encrypted assets
  android/cli/commands/_build.js
  android/templates/build/AssetCryptImpl.java
Labels: android, bug 🐜, in-qe-testing 🕵, no tests

#11351 fix(android): add extension to encrypted assets
  android/cli/commands/_build.js
  android/templates/build/AssetCryptImpl.java
Labels: android, bug 🐜, no tests

#11356 chore(ios)(8_3_X): update libAPSAnalytics.a
  iphone/TitaniumKit/TitaniumKit/Libraries/APSAnalytics/libAPSAnalytics.a
Labels: bug 🐜, ios

#11345 chore(ios): update libAPSAnalytics.a
  iphone/TitaniumKit/TitaniumKit/Libraries/APSAnalytics/libAPSAnalytics.a
Labels: in-qe-testing 🕵, ios, no tests

#11359 docs: remove duplicate prop "category" from "localnotificationaction"
  apidoc/Titanium/App/iOS/iOS.yml
Labels: community 🔥, docs 📔, needs jira 🚨

#11358 docs: mark as optional property "animated" of AnimationOption
  apidoc/Titanium/UI/View.yml
Labels: community 🔥, docs 📔, needs jira 🚨

#11353 docs: add Ti.UI.View.id property
  apidoc/Titanium/UI/View.yml
Labels: community 🔥, docs 📔, needs jira 🚨

#11367 fix(android): prevent snapshots from failing build
  android/cli/commands/_build.js
  android/titanium/src/java/org/appcelerator/titanium/TiApplication.java
  android/titanium/src/java/org/appcelerator/titanium/TiLaunchActivity.java
  build/lib/android/V8Snapshots.h.ejs
  build/lib/android/index.js
  build/lib/android/snapshot.js
Labels: android, bug 🐜, no tests

#11241 fix(android): use correct blob for toImage()
  android/modules/ui/src/java/ti/modules/titanium/ui/ImageViewProxy.java
Labels: android, bug 🐜, in-qe-testing 🕵, no tests
