Repository tidev/titanium-sdk, pull requests merged in 2019-05, with the labels that each got.

#10867 chore(android): bump ti.playservices to 16.1.3
  build/lib/utils.js
  build/scons-modules-integrity.js
  support/module/packaged/modules.json
Labels: android, in-qe-testing 🕵, no tests

#10393 [TIMOB-26390] Android: Connect getters with background drawables for Unit test purposes.
  android/titanium/src/java/org/appcelerator/titanium/TiC.java
  android/titanium/src/java/org/appcelerator/titanium/proxy/TiViewProxy.java
  android/titanium/src/java/org/appcelerator/titanium/util/TiUIHelper.java
  tests/Resources/ti.ui.view.addontest.js
Labels: android, bug 🐜, in-qe-testing 🕵

#10855 fix(ios): maintain native module proxies
  iphone/TitaniumKit/TitaniumKit/Sources/API/TiModule.m
Labels: bug 🐜, in-qe-testing 🕵, ios, no tests

#10851 chore(ios,android): update aps analytics
  android/titanium/lib/aps-analytics.jar
  iphone/TitaniumKit/TitaniumKit/Libraries/APSAnalytics/APSAnalytics.h
  iphone/TitaniumKit/TitaniumKit/Libraries/APSAnalytics/APSUtility.h
  iphone/TitaniumKit/TitaniumKit/Libraries/APSAnalytics/libAPSAnalytics.a
Labels: android, ios, needs jira 🚨, no tests

#10492 TIMOB-26599 Optionally disable video compression when importing video
  apidoc/Titanium/Media/Media.yml
  iphone/Classes/MediaModule.m
Labels: community 🔥, docs 📔, ios, no tests

#10772 fix(ios): delay js object creation to prevent accidental GC (8_0_X)
  iphone/TitaniumKit/TitaniumKit/Sources/API/KrollBridge.m
  iphone/TitaniumKit/TitaniumKit/Sources/API/TiBindingEvent.m
  iphone/TitaniumKit/TitaniumKit/Sources/API/TiBindingTiValue.m
  iphone/TitaniumKit/TitaniumKit/Sources/API/TiProxy.m
  iphone/TitaniumKit/TitaniumKit/Sources/Kroll/KrollObject.h
  iphone/TitaniumKit/TitaniumKit/Sources/Kroll/KrollObject.m
Labels: bug 🐜, in-qe-testing 🕵, ios, no tests

#10871 Update RecurrenceRule.yml
  apidoc/Titanium/Calendar/RecurrenceRule.yml
Labels: docs 📔

#10771 fix(ios): delay js object creation to prevent accidental GC
  iphone/TitaniumKit/TitaniumKit/Sources/API/KrollBridge.m
  iphone/TitaniumKit/TitaniumKit/Sources/API/TiBindingEvent.m
  iphone/TitaniumKit/TitaniumKit/Sources/API/TiBindingTiValue.m
  iphone/TitaniumKit/TitaniumKit/Sources/API/TiProxy.m
  iphone/TitaniumKit/TitaniumKit/Sources/Kroll/KrollObject.h
  iphone/TitaniumKit/TitaniumKit/Sources/Kroll/KrollObject.m
Labels: bug 🐜, in-qe-testing 🕵, ios, no tests

#10886 fix(ios): disable log server when not being used
  iphone/TitaniumKit/TitaniumKit/Sources/API/TiApp.m
  iphone/TitaniumKit/TitaniumKit/Sources/API/TiBase.m
  iphone/TitaniumKit/TitaniumKit/Sources/API/TiLogServer.h
  iphone/TitaniumKit/TitaniumKit/Sources/API/TiLogServer.m
  iphone/TitaniumKit/TitaniumKit/Sources/Misc/TiSharedConfig.h
  iphone/iphone/main.m
  support/iphone/main.m
Labels: bug 🐜, ios, no tests

#10869 fix(ios): disable log server when not being used
  iphone/TitaniumKit/TitaniumKit/Sources/API/TiApp.m
  iphone/TitaniumKit/TitaniumKit/Sources/API/TiBase.m
  iphone/TitaniumKit/TitaniumKit/Sources/API/TiLogServer.h
  iphone/TitaniumKit/TitaniumKit/Sources/API/TiLogServer.m
  iphone/TitaniumKit/TitaniumKit/Sources/Misc/TiSharedConfig.h
  iphone/iphone/main.m
  support/iphone/main.m
Labels: bug 🐜, in-qe-testing 🕵, ios, no tests

#10882 Update SystemButton.yml
  apidoc/Titanium/UI/iOS/SystemButton.yml
  apidoc/images/systembutton/system_icons.png
Labels: docs 📔

#10770 fix(android): Modified "Ti.Database" install() and open() methods
  android/modules/database/src/java/ti/modules/titanium/database/DatabaseModule.java
  tests/Resources/ti.database.addontest.js
Labels: android, bug 🐜, improvement

#10864 [TIMOB-26973] iOS: Add accessibilityIdentifier
  iphone/Classes/TiUINavBarButton.m
  iphone/TitaniumKit/TitaniumKit/Sources/API/TiUIView.m
  iphone/TitaniumKit/TitaniumKit/Sources/API/TiUtils.h
  iphone/TitaniumKit/TitaniumKit/Sources/API/TiUtils.m
Labels: community 🔥, improvement, in-qe-testing 🕵, ios, no tests, parity 👯‍♀️

#10653 refactor(docs): use markdown-it to parse markdown
  apidoc/lib/changes_generator.js
  apidoc/lib/common.js
  apidoc/lib/html_generator.js
  apidoc/lib/jsca_generator.js
  apidoc/lib/jsduck_generator.js
  apidoc/lib/json_generator.js
  apidoc/validate.js
  package-lock.json
  package.json
Labels: docs 📔, improvement, in-qe-testing 🕵

#10898 build(jenkins): add timeout for adb commands
  Jenkinsfile
Labels: needs jira 🚨

#10888 fix(android): APK signing will fail when using MD5 keystore and JDK 8+
  android/cli/commands/_build.js
Labels: android, bug 🐜, in-qe-testing 🕵

#10667 docs(api): remove notes about heavyweight windows
  apidoc/Titanium/UI/Window.yml
Labels: docs 📔, in-qe-testing 🕵, needs jira 🚨

#10668 docs(api): review Ti.UI.View docs
  apidoc/Titanium/UI/View.yml
Labels: docs 📔, in-qe-testing 🕵, needs jira 🚨

#10887 fix(android): Fixed bug where Label "ellipsize" modes START/MIDDLE don't work if "autoLink" is true
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/TiUILabel.java
Labels: android, bug 🐜, in-qe-testing 🕵, no tests

#10725 fix(ios): properly copy completion handlers, remove duplicate UIApplicationDelegate selectors
  iphone/Classes/TiApp+Addons.h
  iphone/Classes/TiApp+Addons.m
  iphone/TitaniumKit/TitaniumKit/Sources/API/TiApp.m
  iphone/TitaniumKit/TitaniumKit/Sources/Kroll/KrollObject.h
Labels: bug 🐜, community 🔥, in-qe-testing 🕵, ios, no tests

#10900 fix(android)(8_0_X): Improved merge of "tiapp.xml" android manifest settings
  android/cli/commands/_build.js
  android/cli/lib/AndroidManifest.js
  android/templates/build/AndroidManifest.xml
Labels: android, bug 🐜, in-qe-testing 🕵, no tests

#10884 fix(android): Improved merge of "tiapp.xml" android manifest settings
  android/cli/commands/_build.js
  android/cli/lib/AndroidManifest.js
  android/templates/build/AndroidManifest.xml
Labels: android, bug 🐜, in-qe-testing 🕵, no tests

#10889 fix(android)(8_0_X): APK signing will fail when using MD5 keystore and JDK 8+
  android/cli/commands/_build.js
Labels: android, bug 🐜, in-qe-testing 🕵

#10665 docs(api): fix table markup
  apidoc/Titanium/App/App.yml
  apidoc/Titanium/Network/HTTPClient.yml
  apidoc/Titanium/UI/2DMatrix.yml
  apidoc/Titanium/UI/ActivityIndicator.yml
  apidoc/Titanium/UI/AlertDialog.yml
  apidoc/Titanium/UI/Button.yml
  apidoc/Titanium/UI/EmailDialog.yml
  apidoc/Titanium/UI/ListView.yml
  apidoc/Titanium/UI/Matrix2D.yml
  apidoc/Titanium/UI/OptionDialog.yml
  apidoc/Titanium/UI/Picker.yml
  apidoc/Titanium/UI/ProgressBar.yml
  apidoc/Titanium/UI/SearchBar.yml
  apidoc/Titanium/UI/Slider.yml
  apidoc/Titanium/UI/Switch.yml
  apidoc/Titanium/UI/TableView.yml
  apidoc/Titanium/UI/TextArea.yml
  apidoc/Titanium/UI/TextField.yml
  apidoc/Titanium/UI/View.yml
  apidoc/Titanium/UI/iOS/Stepper.yml
Labels: docs 📔, improvement, in-qe-testing 🕵, needs jira 🚨

#10902 fix(ios): properly retain geolocation callback
  iphone/Classes/GeolocationModule.m
Labels: community 🔥, ios, needs tests 🚨

#10899 Update CloudPush.yml
  apidoc/Modules/CloudPush/CloudPush.yml
Labels: docs 📔

#10843 Update Proxy.yml
  apidoc/Titanium/Proxy.yml
Labels: docs 📔

#10866 Update RecurrenceRule.yml
  apidoc/Titanium/Calendar/RecurrenceRule.yml
Labels: docs 📔, needs jira 🚨

#10901 fix(ios): force alert() messages to be a string
  iphone/TitaniumKit/TitaniumKit/Sources/Kroll/KrollContext.m
Labels: bug 🐜, community 🔥, in-qe-testing 🕵, ios, no tests

#10909 docs: correct Android LocationProvider example
  apidoc/Titanium/Geolocation/Android/Android.yml
Labels: docs 📔, needs jira 🚨

#10713 doc(android): Updated "Ti.UI.NavigationWindow" to indicate Android support
  apidoc/Titanium/UI/NavigationWindow.yml
Labels: android, docs 📔, in-qe-testing 🕵

#10913 fix(ios): allow music-player in MediaPlayer import (8.0.1+ regression)
  iphone/Classes/MediaModule.h
  iphone/Classes/MediaModule.m
Labels: bug 🐜, community 🔥, in-qe-testing 🕵, ios, needs tests 🚨

#10915 chore(package): update ioslib to 1.7.7
  package-lock.json
  package.json
Labels: bug 🐜, cli 📟, in-qe-testing 🕵, ios

#10907 fix(ios): don't log error about missing use of filesystem api
  iphone/TitaniumKit/TitaniumKit/Sources/API/TiBlob.m
Labels: bug 🐜, in-qe-testing 🕵, ios, no tests

#10919 fix(ios): close database with correct selector during shutdown
  iphone/Classes/TiDatabaseProxy.m
Labels: bug 🐜, in-qe-testing 🕵, ios, no tests

#10872 [TIMOB-27049] fix(ios): call super after implementation in "sendEvent:" delegate selector
  iphone/Classes/TiUIApplication.m
Labels: community 🔥, in-qe-testing 🕵, ios, no tests

#10862 fix(ios): don't add exception handler to js context, breaks usage when timers throw exceptions
  iphone/TitaniumKit/TitaniumKit/Sources/Kroll/KrollTimerManager.m
Labels: bug 🐜, ios, needs jira 🚨, no tests

#10914 fix(ios): properly check available extension build phases
  iphone/cli/commands/_build.js
Labels: bug 🐜, cli 📟, community 🔥, in-qe-testing 🕵, ios, no tests

#10897 [TIMOB-27082] fix(ios): restore SDK < 8.1.0 compatibility
  iphone/Classes/TiCalendarAlert.h
  iphone/Classes/TiCalendarAlert.m
  iphone/Classes/TiCalendarAttendee.h
  iphone/Classes/TiCalendarAttendee.m
  iphone/Classes/TiCalendarCalendar.h
  iphone/Classes/TiCalendarCalendar.m
  iphone/Classes/TiCalendarEvent.h
  iphone/Classes/TiCalendarEvent.m
  iphone/Classes/TiCalendarRecurrenceRule.h
  iphone/Classes/TiCalendarRecurrenceRule.m
  iphone/Classes/TiDatabaseResultSetProxy.h
  iphone/Classes/TiDatabaseResultSetProxy.m
  iphone/TitaniumKit/TitaniumKit/Sources/API/ObjcProxy.h
  iphone/TitaniumKit/TitaniumKit/Sources/API/ObjcProxy.m
  iphone/TitaniumKit/TitaniumKit/Sources/API/TiBlob.h
  iphone/TitaniumKit/TitaniumKit/Sources/API/TiBlob.m
Labels: community 🔥, ios, needs tests 🚨

#10881 feat(android): Added Ti.Platform.canOpenURL() support
  android/modules/platform/src/java/ti/modules/titanium/platform/PlatformModule.java
  android/titanium/src/java/org/appcelerator/titanium/TiC.java
  android/titanium/src/java/org/appcelerator/titanium/io/TiFileProvider.java
  android/titanium/src/java/org/appcelerator/titanium/util/TiMimeTypeHelper.java
  apidoc/Titanium/Platform/Platform.yml
Labels: android, docs 📔, feature 🚀, in-qe-testing 🕵, no tests, parity 👯‍♀️

#10666 docs(ListView)Minor updates
  apidoc/Titanium/UI/ListView.yml
Labels: docs 📔, in-qe-testing 🕵, needs jira 🚨

#10883 fix(ios)(8_0_X): Instead of native exception send javascript exception
  iphone/TitaniumKit/TitaniumKit/Sources/Kroll/KrollContext.m
Labels: bug 🐜, in-qe-testing 🕵, ios, no tests

#10921 fix(ios): Instead of native exception send javascript exception
  iphone/TitaniumKit/TitaniumKit/Sources/Kroll/KrollContext.m
Labels: bug 🐜, in-qe-testing 🕵, ios, no tests
