Repository tidev/titanium-sdk, pull requests merged in 2019-10, with the labels that each got.

#11249 fix(ios): fix TiBase header to order macros properly, re-use macros
  iphone/TitaniumKit/TitaniumKit/Sources/API/TiBase.h
Labels: bug 🐜, ios, needs jira 🚨, needs tests 🚨

#11027 fix(ios): verify module class type
  iphone/TitaniumKit/TitaniumKit/Sources/API/TiHost.m
Labels: bug 🐜, in-qe-testing 🕵, ios, no tests

#11177 fix(android): fix onlink callback being cretion only
  android/modules/ui/src/java/ti/modules/titanium/ui/WebViewProxy.java
Labels: android, bug 🐜, in-qe-testing 🕵, needs tests 🚨, parity 👯‍♀️

#11197 impr(android): implement foregroundServiceType parameter
  android/cli/lib/AndroidManifest.js
  android/modules/android/src/java/ti/modules/titanium/android/AndroidModule.java
  android/titanium/src/java/org/appcelerator/titanium/proxy/ServiceProxy.java
  apidoc/Titanium/Android/Android.yml
  apidoc/Titanium/Android/Service.yml
Labels: android, docs 📔, improvement, in-qe-testing 🕵, no tests

#11226 fix(ios): localnotificationaction event contains notification id instead of the action id
  iphone/TitaniumKit/TitaniumKit/Sources/API/TiApp.m
Labels: in-qe-testing 🕵, ios, needs tests 🚨

#11240 fix(ios): hideShadow handling for iOS 13
  iphone/TitaniumKit/TitaniumKit/Sources/Modules/TiUIWindowProxy.m
Labels: bug 🐜, in-qe-testing 🕵, ios, no tests

#11258 fix(conditions): Change from ifdef to if due to variable always being defined
  iphone/Classes/TiUIApplicationShortcutsProxy.m
  iphone/Classes/TiUIiOSApplicationShortcutsProxy.m
Labels: bug 🐜, ios, no tests

#11255 fix(conditions): Change from ifdef to if due to variable always being defined
  iphone/Classes/TiUIApplicationShortcutsProxy.m
  iphone/Classes/TiUIiOSApplicationShortcutsProxy.m
Labels: bug 🐜, in-qe-testing 🕵, ios, no tests

#11243 fix(ios): guard source property and removed NSNull if it is nil
  iphone/TitaniumKit/TitaniumKit/Sources/API/TiApp.m
Labels: bug 🐜, in-qe-testing 🕵, ios, no tests

#11242 fix(ios): guard source property and removed NSNull if it is nil
  iphone/TitaniumKit/TitaniumKit/Sources/API/TiApp.m
Labels: bug 🐜, in-qe-testing 🕵, ios, no tests

#11253 fix(android): performance issue with deeply nested views as of 7.5.0
  android/titanium/src/java/org/appcelerator/titanium/view/TiCompositeLayout.java
Labels: android, bug 🐜, in-qe-testing 🕵, no tests

#11256 fix(ios): close window handling from presentationController’s delegate method
  iphone/TitaniumKit/TitaniumKit/Sources/API/TiControllerProtocols.h
  iphone/TitaniumKit/TitaniumKit/Sources/API/TiViewController.h
  iphone/TitaniumKit/TitaniumKit/Sources/API/TiViewController.m
  iphone/TitaniumKit/TitaniumKit/Sources/API/TiWindowProxy.m
Labels: bug 🐜, in-qe-testing 🕵, ios, no tests

#11247 chore(ios): support new property to remove note
  apidoc/Titanium/Contacts/Contacts.yml
  iphone/Classes/ContactsModule.h
  iphone/Classes/ContactsModule.m
Labels: docs 📔, in-qe-testing 🕵, ios, no tests

#11238 fix(ios): update ti.applesignin module to 1.1.1
  support/module/packaged/modules.json
Labels: bug 🐜, in-qe-testing 🕵, ios

#11252 fix(android): update log strings TIMOB-7786
  android/titanium/src/java/ti/modules/titanium/codec/CodecModule.java
Labels: android, community 🔥, in-qe-testing 🕵, no tests

#11074 feat(ios,android): expose Ti.UI.Slider „tintColor“ and „trackTintColor“
  android/modules/ui/src/java/ti/modules/titanium/ui/SliderProxy.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/TiUIProgressBar.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/TiUISlider.java
  apidoc/Titanium/UI/Slider.yml
  iphone/Classes/TiUISlider.m
  tests/Resources/ti.ui.slider.addontest.js
Labels: android, community 🔥, docs 📔, in-qe-testing 🕵, ios

#11254 fix(android)(8_2_X): performance issue with deeply nested views as of 7.5.0
  android/titanium/src/java/org/appcelerator/titanium/view/TiCompositeLayout.java
Labels: android, bug 🐜, in-qe-testing 🕵, no tests

#11266 feat(ti.map): update to 3.3.0-ios, 4.5.0-android module releases
  support/module/packaged/modules.json
Labels: android, feature 🚀, ios

#11261 feat(ti.map): update to 3.3.0-ios, 4.5.0-android module releases
  support/module/packaged/modules.json
Labels: android, feature 🚀, ios

#11264 fix(ios): hide dimming view
  iphone/Classes/TiUIListView.m
  iphone/Classes/TiUITableView.m
Labels: bug 🐜, in-qe-testing 🕵, ios, no tests

#11228 fix(ios): select a valid ios sim xcodebuild destination
  iphone/cli/commands/_build.js
  package-lock.json
  package.json
Labels: bug 🐜, cli 📟, in-qe-testing 🕵, ios

#11235 fix(ios): select a valid ios sim xcodebuild destination [backport]
  iphone/cli/commands/_build.js
  package-lock.json
  package.json
Labels: in-qe-testing 🕵

#11263 fix(ios): hide dimming view
  iphone/Classes/TiUIListView.m
  iphone/Classes/TiUITableView.m
Labels: bug 🐜, in-qe-testing 🕵, ios, no tests

#11257 fix(ios): close window handling from presentationController’s delegate method
  iphone/TitaniumKit/TitaniumKit/Sources/API/TiControllerProtocols.h
  iphone/TitaniumKit/TitaniumKit/Sources/API/TiViewController.h
  iphone/TitaniumKit/TitaniumKit/Sources/API/TiViewController.m
  iphone/TitaniumKit/TitaniumKit/Sources/API/TiWindowProxy.m
Labels: bug 🐜, in-qe-testing 🕵, ios, no tests

#11237 Update App.yml to fix formatting issue in TIDOC-3379
  apidoc/Titanium/App/App.yml
Labels: docs 📔

#11273 fix(ios): app crashes when error happens in fetching location
  iphone/Classes/GeolocationModule.m
Labels: bug 🐜, in-qe-testing 🕵, ios, no tests

#11268 fix(iOS)(8_2_X): can not show fullscreen modal windows anymore
  iphone/TitaniumKit/TitaniumKit/Sources/API/TiRootViewController.m
  iphone/TitaniumKit/TitaniumKit/Sources/API/TiViewController.m
  iphone/TitaniumKit/TitaniumKit/Sources/API/TiWindowProxy.m
Labels: ios, no tests

#11267 fix(ios): can not show fullscreen modal windows anymore
  iphone/TitaniumKit/TitaniumKit/Sources/API/TiRootViewController.m
  iphone/TitaniumKit/TitaniumKit/Sources/API/TiViewController.m
  iphone/TitaniumKit/TitaniumKit/Sources/API/TiWindowProxy.m
Labels: in-qe-testing 🕵, ios, no tests

#11277 fix(android): focus on TextInputEditText view
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/TiUIText.java
  android/titanium/src/java/org/appcelerator/titanium/util/TiUIHelper.java
Labels: android, bug 🐜, in-qe-testing 🕵, no tests

#11274 fix(ios): remove additional gc protection once proxy is remembered (8_2_X)
  iphone/Classes/TiAppiOSProxy.h
  iphone/Classes/TiAppiOSProxy.m
  iphone/TitaniumKit/TitaniumKit/Sources/API/TiProxy.m
Labels: bug 🐜, in-qe-testing 🕵, ios, no tests

#11028 fix(ios): remove additional gc protection once proxy is remembered
  iphone/TitaniumKit/TitaniumKit/Sources/API/TiProxy.m
Labels: bug 🐜, in-qe-testing 🕵, ios, no tests

#11278 fix(android)(8_2_X): focus on TextInputEditText view
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/TiUIText.java
  android/titanium/src/java/org/appcelerator/titanium/util/TiUIHelper.java
Labels: android, bug 🐜, no tests

#11269 build: allow building a windows ti.main.js
  Jenkinsfile
  build/scons-build.js
Labels: in-qe-testing 🕵

#11236 docs(android): fix permission example for Android 8
  apidoc/Titanium/Android/Android.yml
Labels: community 🔥, docs 📔, needs jira 🚨

#11275 fix(android): support Geolocation altitudeAccuracy
  android/modules/geolocation/src/java/ti/modules/titanium/geolocation/GeolocationModule.java
  apidoc/Titanium/Geolocation/Geolocation.yml
Labels: android, docs 📔, improvement, in-qe-testing 🕵, no tests

#11285 docs: deprecate Ti.Analytics.navEvent
  apidoc/Titanium/Analytics/Analytics.yml
Labels: deprecation, docs 📔, no tests

#11284 feat(android): target api level 29 by default
  android/package.json
Labels: android, improvement, in-qe-testing 🕵, no tests

#11245 fix(ios): added xcworkspacedata file generation
  iphone/cli/commands/_build.js
  iphone/cli/hooks/run.js
  iphone/iphone/Titanium.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  support/iphone/main.m
Labels: in-qe-testing 🕵

#11281 Fix xcodebuild dest, bump min iOS target to 9, disable ONLY_ACTIVE_ARCH for 32-bit sims
  iphone/cli/commands/_build.js
  iphone/iphone/Titanium.xcodeproj/project.pbxproj
  package-lock.json
  package.json
Labels: in-qe-testing 🕵

#11213 fix(ios): inverted condition on baseURL construction
  iphone/Classes/TiUIWebView.m
  tests/Resources/ti.ui.webview.addontest.js
Labels: bug 🐜, community 🔥, in-qe-testing 🕵, ios

#11168 fix(android): fix onprogress payload value for data other than HashMap
  android/modules/network/src/java/ti/modules/titanium/network/TiHTTPClient.java
  tests/Resources/ti.network.httpclient.addontest.js
Labels: android, bug 🐜, in-qe-testing 🕵

#11262 fix(android): VideoPlayer with border fails to render as of 8.3.0
  android/titanium/src/java/org/appcelerator/titanium/view/TiUIView.java
Labels: android, bug 🐜, in-qe-testing 🕵, no tests

#11293 chore(npm): updated ioslib@1.7.16 [TIMOB-27490]
  package-lock.json
  package.json
Labels: bug 🐜, cli 📟, in-qe-testing 🕵, ios, no tests

#11291 fix(ios): set dest to generic iOS sim [TIMOB-27488]
  iphone/cli/commands/_build.js
Labels: bug 🐜, cli 📟, in-qe-testing 🕵, ios, no tests

#11290 fix(ios): set dest to generic iOS sim [TIMOB-27488]
  iphone/cli/commands/_build.js
Labels: in-qe-testing 🕵

#11292 chore(npm): updated ioslib@1.7.16 [TIMOB-27490]
  package-lock.json
  package.json
Labels: in-qe-testing 🕵

#11045 refactor(android): asset handling
  .eslintrc
  android/cli/commands/_build.js
  android/cli/commands/_buildModule.js
  android/modules/android/src/java/ti/modules/titanium/android/TiBroadcastReceiver.java
  android/modules/android/src/java/ti/modules/titanium/android/TiJSIntervalService.java
  android/modules/android/src/java/ti/modules/titanium/android/TiJSService.java
  android/modules/android/src/java/ti/modules/titanium/android/quicksettings/TiJSQuickSettingsService.java
  android/runtime/common/src/java/org/appcelerator/kroll/KrollRuntime.java
  android/runtime/common/src/java/org/appcelerator/kroll/util/KrollAssetHelper.java
  android/runtime/v8/src/java/org/appcelerator/kroll/runtime/v8/V8Runtime.java
  android/runtime/v8/src/native/JNIUtil.cpp
  android/runtime/v8/src/native/TypeConverter.cpp
  android/runtime/v8/src/native/TypeConverter.h
  android/runtime/v8/src/native/V8Runtime.cpp
  android/runtime/v8/src/native/modules/AssetsModule.cpp
  android/templates/build/AssetCryptImpl.java
  android/templates/module/generated/CommonJsSourceProvider.java.ejs
  android/titanium/src/java/org/appcelerator/titanium/TiApplication.java
  android/titanium/src/java/org/appcelerator/titanium/TiLaunchActivity.java
  android/titanium/src/java/org/appcelerator/titanium/TiRootActivity.java
  build/lib/packager.js
  support/android/lib/ti.cloak.jar
  support/android/msvcr71.dll
  support/android/titanium_prep.linux32
  support/android/titanium_prep.linux64
  support/android/titanium_prep.macos
  support/android/titanium_prep.win32.exe
  support/android/titanium_prep.win64.exe
  support/ti.cloak.zip
  tests/Resources/ti.network.httpclient.addontest.js
  tests/Resources/ti.ui.webview.addontest.js
Labels: android, cli 📟, improvement, in-qe-testing 🕵, no tests

#11058 fix(android): remove usage of getResourceAsStream()
  .eslintignore
  android/build/common.xml
  android/modules/ui/assets/Resources/ti.internal/webview/binding.js
  android/modules/ui/assets/Resources/ti.internal/webview/binding.min.js
  android/modules/ui/assets/Resources/ti.internal/webview/json2.js
  android/modules/ui/assets/Resources/ti.internal/webview/polling.js
  android/modules/ui/assets/Resources/ti.internal/webview/polling.min.js
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/tableview/TiBaseTableViewItem.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/tableview/TiTableViewRowProxyItem.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/webview/TiWebViewBinding.java
  android/titanium/res/drawable/background.png
  android/titanium/src/java/org/appcelerator/titanium/TiApplication.java
  android/titanium/src/java/org/appcelerator/titanium/res/drawable/btn_check_buttonless_on_144.png
  android/titanium/src/java/org/appcelerator/titanium/res/drawable/btn_check_buttonless_on_192.png
  android/titanium/src/java/org/appcelerator/titanium/res/drawable/btn_check_buttonless_on_36.png
  android/titanium/src/java/org/appcelerator/titanium/res/drawable/btn_check_buttonless_on_48.png
  android/titanium/src/java/org/appcelerator/titanium/res/drawable/btn_check_buttonless_on_72.png
  android/titanium/src/java/org/appcelerator/titanium/res/drawable/btn_check_buttonless_on_96.png
  android/titanium/src/java/org/appcelerator/titanium/res/drawable/btn_more_144.png
  android/titanium/src/java/org/appcelerator/titanium/res/drawable/btn_more_192.png
  android/titanium/src/java/org/appcelerator/titanium/res/drawable/btn_more_36.png
  android/titanium/src/java/org/appcelerator/titanium/res/drawable/btn_more_48.png
  android/titanium/src/java/org/appcelerator/titanium/res/drawable/btn_more_72.png
  android/titanium/src/java/org/appcelerator/titanium/res/drawable/btn_more_96.png
  android/titanium/src/java/org/appcelerator/titanium/res/drawable/btn_picker_normal.9.png
  android/titanium/src/java/org/appcelerator/titanium/res/drawable/btn_picker_pressed.9.png
  android/titanium/src/java/org/appcelerator/titanium/res/drawable/btn_picker_selected.9.png
  android/titanium/src/java/org/appcelerator/titanium/res/drawable/default_icon.png
  android/titanium/src/java/org/appcelerator/titanium/res/drawable/photoDefault.png
  android/titanium/src/java/org/appcelerator/titanium/util/TiFileHelper.java
Labels: android, improvement, in-qe-testing 🕵, no tests

#11150 perf(android): implement ability to pre-cache common js assets
  android/cli/commands/_build.js
  android/dev/TitaniumTest/assets/cache.json
  android/dev/TitaniumTest/src/com/titanium/test/TitaniumTestApplication.java
  android/runtime/common/src/java/org/appcelerator/kroll/util/KrollAssetCache.java
  android/runtime/common/src/java/org/appcelerator/kroll/util/KrollAssetHelper.java
  android/templates/build/App.java
  android/templates/build/AssetCryptImpl.java
Labels: android, improvement, no tests

#11288 fix(ios): setting last index of TabbedBar doesn't work
  iphone/Classes/TiUIButtonBar.m
Labels: bug 🐜, in-qe-testing 🕵, ios, no tests

#11286 fix(ios): wkwebview is stripping out = characters in cookies
  iphone/Classes/TiUIWebView.m
Labels: bug 🐜, in-qe-testing 🕵, ios, needs tests 🚨
