Repository tidev/titanium-sdk, pull requests merged in 2020-08, with the labels that each got.

#11863 test: increase timeout for userAgent test
  tests/Resources/ti.ui.webview.test.js
Labels: backport 9_1_X, backport 9_3_X, needs jira 🚨, test

#11864 [Backport 9_1_X] test: increase timeout for userAgent test
  tests/Resources/ti.ui.webview.test.js
Labels: needs jira 🚨

#11865 [Backport 9_3_X] test: increase timeout for userAgent test
  tests/Resources/ti.ui.webview.test.js
Labels: needs jira 🚨

#11869 [Backport 9_3_X] feat: add OS version major/minor integer constants
  android/modules/platform/src/java/ti/modules/titanium/platform/PlatformModule.java
  apidoc/Global/Global.yml
  apidoc/Titanium/Platform/Platform.yml
  common/Resources/ti.internal/extensions/globals.js
  common/Resources/ti.internal/extensions/index.js
  common/Resources/ti.internal/extensions/ti/ti.blob.js
  common/Resources/ti.internal/extensions/ti/ti.ui.js
  iphone/Classes/PlatformModule.h
  iphone/Classes/PlatformModule.m
  tests/Resources/intl.numberformat.test.js
  tests/Resources/ti.app.ios.test.js
  tests/Resources/ti.network.httpclient.test.js
  tests/Resources/ti.platform.test.js
  tests/Resources/ti.ui.ios.tableviewstyle.test.js
  tests/Resources/ti.ui.ios.test.js
  tests/Resources/ti.ui.test.js
Labels: android, docs 📔, ios, needs jira 🚨

#11844 fix(ios): exclude arm64 architecture from simulator build
  iphone/TitaniumKit/TitaniumKit/Scripts/build-universal-framework.sh
  iphone/cli/commands/_buildModule.js
  support/iphone/build_titaniumkit.sh
Labels: iOS 14, ios

#11876 [Backport 9_3_X] build(deps-dev): bump eslint-config-axway from 4.7.0 to 4.7.1
  package-lock.json
  package.json
Labels: needs jira 🚨

#11877 [Backport 9_3_X] build(deps-dev): bump eslint-plugin-mocha from 7.0.1 to 8.0.0
  package-lock.json
  package.json
Labels: needs jira 🚨

#11874 fix(android): DateTimeFormat mishandles some combinations of settings on Android 8
  android/modules/locale/src/java/ti/modules/titanium/locale/DateTimeFormatProxy.java
Labels: android, backport 9_1_X, backport 9_3_X, bug 🐜, in-qe-testing 🕵, no tests

#11866 chore(android)(9_3_X): use latest emulator and ndk
  Jenkinsfile
  build/lib/test/test.js
  tests/Resources/ti.app.test.js
  tests/Resources/ti.ui.window.test.js
  tests/plugins/mocha.test.support/hooks/hook.js
Labels: android, needs jira 🚨, no tests

#11850 chore(android)(9_3_X): compile with API Level 30
  android/app/build.gradle
  android/package.json
  android/titanium/build.gradle
  tests/Resources/ti.android.test.js
Labels: android, improvement, in-qe-testing 🕵, no tests

#11881 [Backport 9_3_X] build(deps-dev): bump rollup from 2.23.0 to 2.23.1
  package-lock.json
  package.json
Labels: needs jira 🚨

#11884 ci: update backport action
  .github/workflows/backport.yml
Labels: backport 9_1_X, backport 9_3_X, needs jira 🚨

#11346 feat: webpack support
  .eslintrc
  android/cli/commands/_build.js
  cli/hooks/webpack.js
  cli/lib/tasks/process-js-task.js
  cli/lib/webpack/appcd.js
  cli/lib/webpack/log-update.js
  cli/lib/webpack/reporter.js
  cli/lib/webpack/service.js
  iphone/cli/commands/_build.js
  package-lock.json
  package.json
Labels: backport 9_1_X, cli 📟, feature 🚀

#11887 [Backport 9_1_X] feat: webpack support
  .eslintrc
  android/cli/commands/_build.js
  cli/hooks/webpack.js
  cli/lib/tasks/process-js-task.js
  cli/lib/webpack/appcd.js
  cli/lib/webpack/log-update.js
  cli/lib/webpack/reporter.js
  cli/lib/webpack/service.js
  iphone/cli/commands/_build.js
  package-lock.json
  package.json
Labels: needs jira 🚨

#11862 fix(android)(9_1_X): draw border path correctly
  android/titanium/src/java/org/appcelerator/titanium/view/TiBorderWrapperView.java
Labels: android, backport 9_3_X, backport master, bug 🐜, in-qe-testing 🕵, no tests

#11889 [Backport master] fix(android)(9_1_X): draw border path correctly
  android/titanium/src/java/org/appcelerator/titanium/view/TiBorderWrapperView.java
Labels: android, needs jira 🚨, no tests

#11888 [Backport 9_3_X] fix(android)(9_1_X): draw border path correctly
  android/titanium/src/java/org/appcelerator/titanium/view/TiBorderWrapperView.java
Labels: android, needs jira 🚨, no tests

#11892 [Backport 9_3_X] build(deps): bump wrap-ansi from 6.2.0 to 7.0.0
  package-lock.json
  package.json
Labels: needs jira 🚨

#11893 [Backport 9_1_X] feat: webpack template for classic apps
  .gitignore
  android/templates/app/webpack-default/template/platform/android/README.md
  android/templates/app/webpack-default/template/platform/android/res/drawable-anydpi-v26/ic_launcher.xml
  android/templates/app/webpack-default/template/platform/android/res/drawable-anydpi-v26/ic_launcher_round.xml
  android/templates/app/webpack-default/template/platform/android/res/drawable-hdpi/ic_launcher.png
  android/templates/app/webpack-default/template/platform/android/res/drawable-hdpi/ic_launcher_foreground.png
  android/templates/app/webpack-default/template/platform/android/res/drawable-hdpi/ic_launcher_round.png
  android/templates/app/webpack-default/template/platform/android/res/drawable-mdpi/ic_launcher.png
  android/templates/app/webpack-default/template/platform/android/res/drawable-mdpi/ic_launcher_foreground.png
  android/templates/app/webpack-default/template/platform/android/res/drawable-mdpi/ic_launcher_round.png
  android/templates/app/webpack-default/template/platform/android/res/drawable-v24/ic_launcher_foreground.xml
  android/templates/app/webpack-default/template/platform/android/res/drawable-xhdpi/ic_launcher.png
  android/templates/app/webpack-default/template/platform/android/res/drawable-xhdpi/ic_launcher_foreground.png
  android/templates/app/webpack-default/template/platform/android/res/drawable-xhdpi/ic_launcher_round.png
  android/templates/app/webpack-default/template/platform/android/res/drawable-xxhdpi/ic_launcher.png
  android/templates/app/webpack-default/template/platform/android/res/drawable-xxhdpi/ic_launcher_foreground.png
  android/templates/app/webpack-default/template/platform/android/res/drawable-xxhdpi/ic_launcher_round.png
  android/templates/app/webpack-default/template/platform/android/res/drawable-xxxhdpi/ic_launcher.png
  android/templates/app/webpack-default/template/platform/android/res/drawable-xxxhdpi/ic_launcher_foreground.png
  android/templates/app/webpack-default/template/platform/android/res/drawable-xxxhdpi/ic_launcher_round.png
  android/templates/app/webpack-default/template/platform/android/res/drawable/ic_launcher_background.xml
  android/templates/app/webpack-default/template/platform/android/res/values/colors.xml
  android/templates/app/webpack-default/template/platform/android/res/values/ic_launcher_background.xml
  android/templates/app/webpack-default/template/platform/android/res/values/styles.xml
  android/templates/app/webpack-default/template/src/assets/android/default.9.png
  cli/lib/webpack-post-create.js
  iphone/templates/app/webpack-default/template/src/assets/ios/LaunchLogo.png
  templates/app/default/template/README
  templates/app/webpack-default/hooks/post-create.js
  templates/app/webpack-default/template/.editorconfig
  templates/app/webpack-default/template/.eslintrc.js
  templates/app/webpack-default/template/.gitignore
  templates/app/webpack-default/template/.vscode/extensions.json
  templates/app/webpack-default/template/DefaultIcon.png
  templates/app/webpack-default/template/LICENSE
  templates/app/webpack-default/template/README.md
  templates/app/webpack-default/template/babel.config.js
  templates/app/webpack-default/template/package.json
  templates/app/webpack-default/template/src/assets/fonts/FontAwesome5Brands-Regular.otf
  templates/app/webpack-default/template/src/assets/fonts/FontAwesome5Free-Regular.otf
  templates/app/webpack-default/template/src/assets/fonts/FontAwesome5Free-Solid.otf
  templates/app/webpack-default/template/src/assets/images/home.png
  templates/app/webpack-default/template/src/assets/images/home@2x.png
  templates/app/webpack-default/template/src/assets/images/home@3x.png
  templates/app/webpack-default/template/src/assets/images/profile.jpg
  templates/app/webpack-default/template/src/assets/images/user.png
  templates/app/webpack-default/template/src/assets/images/user@2x.png
  templates/app/webpack-default/template/src/assets/images/user@3x.png
  templates/app/webpack-default/template/src/home.js
  templates/app/webpack-default/template/src/main.js
  templates/app/webpack-default/template/src/profile.js
  templates/app/webpack-default/template/src/utils.js
  templates/app/webpack-default/template/tiapp.xml
Labels: needs jira 🚨

#11894 [Backport 9_3_X] feat: webpack template for classic apps
  .gitignore
  android/templates/app/webpack-default/template/platform/android/README.md
  android/templates/app/webpack-default/template/platform/android/res/drawable-anydpi-v26/ic_launcher.xml
  android/templates/app/webpack-default/template/platform/android/res/drawable-anydpi-v26/ic_launcher_round.xml
  android/templates/app/webpack-default/template/platform/android/res/drawable-hdpi/ic_launcher.png
  android/templates/app/webpack-default/template/platform/android/res/drawable-hdpi/ic_launcher_foreground.png
  android/templates/app/webpack-default/template/platform/android/res/drawable-hdpi/ic_launcher_round.png
  android/templates/app/webpack-default/template/platform/android/res/drawable-mdpi/ic_launcher.png
  android/templates/app/webpack-default/template/platform/android/res/drawable-mdpi/ic_launcher_foreground.png
  android/templates/app/webpack-default/template/platform/android/res/drawable-mdpi/ic_launcher_round.png
  android/templates/app/webpack-default/template/platform/android/res/drawable-v24/ic_launcher_foreground.xml
  android/templates/app/webpack-default/template/platform/android/res/drawable-xhdpi/ic_launcher.png
  android/templates/app/webpack-default/template/platform/android/res/drawable-xhdpi/ic_launcher_foreground.png
  android/templates/app/webpack-default/template/platform/android/res/drawable-xhdpi/ic_launcher_round.png
  android/templates/app/webpack-default/template/platform/android/res/drawable-xxhdpi/ic_launcher.png
  android/templates/app/webpack-default/template/platform/android/res/drawable-xxhdpi/ic_launcher_foreground.png
  android/templates/app/webpack-default/template/platform/android/res/drawable-xxhdpi/ic_launcher_round.png
  android/templates/app/webpack-default/template/platform/android/res/drawable-xxxhdpi/ic_launcher.png
  android/templates/app/webpack-default/template/platform/android/res/drawable-xxxhdpi/ic_launcher_foreground.png
  android/templates/app/webpack-default/template/platform/android/res/drawable-xxxhdpi/ic_launcher_round.png
  android/templates/app/webpack-default/template/platform/android/res/drawable/ic_launcher_background.xml
  android/templates/app/webpack-default/template/platform/android/res/values/colors.xml
  android/templates/app/webpack-default/template/platform/android/res/values/ic_launcher_background.xml
  android/templates/app/webpack-default/template/platform/android/res/values/styles.xml
  android/templates/app/webpack-default/template/src/assets/android/default.9.png
  cli/lib/webpack-post-create.js
  iphone/templates/app/webpack-default/template/src/assets/ios/LaunchLogo.png
  templates/app/default/template/README
  templates/app/webpack-default/hooks/post-create.js
  templates/app/webpack-default/template/.editorconfig
  templates/app/webpack-default/template/.eslintrc.js
  templates/app/webpack-default/template/.gitignore
  templates/app/webpack-default/template/.vscode/extensions.json
  templates/app/webpack-default/template/DefaultIcon.png
  templates/app/webpack-default/template/LICENSE
  templates/app/webpack-default/template/README.md
  templates/app/webpack-default/template/babel.config.js
  templates/app/webpack-default/template/package.json
  templates/app/webpack-default/template/src/assets/fonts/FontAwesome5Brands-Regular.otf
  templates/app/webpack-default/template/src/assets/fonts/FontAwesome5Free-Regular.otf
  templates/app/webpack-default/template/src/assets/fonts/FontAwesome5Free-Solid.otf
  templates/app/webpack-default/template/src/assets/images/home.png
  templates/app/webpack-default/template/src/assets/images/home@2x.png
  templates/app/webpack-default/template/src/assets/images/home@3x.png
  templates/app/webpack-default/template/src/assets/images/profile.jpg
  templates/app/webpack-default/template/src/assets/images/user.png
  templates/app/webpack-default/template/src/assets/images/user@2x.png
  templates/app/webpack-default/template/src/assets/images/user@3x.png
  templates/app/webpack-default/template/src/home.js
  templates/app/webpack-default/template/src/main.js
  templates/app/webpack-default/template/src/profile.js
  templates/app/webpack-default/template/src/utils.js
  templates/app/webpack-default/template/tiapp.xml
Labels: needs jira 🚨

#11902 chore(deps): update liveview to 1.5.3
  package-lock.json
  package.json
Labels: backport 9_1_X, backport 9_3_X, in-qe-testing 🕵, needs jira 🚨

#11903 fix: typo in install command for webpack plugin
  cli/hooks/webpack.js
Labels: backport 9_1_X, backport 9_3_X, cli 📟, needs jira 🚨

#11910 test: use threshold for image diff
  tests/Resources/utilities/assertions.js
Labels: backport master, needs jira 🚨, no tests

#11873 fix(ios): enable swift development in Titanium
  iphone/Classes/AppModule.m
  iphone/Classes/GeolocationModule.m
  iphone/Classes/PlatformModule.m
  iphone/Classes/TiUtils+Addons.h
  iphone/Classes/TiUtils+Addons.m
  iphone/Classes/TiUtils+Addons.swift
  iphone/TitaniumKit/TitaniumKit.xcodeproj/project.pbxproj
  iphone/TitaniumKit/TitaniumKit.xcodeproj/xcshareddata/xcschemes/Distribution.xcscheme
  iphone/cli/commands/_build.js
  iphone/iphone/Titanium-Bridging-Header.h
  iphone/iphone/Titanium.xcodeproj/project.pbxproj
  tests/Resources/ti.platform.test.js
Labels: backport 9_3_X, ios

#11919 style(ios): add swift linting
  .swiftlint.yml
  lint-staged.config.js
  package.json
Labels: backport 9_3_X, ios, needs jira 🚨, no tests

#11923 [Backport 9_3_X] style(ios): add swift linting
  .swiftlint.yml
  lint-staged.config.js
  package.json
Labels: needs jira 🚨

#11924 docs: fix extendSafeArea text
  apidoc/Titanium/UI/Window.yml
Labels: community 🔥, docs 📔, needs jira 🚨

#11926 ci(backport): change on to work off the pull_request_target
  .github/workflows/backport.yml
Labels: backport 9_1_X, backport 9_3_X, needs jira 🚨

#11928 buidl(ios): exclude arm64 architecture while building for simulator
  iphone/cli/commands/_build.js
Labels: backport 9_3_X, iOS 14, ios

#11934 [Backport 9_3_X] buidl(ios): exclude arm64 architecture while building for simulator
  iphone/cli/commands/_build.js
Labels: iOS 14, ios

#11932 [Backport 9_3_X] build(deps-dev): bump rollup from 2.26.3 to 2.26.4
  package-lock.json
  package.json
Labels: needs jira 🚨

#11933 [Backport 9_3_X] build(deps-dev): bump danger from 10.3.0 to 10.4.0
  package-lock.json
  package.json
Labels: needs jira 🚨

#11941 [Backport 9_3_X] build(deps-dev): bump mocha-jenkins-reporter from 0.4.4 to 0.4.5
  package-lock.json
  package.json
Labels: needs jira 🚨

#11943 [Backport 9_3_X] feat: add vscode config files to app templates #11870
  templates/app/angular-default/template/.vscode/settings.json
  templates/app/default/template/.vscode/extensions.json
  templates/app/default/template/.vscode/settings.json
Labels: needs jira 🚨

#11949 [Backport 9_3_X] build(deps-dev): bump mocha from 7.2.0 to 8.1.1
  package-lock.json
  package.json
Labels: needs jira 🚨

#11951 fix(ios): restored borderRadius setter
  iphone/TitaniumKit/TitaniumKit/Sources/API/TiUIView.m
  tests/Resources/ti.ui.view.test.js
Labels: backport 9_1_X, ios

#11952 [Backport 9_1_X] fix(ios): restored borderRadius setter
  iphone/TitaniumKit/TitaniumKit/Sources/API/TiUIView.m
  tests/Resources/ti.ui.view.test.js
Labels: ios, needs jira 🚨

#11935 fix(android): native modules should use min sdk for dependency
  android/cli/commands/_buildModule.js
  android/templates/module/generated/build.gradle
Labels: android, backport 9_1_X, backport 9_3_X, bug 🐜, in-qe-testing 🕵, no tests

#11953 [Backport 9_1_X] fix(android): native modules should use min sdk for dependency
  android/cli/commands/_buildModule.js
  android/templates/module/generated/build.gradle
Labels: needs jira 🚨

#11954 [Backport 9_3_X] fix(android): native modules should use min sdk for dependency
  android/cli/commands/_buildModule.js
  android/templates/module/generated/build.gradle
Labels: needs jira 🚨

#11959 [Backport 9_3_X] build(deps-dev): bump cz-conventional-changelog from 3.2.0 to 3.2.1
  package-lock.json
  package.json
Labels: dependencies, needs jira 🚨

#11960 [Backport 9_3_X] build(deps-dev): bump lint-staged from 10.2.11 to 10.2.12
  package-lock.json
  package.json
Labels: dependencies, needs jira 🚨

#11961 [Backport 9_3_X] build(deps-dev): bump commitizen from 4.1.5 to 4.2.0
  package-lock.json
  package.json
Labels: dependencies, needs jira 🚨

#11938 fix(android): allow node to clear event loop
  android/cli/commands/_build.js
Labels: android, backport 9_3_X, bug 🐜, in-qe-testing 🕵, no tests

#11825 feat(ios): expose new APIs to customize paging control
  apidoc/Titanium/UI/ScrollableView.yml
  iphone/Classes/TiUIScrollableView.h
  iphone/Classes/TiUIScrollableView.m
  iphone/Classes/TiUIScrollableViewProxy.m
  iphone/TitaniumKit/TitaniumKit/Sources/API/TiBlob.m
  tests/Resources/ti.ui.scrollableview.test.js
Labels: backport 9_3_X, docs 📔, feature 🚀, iOS 14, in-qe-testing 🕵, ios

#11975 [Backport 9_3_X] fix(android): allow node to clear event loop
  android/cli/commands/_build.js
Labels: android, bug 🐜, in-qe-testing 🕵, needs jira 🚨, no tests

#11973 [Backport 9_3_X] build(deps-dev): bump rollup from 2.26.5 to 2.26.6
  package-lock.json
  package.json
Labels: dependencies, needs jira 🚨

#11974 [Backport 9_3_X] build(deps-dev): bump cz-conventional-changelog from 3.2.1 to 3.3.0
  package-lock.json
  package.json
Labels: dependencies, needs jira 🚨

#11980 docs: add missing method in scollableview example
  apidoc/Titanium/UI/ScrollableView.yml
Labels: backport 9_3_X, community 🔥, docs 📔, needs jira 🚨

#11981 [Backport 9_3_X] docs: add missing method in scollableview example
  apidoc/Titanium/UI/ScrollableView.yml
Labels: community 🔥, docs 📔, needs jira 🚨

#11896 chore(ios): added new error constant and updated doc for local network privacy
  apidoc/Titanium/Network/BonjourBrowser.yml
  apidoc/Titanium/Network/BonjourService.yml
  iphone/Classes/TiNetworkBonjourServiceProxy.m
Labels: backport 9_3_X, docs 📔, iOS 14, in-qe-testing 🕵, ios, no tests

#11897 feat(iOS): support new APIs timeoutForResource and waitsForConnectivity
  apidoc/Titanium/Network/HTTPClient.yml
  iphone/Classes/TiNetworkHTTPClientProxy.m
  iphone/TitaniumKit/TitaniumKit/Libraries/APSHTTPClient/APSHTTPRequest.h
  iphone/TitaniumKit/TitaniumKit/Libraries/APSHTTPClient/libAPSHTTPClient.a
  tests/Resources/ti.network.httpclient.test.js
Labels: backport 9_3_X, docs 📔, iOS 14, in-qe-testing 🕵, ios

#11968 fix(ios): only include presentationControllerDidDismiss when photogallery is used
  iphone/Classes/MediaModule.m
Labels: backport 9_1_X, backport 9_3_X, bug 🐜, ios, needs tests 🚨

#11982 [Backport 9_3_X] chore(ios): added new error constant and updated doc for local network privacy
  apidoc/Titanium/Network/BonjourBrowser.yml
  apidoc/Titanium/Network/BonjourService.yml
  iphone/Classes/TiNetworkBonjourServiceProxy.m
Labels: docs 📔, iOS 14, in-qe-testing 🕵, ios, needs jira 🚨, no tests

#11983 [Backport 9_3_X] feat(iOS): support new APIs timeoutForResource and waitsForConnectivity
  apidoc/Titanium/Network/HTTPClient.yml
  iphone/Classes/TiNetworkHTTPClientProxy.m
  iphone/TitaniumKit/TitaniumKit/Libraries/APSHTTPClient/APSHTTPRequest.h
  iphone/TitaniumKit/TitaniumKit/Libraries/APSHTTPClient/libAPSHTTPClient.a
  tests/Resources/ti.network.httpclient.test.js
Labels: docs 📔, iOS 14, in-qe-testing 🕵, ios, needs jira 🚨

#11991 [Backport 9_3_X] build(deps-dev): bump mocha from 8.1.2 to 8.1.3
  package-lock.json
  package.json
Labels: dependencies, needs jira 🚨

#11976 fix(ios): update liveview for ios 14 compatibility
  package-lock.json
  package.json
Labels: backport 9_3_X, iOS 14, in-qe-testing 🕵, ios

#11992 [Backport 9_3_X] fix(ios): update liveview for ios 14 compatibility
  package-lock.json
  package.json
Labels: iOS 14, in-qe-testing 🕵, ios
