Repository tidev/titanium-sdk, pull requests merged in 2020-09, with the labels that each got.

#11995 [Backport 9_3_X] build(deps-dev): bump eslint from 7.7.0 to 7.8.0
  package-lock.json
  package.json
Labels: dependencies, needs jira 🚨

#11936 feat: add "uprightWidth" and "uprightHeight" properties to Ti.Blob
  android/titanium/src/java/org/appcelerator/titanium/TiBlob.java
  apidoc/Titanium/Blob.yml
  iphone/TitaniumKit/TitaniumKit/Sources/API/TiBlob.h
  iphone/TitaniumKit/TitaniumKit/Sources/API/TiBlob.m
  tests/Resources/ExifFlipHorizontal.jpg
  tests/Resources/ExifFlipVertical.jpg
  tests/Resources/ExifRotate180.jpg
  tests/Resources/ExifRotate270.jpg
  tests/Resources/ExifRotate90.jpg
  tests/Resources/ExifTranspose.jpg
  tests/Resources/ExifTransverse.jpg
  tests/Resources/ti.blob.test.js
Labels: android, backport 9_3_X, docs 📔, feature 🚀, in-qe-testing 🕵, ios

#11834 feat(ios): expose new iOS 14 APIs in Ti.UI.WebView
  apidoc/Titanium/UI/WebView.yml
  iphone/Classes/TiUIWebView.m
  iphone/Classes/TiUIWebViewProxy.m
  tests/Resources/ti.ui.webview.test.js
Labels: backport 9_3_X, docs 📔, feature 🚀, iOS 14, in-qe-testing 🕵, ios

#11999 [Backport 9_3_X] feat: add "uprightWidth" and "uprightHeight" properties to Ti.Blob
  android/titanium/src/java/org/appcelerator/titanium/TiBlob.java
  apidoc/Titanium/Blob.yml
  iphone/TitaniumKit/TitaniumKit/Sources/API/TiBlob.h
  iphone/TitaniumKit/TitaniumKit/Sources/API/TiBlob.m
  tests/Resources/ExifFlipHorizontal.jpg
  tests/Resources/ExifFlipVertical.jpg
  tests/Resources/ExifRotate180.jpg
  tests/Resources/ExifRotate270.jpg
  tests/Resources/ExifRotate90.jpg
  tests/Resources/ExifTranspose.jpg
  tests/Resources/ExifTransverse.jpg
  tests/Resources/ti.blob.test.js
Labels: android, docs 📔, feature 🚀, in-qe-testing 🕵, ios, needs jira 🚨

#12001 [Backport 9_3_X] feat(ios): support new date picker styles
  apidoc/Titanium/UI/Picker.yml
  apidoc/Titanium/UI/iOS/iOS.yml
  iphone/Classes/TiUIPicker.m
  iphone/Classes/TiUIiOSProxy.m
Labels: community 🔥, docs 📔, iOS 14, in-qe-testing 🕵, ios, needs jira 🚨, needs tests 🚨

#12003 [Backport 9_3_X] build(deps): [security] bump bl from 4.0.2 to 4.0.3
  package-lock.json
Labels: dependencies, security

#12004 [Backport 9_3_X] build(deps-dev): bump eslint from 7.8.0 to 7.8.1
  package-lock.json
  package.json
Labels: needs jira 🚨

#12009 [Backport 9_3_X] build(deps-dev): bump lint-staged from 10.2.13 to 10.3.0
  package-lock.json
  package.json
Labels: dependencies

#12008 [Backport 9_3_X] build(deps-dev): bump eslint-config-axway from 4.7.2 to 4.7.3
  package-lock.json
  package.json
Labels: dependencies

#12002 [TIMOB-28108] Allow tintColor to accept a semantic color
  iphone/Classes/TiUIRefreshControlProxy.m
Labels: backport 9_3_X, bug 🐜, in-qe-testing 🕵, ios, no tests

#11969 fix(ios): use arc to create corner radius instead of qudratic curve
  iphone/TitaniumKit/TitaniumKit/Sources/API/TiUIView.m
  tests/Resources/android/snapshots/borderRadius30px.png
  tests/Resources/ios/snapshots/borderRadius12px_12_12dp_12_2x.png
  tests/Resources/ios/snapshots/borderRadius12px_12_12dp_12_3x.png
  tests/Resources/ios/snapshots/borderRadius12px_12_2x.png
  tests/Resources/ios/snapshots/borderRadius12px_12_3x.png
  tests/Resources/ios/snapshots/borderRadius30px.png
  tests/Resources/ti.ui.view.test.js
Labels: backport 9_1_X, backport 9_3_X, bug 🐜, in-qe-testing 🕵, ios

#12012 [Backport 9_3_X] fix(ios): use arc to create corner radius instead of qudratic curve
  iphone/TitaniumKit/TitaniumKit/Sources/API/TiUIView.m
  tests/Resources/android/snapshots/borderRadius30px.png
  tests/Resources/ios/snapshots/borderRadius12px_12_12dp_12_2x.png
  tests/Resources/ios/snapshots/borderRadius12px_12_12dp_12_3x.png
  tests/Resources/ios/snapshots/borderRadius12px_12_2x.png
  tests/Resources/ios/snapshots/borderRadius12px_12_3x.png
  tests/Resources/ios/snapshots/borderRadius30px.png
  tests/Resources/ti.ui.view.test.js
Labels: bug 🐜, in-qe-testing 🕵, ios, needs jira 🚨

#12011 [Backport 9_1_X] fix(ios): use arc to create corner radius instead of qudratic curve
  iphone/TitaniumKit/TitaniumKit/Sources/API/TiUIView.m
  tests/Resources/android/snapshots/borderRadius30px.png
  tests/Resources/ios/snapshots/borderRadius12px_12_12dp_12_2x.png
  tests/Resources/ios/snapshots/borderRadius12px_12_12dp_12_3x.png
  tests/Resources/ios/snapshots/borderRadius12px_12_2x.png
  tests/Resources/ios/snapshots/borderRadius12px_12_3x.png
  tests/Resources/ios/snapshots/borderRadius30px.png
  tests/Resources/ti.ui.view.test.js
Labels: bug 🐜, in-qe-testing 🕵, ios, needs jira 🚨

#12014 ci: update to latest backport action
  .github/workflows/backport.yml
Labels: backport 9_1_X, backport 9_3_X, needs jira 🚨

#12016 [Backport 9_3_X] build(deps-dev): bump rollup from 2.26.9 to 2.26.10
  package-lock.json
  package.json
Labels: needs jira 🚨

#12018 [Backport 9_3_X] build(deps-dev): bump husky from 4.2.5 to 4.3.0
  package-lock.json
  package.json
Labels: dependencies

#12021 [Backport 9_3_X] build(deps-dev): bump rollup from 2.26.10 to 2.26.11
  package-lock.json
  package.json
Labels: dependencies

#12020 fix(ios): guard new picker types
  iphone/Classes/TiUIPicker.m
  iphone/Classes/TiUIiOSProxy.m
  iphone/iphone/Titanium_Prefix.pch
Labels: backport 9_3_X, bug 🐜, ios, needs tests 🚨

#12024 [Backport 9_3_X] fix(ios): guard new picker types
  iphone/Classes/TiUIPicker.m
  iphone/Classes/TiUIiOSProxy.m
  iphone/iphone/Titanium_Prefix.pch
Labels: bug 🐜, ios, needs tests 🚨

#12028 fix(ios): do not update properties if transition animation
  iphone/TitaniumKit/TitaniumKit/Sources/API/TiAnimation.m
  tests/Resources/ti.ui.view.test.js
Labels: backport 9_1_X, backport 9_3_X, bug 🐜, in-qe-testing 🕵, ios

#12030 [Backport 9_1_X] fix(ios): do not update properties if transition animation
  iphone/TitaniumKit/TitaniumKit/Sources/API/TiAnimation.m
  tests/Resources/ti.ui.view.test.js
Labels: bug 🐜, in-qe-testing 🕵, ios, needs jira 🚨

#12031 [Backport 9_3_X] fix(ios): do not update properties if transition animation
  iphone/TitaniumKit/TitaniumKit/Sources/API/TiAnimation.m
  tests/Resources/ti.ui.view.test.js
Labels: bug 🐜, in-qe-testing 🕵, ios, needs jira 🚨

#11920 build(iOS): fix to add resources and sources file in widget extension
  iphone/cli/commands/_build.js
Labels: backport 9_3_X, bug 🐜, iOS 14, in-qe-testing 🕵, ios, no tests

#12032 [Backport 9_3_X] build(iOS): fix to add resources and sources file in widget extension
  iphone/cli/commands/_build.js
Labels: bug 🐜, iOS 14, in-qe-testing 🕵, ios, needs jira 🚨, no tests

#12034 fix(ios): avoid provisioning profile issues when targeting iPhone device
  iphone/iphone/Titanium.xcodeproj/project.pbxproj
Labels: needs jira 🚨

#12035 docs: use actual constants instead of wildcard
  apidoc/Titanium/Geolocation/Geolocation.yml
Labels: backport 9_3_X, docs 📔, in-qe-testing 🕵, no tests

#12040 [Backport 9_3_X] build(deps): bump archiver from 5.0.0 to 5.0.1
  package-lock.json
  package.json
Labels: dependencies, needs jira 🚨

#12037 fix(ios): rely on event flush interval
  iphone/TitaniumKit/TitaniumKit/Sources/API/TiExceptionHandler.m
Labels: backport 9_1_X, backport 9_3_X, in-qe-testing 🕵, ios, no tests

#12041 [Backport 9_1_X] fix(ios): rely on event flush interval
  iphone/TitaniumKit/TitaniumKit/Sources/API/TiExceptionHandler.m
Labels: in-qe-testing 🕵, ios, needs jira 🚨, no tests

#12042 [Backport 9_3_X] fix(ios): rely on event flush interval
  iphone/TitaniumKit/TitaniumKit/Sources/API/TiExceptionHandler.m
Labels: in-qe-testing 🕵, ios, needs jira 🚨, no tests

#11867 feat(ios): allow multiple photo selection
  apidoc/Titanium/Media/Media.yml
  iphone/Classes/MediaModule.h
  iphone/Classes/MediaModule.m
Labels: backport 9_3_X, docs 📔, iOS 14, in-qe-testing 🕵, ios, no tests

#12054 [Backport 9_3_X] build(deps-dev): bump eslint from 7.8.1 to 7.9.0
  package-lock.json
  package.json
Labels: dependencies, needs jira 🚨

#12056 [Backport 9_3_X] build(deps-dev): bump @commitlint/cli from 9.1.2 to 11.0.0
  package-lock.json
  package.json
Labels: dependencies, needs jira 🚨

#12057 [Backport 9_3_X] build(deps): bump moment from 2.27.0 to 2.28.0
  package-lock.json
  package.json
Labels: dependencies, needs jira 🚨

#12044 [Backport 9_3_X] fix: add version to new "datePickerStyle" property
  apidoc/Titanium/UI/Picker.yml
Labels: docs 📔, needs jira 🚨

#12055 [Backport 9_3_X] build(deps-dev): bump titanium from 5.2.2 to 5.2.3
  package-lock.json
  package.json
Labels: needs jira 🚨

#12059 [Backport 9_3_X] build(deps): bump archiver from 5.0.1 to 5.0.2
  package-lock.json
  package.json
Labels: dependencies, needs jira 🚨

#12060 [Backport 9_3_X] build(deps-dev): bump @commitlint/config-conventional from 9.1.2 to 11.0.0
  package-lock.json
  package.json
Labels: dependencies, needs jira 🚨

#12058 build(ios): fallback to xcode 11 dir name for ios xcframework if we can't find xcode 12 variant
  build/lib/ios.js
  iphone/cli/commands/_buildModule.js
Labels: backport 9_3_X, bug 🐜, cli 📟, in-qe-testing 🕵, ios, needs jira 🚨

#12064 [Backport 9_3_X] build(ios): fallback to xcode 11 dir name for ios xcframework if we can't find xcode 12 variant
  build/lib/ios.js
  iphone/cli/commands/_buildModule.js
Labels: bug 🐜, cli 📟, in-qe-testing 🕵, ios, needs jira 🚨

#12065 chore(deps): upgrade ti.applesignin to 2.0.0
  support/module/packaged/modules.json
Labels: backport 9_2_X, backport 9_3_X, dependencies, feature 🚀, in-qe-testing 🕵, ios, no tests

#12071 [Backport 9_2_X] chore(deps): upgrade ti.applesignin to 2.0.0
  support/module/packaged/modules.json
Labels: dependencies, feature 🚀, in-qe-testing 🕵, ios, needs jira 🚨, no tests

#12072 [Backport 9_3_X] chore(deps): upgrade ti.applesignin to 2.0.0
  support/module/packaged/modules.json
Labels: dependencies, feature 🚀, in-qe-testing 🕵, ios, needs jira 🚨, no tests

#12069 Update modules
  support/module/packaged/modules.json
Labels: backport 9_2_X, backport 9_3_X, ios, needs jira 🚨, no tests

#12076 [Backport 9_2_X] Update modules
  support/module/packaged/modules.json
Labels: ios, needs jira 🚨, no tests

#12077 [Backport 9_3_X] Update modules
  support/module/packaged/modules.json
Labels: ios, needs jira 🚨, no tests

#12045 fix(ios): remove SDK guards for peek and pop
  iphone/Classes/TiUIiOSPreviewContextProxy.m
  iphone/TitaniumKit/TitaniumKit/Sources/API/TiViewProxy.m
Labels: backport 9_2_X, backport 9_3_X, community 🔥, in-qe-testing 🕵, ios, no tests

#12082 [Backport 9_2_X] fix(ios): remove SDK guards for peek and pop
  iphone/Classes/TiUIiOSPreviewContextProxy.m
  iphone/TitaniumKit/TitaniumKit/Sources/API/TiViewProxy.m
Labels: community 🔥, in-qe-testing 🕵, ios, no tests

#12080 [Backport 9_2_X] build(deps-dev): bump titanium from 5.2.3 to 5.2.4
  package-lock.json
  package.json
Labels: dependencies

#12086 [Backport 9_2_X] build(deps): bump node-appc from 1.1.0 to 1.1.1
  package-lock.json
  package.json
Labels: dependencies

#12087 [Backport 9_2_X] build(deps-dev): bump titanium from 5.2.4 to 5.2.5
  package-lock.json
  package.json
Labels: dependencies

#12090 fix(ios): use TITANIUM_SDK variable to point at xcframework path in xcode project
  iphone/templates/module/objc/template/ios/{{ModuleName}}.xcodeproj/project.pbxproj.ejs
  iphone/templates/module/swift/template/ios/{{ModuleName}}.xcodeproj/project.pbxproj.ejs
Labels: backport 9_2_X, improvement, in-qe-testing 🕵, ios, needs jira 🚨, no tests

#12098 [Backport 9_2_X] fix(ios): use TITANIUM_SDK variable to point at xcframework path in xcode project
  iphone/templates/module/objc/template/ios/{{ModuleName}}.xcodeproj/project.pbxproj.ejs
  iphone/templates/module/swift/template/ios/{{ModuleName}}.xcodeproj/project.pbxproj.ejs
Labels: improvement, in-qe-testing 🕵, ios, needs jira 🚨, no tests

#12091 fix(ios): when building module test project, unzip via spawn to avoid max buffer error
  iphone/cli/commands/_buildModule.js
Labels: backport 9_2_X, bug 🐜, cli 📟, in-qe-testing 🕵, ios, no tests

#12102 fix(ios): added missing left (“)
  iphone/templates/module/swift/template/ios/{{ModuleName}}.xcodeproj/project.pbxproj.ejs
Labels: backport 9_2_X, bug 🐜, cli 📟, ios, no tests

#12100 [Backport 9_2_X] fix(ios): when building module test project, unzip via spawn to avoid max buffer error
  iphone/cli/commands/_buildModule.js
Labels: bug 🐜, cli 📟, in-qe-testing 🕵, ios, needs jira 🚨, no tests

#12103 [Backport 9_2_X] fix(ios): added missing left (“)
  iphone/templates/module/swift/template/ios/{{ModuleName}}.xcodeproj/project.pbxproj.ejs
Labels: bug 🐜, cli 📟, ios, no tests

#12106 docs: adding drawerlayout alloy example
  apidoc/Titanium/UI/Android/DrawerLayout.yml
Labels: community 🔥, docs 📔

#12094 fix(ios): remove old tiverify.xcframework references from project
  iphone/cli/commands/_build.js
Labels: backport 9_2_X, bug 🐜, iOS 14, in-qe-testing 🕵, ios

#12110 [Backport 9_2_X] fix(ios): remove old tiverify.xcframework references from project
  iphone/cli/commands/_build.js
Labels: bug 🐜, iOS 14, in-qe-testing 🕵, ios, needs jira 🚨

#12093 fix(ios): ignore the mac build if it failed and exclude sim arm64 if thirdparty .framework is there
  iphone/cli/commands/_build.js
  iphone/cli/commands/_buildModule.js
  iphone/templates/module/default/template/ios/manifest.ejs
Labels: backport 9_2_X, bug 🐜, cli 📟, in-qe-testing 🕵, ios

#12115 [Backport 9_2_X] fix(ios): ignore the mac build if it failed and exclude sim arm64 if thirdparty .framework is there
  iphone/cli/commands/_build.js
  iphone/cli/commands/_buildModule.js
  iphone/templates/module/default/template/ios/manifest.ejs
Labels: bug 🐜, cli 📟, in-qe-testing 🕵, ios

#12116 chore(deps): update facebook module to 9.0.0 for ios, 10.0.0 for android
  support/module/packaged/modules.json
Labels: android, backport 9_2_X, feature 🚀, in-qe-testing 🕵, ios, no tests

#12117 [Backport 9_2_X] chore(deps): update facebook module to 9.0.0 for ios, 10.0.0 for android
  support/module/packaged/modules.json
Labels: android, feature 🚀, in-qe-testing 🕵, ios, no tests

#12107 feat(ios): support iOS 14+ App Clips
  iphone/cli/commands/_build.js
Labels: cli 📟, community 🔥, iOS 14, improvement, in-qe-testing 🕵, ios, no tests

#12112 chore(deps): update hyperloop to 6.0.0
  support/module/packaged/modules.json
Labels: backport 9_2_X, iOS 14, in-qe-testing 🕵

#12118 fix(ios): use xcodeTargetOS of 'iphoneos' for mac catalyst
  iphone/cli/commands/_build.js
Labels: backport 9_2_X, bug 🐜, cli 📟, in-qe-testing 🕵, ios, needs jira 🚨, no tests

#12121 [Backport 9_2_X] chore(deps): update hyperloop to 6.0.0
  support/module/packaged/modules.json
Labels: iOS 14, in-qe-testing 🕵

#12122 [Backport 9_2_X] fix(ios): use xcodeTargetOS of 'iphoneos' for mac catalyst
  iphone/cli/commands/_build.js
Labels: bug 🐜, cli 📟, in-qe-testing 🕵, ios, needs jira 🚨, no tests

#12123 docs(changelog): update changelog for 9.2.0 GA
  CHANGELOG.md
  releasing_the_sdk.md
Labels: backport 9_2_X, needs jira 🚨

#11899 impr(android): implement Ti.Network.HTTPClient responseHeaders property
  android/modules/network/src/java/ti/modules/titanium/network/HTTPClientProxy.java
  android/modules/network/src/java/ti/modules/titanium/network/TiHTTPClient.java
  tests/Resources/ti.network.httpclient.test.js
Labels: android, backport master, improvement, in-qe-testing 🕵, parity 👯‍♀️

#12124 [Backport 9_2_X] docs(changelog): update changelog for 9.2.0 GA
  CHANGELOG.md
  releasing_the_sdk.md
Labels: needs jira 🚨

#12125 [Backport master] impr(android): implement Ti.Network.HTTPClient responseHeaders property
  android/modules/network/src/java/ti/modules/titanium/network/HTTPClientProxy.java
  android/modules/network/src/java/ti/modules/titanium/network/TiHTTPClient.java
  tests/Resources/ti.network.httpclient.test.js
Labels: android, improvement, in-qe-testing 🕵, needs jira 🚨, parity 👯‍♀️

#12126 chore(deps): upgrade hyperloop to 6.0.1
  support/module/packaged/modules.json
Labels: backport master, bug 🐜, needs jira 🚨, no tests

#12129 fix(ios): guard PHPicker usage with openPhotoGallery
  iphone/Classes/MediaModule.m
Labels: backport 9_2_X, bug 🐜, ios, needs tests 🚨

#12131 [Backport 9_2_X] fix(ios): guard PHPicker usage with openPhotoGallery
  iphone/Classes/MediaModule.m
Labels: bug 🐜, ios, needs tests 🚨

#12130 docs(apidoc): fix backgroundSelectedColor type
  apidoc/Titanium/UI/View.yml
Labels: backport 9_2_X, docs 📔, needs jira 🚨

#12132 [Backport 9_2_X] docs(apidoc): fix backgroundSelectedColor type
  apidoc/Titanium/UI/View.yml
Labels: docs 📔, needs jira 🚨

#11970 refactor(android)(9_3_X): removed unneeded libraries
  android/titanium/lib/commons-logging-1.1.1.jar
  android/titanium/lib/nineoldandroids-appc-2.4.0.jar
  android/titanium/src/java/org/appcelerator/titanium/util/TiAnimationBuilder.java
  android/titanium/src/java/org/appcelerator/titanium/view/Ti2DMatrix.java
  android/titanium/src/java/org/appcelerator/titanium/view/TiBorderWrapperView.java
  android/titanium/src/java/org/appcelerator/titanium/view/TiUIView.java
Labels: android, backport master, improvement, in-qe-testing 🕵, no tests

#12133 fix(ios): disable default animation while setting backgroundImage
  iphone/TitaniumKit/TitaniumKit/Sources/API/TiUIView.m
Labels: backport 9_2_X, bug 🐜, in-qe-testing 🕵, ios, no tests

#12138 [Backport 9_2_X] fix(ios): disable default animation while setting backgroundImage
  iphone/TitaniumKit/TitaniumKit/Sources/API/TiUIView.m
Labels: bug 🐜, in-qe-testing 🕵, ios, no tests

#12104 fix(ios): avoid over release of list item proxies
  iphone/Classes/TiUIListView.m
  iphone/TitaniumKit/TitaniumKit/Sources/API/TiProxy.m
Labels: backport 9_2_X, bug 🐜, in-qe-testing 🕵, ios, no tests

#12140 [Backport 9_2_X] fix(ios): avoid over release of list item proxies
  iphone/Classes/TiUIListView.m
  iphone/TitaniumKit/TitaniumKit/Sources/API/TiProxy.m
Labels: bug 🐜, in-qe-testing 🕵, ios, needs jira 🚨, no tests

#12135 fix(ios): explicitly return null if source exists and hasn't changed
  iphone/cli/commands/_build.js
Labels: backport 9_2_X, bug 🐜, cli 📟, in-qe-testing 🕵, ios

#12141 [Backport 9_2_X] fix(ios): explicitly return null if source exists and hasn't changed
  iphone/cli/commands/_build.js
Labels: bug 🐜, cli 📟, in-qe-testing 🕵, ios, needs jira 🚨
