Repository tidev/titanium-sdk, pull requests merged in 2020-10, with the labels that each got.

#12139 fix(ios): format js errors in cli output
  iphone/TitaniumKit/TitaniumKit/Sources/API/KrollBridge.m
  iphone/TitaniumKit/TitaniumKit/Sources/API/TiExceptionHandler.h
  iphone/TitaniumKit/TitaniumKit/Sources/API/TiExceptionHandler.m
Labels: backport 9_2_X, bug 🐜, in-qe-testing 🕵, ios, no tests

#12142 fix(ios): check for thirdparty framework path
  iphone/cli/commands/_buildModule.js
Labels: backport 9_2_X, bug 🐜, in-qe-testing 🕵, no tests

#12147 [Backport 9_2_X] fix(ios): format js errors in cli output
  iphone/TitaniumKit/TitaniumKit/Sources/API/KrollBridge.m
  iphone/TitaniumKit/TitaniumKit/Sources/API/TiExceptionHandler.h
  iphone/TitaniumKit/TitaniumKit/Sources/API/TiExceptionHandler.m
Labels: bug 🐜, in-qe-testing 🕵, ios, no tests

#12148 [Backport 9_2_X] fix(ios): check for thirdparty framework path
  iphone/cli/commands/_buildModule.js
Labels: bug 🐜, in-qe-testing 🕵, no tests

#12146 fix(ios): ignore duplicate and unnecessary framework search paths
  iphone/cli/commands/_build.js
  iphone/cli/hooks/frameworks.js
  package-lock.json
  package.json
Labels: backport 9_2_X, bug 🐜, in-qe-testing 🕵, ios

#12149 [Backport 9_2_X] fix(ios): ignore duplicate and unnecessary framework search paths
  iphone/cli/commands/_build.js
  iphone/cli/hooks/frameworks.js
  package-lock.json
  package.json
Labels: bug 🐜, in-qe-testing 🕵, ios, needs jira 🚨

#12150 chore(ios): update ti.map for ios to 4.0.1
  support/module/packaged/modules.json
Labels: backport 9_2_X, bug 🐜, ios

#12151 [Backport 9_2_X] chore(ios): update ti.map for ios to 4.0.1
  support/module/packaged/modules.json
Labels: bug 🐜, ios

#12128 fix(ios): check for selector availability
  iphone/Classes/TiUITableViewRowProxy.m
  tests/Resources/ti.ui.tableview.test.js
Labels: backport 9_2_X, bug 🐜, customer, in-qe-testing 🕵, ios

#12152 [Backport 9_2_X] fix(ios): check for selector availability
  iphone/Classes/TiUITableViewRowProxy.m
  tests/Resources/ti.ui.tableview.test.js
Labels: bug 🐜, customer, in-qe-testing 🕵, ios

#12156 chore(deps): update hyperloop to 6.0.2
  support/module/packaged/modules.json
Labels: backport 9_2_X, dependencies, in-qe-testing 🕵, no tests

#12159 [Backport 9_2_X] chore(deps): update hyperloop to 6.0.2
  support/module/packaged/modules.json
Labels: dependencies, in-qe-testing 🕵, no tests

#12153 fix(ios): append TitaniumKit.xcframework if module is created with sdk < 9.2.0
  iphone/cli/commands/_buildModule.js
Labels: backport 9_2_X, bug 🐜, in-qe-testing 🕵, no tests

#12160 [Backport 9_2_X] fix(ios): append TitaniumKit.xcframework if module is created with sdk < 9.2.0
  iphone/cli/commands/_buildModule.js
Labels: bug 🐜, in-qe-testing 🕵, no tests

#12119 chore(android): update websocket lib for JS debugging
  android/runtime/v8/lib/java_websocket.LICENSE
  android/runtime/v8/lib/java_websocket.jar
  android/runtime/v8/src/java/org/appcelerator/kroll/runtime/v8/JSDebugger.java
  android/titanium/build.gradle
Labels: android, bug 🐜, improvement, in-qe-testing 🕵, no tests

#11841 fix(android)(9_3_X): build fails if "app_name" is defined in i18n "strings.xml" as of 9.0.0
  android/cli/commands/_build.js
Labels: android, backport master, bug 🐜, in-qe-testing 🕵, no tests

#11986 feat(android)(9_3_X): add camera/microphone foreground service constants
  android/modules/android/src/java/ti/modules/titanium/android/AndroidModule.java
  apidoc/Titanium/Android/Android.yml
Labels: android, backport master, docs 📔, improvement, in-qe-testing 🕵, no tests

#12169 [Backport master] fix(android)(9_3_X): build fails if "app_name" is defined in i18n "strings.xml" as of 9.0.0
  android/cli/commands/_build.js
Labels: android, bug 🐜, in-qe-testing 🕵, no tests

#12170 [Backport master] feat(android)(9_3_X): add camera/microphone foreground service constants
  android/modules/android/src/java/ti/modules/titanium/android/AndroidModule.java
  apidoc/Titanium/Android/Android.yml
Labels: android, docs 📔, improvement, in-qe-testing 🕵, no tests

#12105 refactor(android): webview permission/storage handling
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/webview/TiUIWebView.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/webview/TiWebChromeClient.java
  android/titanium/src/java/org/appcelerator/titanium/TiBaseActivity.java
Labels: android, improvement, in-qe-testing 🕵, no tests

#12164 build: after running macos tests, close the modal dialogs that get popped
  build/lib/test/close_modals.scpt
  build/lib/test/test.js
Labels: improvement, needs jira 🚨, no tests, test

#12166 fix(android): string reference equality in service code
  android/modules/android/src/java/ti/modules/titanium/android/TiJSService.java
Labels: android, bug 🐜, in-qe-testing 🕵, no tests

#12165 fix(android): openPhotoGallery() crashes when canceled as of 9.1.0
  android/modules/media/src/java/ti/modules/titanium/media/MediaModule.java
Labels: android, bug 🐜, in-qe-testing 🕵, no tests

#12154 feat(android): update kotlin language support to 1.4.0
  android/build.gradle
  android/templates/build/root.build.gradle
Labels: android, improvement, in-qe-testing 🕵, no tests

#12143 refactor(android): media/file APIs to use scoped storage
  android/modules/filesystem/src/java/ti/modules/titanium/filesystem/FilesystemModule.java
  android/modules/media/src/java/android/widget/TiVideoView8.java
  android/modules/media/src/java/ti/modules/titanium/media/MediaModule.java
  android/modules/media/src/java/ti/modules/titanium/media/TiCameraActivity.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/webview/TiWebChromeClient.java
  android/titanium/src/java/org/appcelerator/titanium/TiApplication.java
  android/titanium/src/java/org/appcelerator/titanium/TiFileProxy.java
  android/titanium/src/java/org/appcelerator/titanium/io/TiBaseFile.java
  android/titanium/src/java/org/appcelerator/titanium/io/TiContentFile.java
  android/titanium/src/java/org/appcelerator/titanium/io/TiFile.java
  android/titanium/src/java/org/appcelerator/titanium/io/TiFileFactory.java
  android/titanium/src/java/org/appcelerator/titanium/io/TiFileProvider.java
  android/titanium/src/java/org/appcelerator/titanium/io/TiResourceFile.java
  android/titanium/src/java/org/appcelerator/titanium/io/TitaniumBlob.java
  android/titanium/src/java/ti/modules/titanium/TitaniumModule.java
  apidoc/Titanium/Media/Media.yml
  build/lib/test/test.js
  tests/Resources/ti.filesystem.file.test.js
  tests/Resources/ti.media.test.js
Labels: android, bug 🐜, docs 📔, improvement, in-qe-testing 🕵

#12181 fix(template): update dependencies of angular template
  templates/app/angular-default/template/.eslintrc.js
  templates/app/angular-default/template/.eslintrc.json
  templates/app/angular-default/template/package.json
  templates/app/angular-default/template/src/main.aot.ts
  templates/app/angular-default/template/tsconfig.json
  templates/app/angular-default/template/typings/node/index.d.ts
Labels: backport 9_2_X, cli 📟, in-qe-testing 🕵

#12184 [Backport 9_2_X] fix(template): update dependencies of angular template
  templates/app/angular-default/template/.eslintrc.js
  templates/app/angular-default/template/.eslintrc.json
  templates/app/angular-default/template/package.json
  templates/app/angular-default/template/src/main.aot.ts
  templates/app/angular-default/template/tsconfig.json
  templates/app/angular-default/template/typings/node/index.d.ts
Labels: cli 📟, in-qe-testing 🕵

#12183 build: remove fake titanium-sdk node_module used by titanium CLI tisdk3fixes hook
  build/lib/packager.js
  build/titanium-sdk/lib/titanium.js
Labels: needs jira 🚨

#12186 chore(deps): update android to use v8 8.6.395.10
  android/package.json
Labels: android, improvement, in-qe-testing 🕵, needs jira 🚨, no tests

#12187 fix(ios): fix MediaModule compile error
  iphone/Classes/MediaModule.m
Labels: backport 9_2_X, bug 🐜, community 🔥, ios, no tests

#12192 [Backport 9_2_X] fix(ios): fix MediaModule compile error
  iphone/Classes/MediaModule.m
Labels: bug 🐜, community 🔥, ios, no tests

#12196 test: added new TableView/ListView unit tests
  tests/Resources/ti.media.videoplayer.test.js
  tests/Resources/ti.ui.listview.test.js
  tests/Resources/ti.ui.tableview.test.js
Labels: android, needs jira 🚨, test

#12193 fix(ios): TableView "sectionCount" property crash
  iphone/Classes/TiUITableView.m
  iphone/Classes/TiUITableViewProxy.h
  iphone/Classes/TiUITableViewProxy.m
Labels: backport 9_2_X, bug 🐜, in-qe-testing 🕵, ios, no tests

#12175 fix(android): TabGroup without badge crashes when using AppCompat theme as of 9.3.0
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/tabgroup/TiUIBottomNavigationTabGroup.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/tabgroup/TiUITabLayoutTabGroup.java
  android/titanium/src/java/org/appcelerator/titanium/util/TiUIHelper.java
Labels: android, bug 🐜, in-qe-testing 🕵, no tests

#12199 fix(angular): declare missing nodejs namespace for zone.js
  templates/app/angular-default/template/tsconfig.json
  templates/app/angular-default/template/typings/node/index.d.ts
Labels: backport 9_2_X, bug 🐜, in-qe-testing 🕵

#12204 [Backport 9_2_X] fix(angular): declare missing nodejs namespace for zone.js
  templates/app/angular-default/template/tsconfig.json
  templates/app/angular-default/template/typings/node/index.d.ts
Labels: bug 🐜, in-qe-testing 🕵

#12167 fix(ios): fix "dateTimeColor“ for iOS 14+
  apidoc/Titanium/UI/Picker.yml
  iphone/Classes/TiUIPicker.m
  tests/Resources/ti.ui.picker.test.js
Labels: backport 9_2_X, community 🔥, docs 📔, in-qe-testing 🕵, ios

#12172 fix(mac): generate missing macOS asset catalog icons
  iphone/cli/commands/_build.js
Labels: backport 9_2_X, cli 📟, community 🔥, improvement, in-qe-testing 🕵, ios, no tests

#12211 [Backport 9_2_X] fix(mac): generate missing macOS asset catalog icons
  iphone/cli/commands/_build.js
Labels: cli 📟, community 🔥, improvement, in-qe-testing 🕵, ios, needs jira 🚨, no tests

#12210 fix(ios): handle spaces in xcode path
  iphone/cli/hooks/package.js
Labels: backport 9_2_X, bug 🐜, cli 📟, in-qe-testing 🕵, ios

#12213 [Backport 9_2_X] fix(ios): handle spaces in xcode path
  iphone/cli/hooks/package.js
Labels: bug 🐜, cli 📟, in-qe-testing 🕵, ios, needs jira 🚨

#12194 fix(cli/clean): set prompt on project dir option
  cli/commands/clean.js
Labels: needs jira 🚨

#11985 refactor(android)(9_3_X): honor Android 11 "package visibility"
  android/app/src/main/AndroidManifest.xml
  android/cli/commands/_build.js
  android/cli/lib/android-manifest.js
  android/modules/platform/src/java/ti/modules/titanium/platform/PlatformModule.java
  android/modules/ui/src/java/ti/modules/titanium/ui/EmailDialogProxy.java
  android/templates/build/AndroidManifest.xml
  apidoc/Titanium/Platform/Platform.yml
Labels: android, backport master, docs 📔, improvement, in-qe-testing 🕵, no tests

#12212 fix(android): openPhotoGallery() crash selecting multiple files as of 9.1.0
  android/modules/media/src/java/ti/modules/titanium/media/MediaModule.java
  android/titanium/src/java/org/appcelerator/titanium/TiBlob.java
Labels: android, backport 9_2_X, bug 🐜, in-qe-testing 🕵, no tests

#12205 fix: always load aca module first on startup
  common/Resources/ti.internal/aca.js
  common/Resources/ti.main.js
Labels: backport 9_2_X, bug 🐜, in-qe-testing 🕵, no tests

#12219 [Backport 9_2_X] fix: always load aca module first on startup
  common/Resources/ti.internal/aca.js
  common/Resources/ti.main.js
Labels: bug 🐜, in-qe-testing 🕵, no tests

#12188 refactor(ios): remove deprecated framework usage
  iphone/Classes/ContactsModule.h
  iphone/Classes/ContactsModule.m
  iphone/Classes/TiContactsGroup.h
  iphone/Classes/TiContactsGroup.m
  iphone/Classes/TiContactsPerson.h
  iphone/Classes/TiContactsPerson.m
  iphone/iphone/Titanium.xcodeproj/project.pbxproj
  iphone/layout/layout/AppDelegate.m
Labels: backport 9_2_X, community 🔥, in-qe-testing 🕵, ios, no tests

#12221 [Backport 9_2_X] refactor(ios): remove deprecated framework usage
  iphone/Classes/ContactsModule.h
  iphone/Classes/ContactsModule.m
  iphone/Classes/TiContactsGroup.h
  iphone/Classes/TiContactsGroup.m
  iphone/Classes/TiContactsPerson.h
  iphone/Classes/TiContactsPerson.m
  iphone/iphone/Titanium.xcodeproj/project.pbxproj
  iphone/layout/layout/AppDelegate.m
Labels: community 🔥, in-qe-testing 🕵, ios, needs jira 🚨, no tests

#12220 chore(ios): update APSAnalytics
  iphone/TitaniumKit/TitaniumKit/Libraries/APSAnalytics/APSAnalytics.xcframework/Info.plist
  iphone/TitaniumKit/TitaniumKit/Libraries/APSAnalytics/APSAnalytics.xcframework/ios-arm64_armv7/Headers/APSAnalytics.h
  iphone/TitaniumKit/TitaniumKit/Libraries/APSAnalytics/APSAnalytics.xcframework/ios-arm64_armv7/libAPSAnalytics.a
  iphone/TitaniumKit/TitaniumKit/Libraries/APSAnalytics/APSAnalytics.xcframework/ios-arm64_i386_x86_64-simulator/Headers/APSAnalytics.h
  iphone/TitaniumKit/TitaniumKit/Libraries/APSAnalytics/APSAnalytics.xcframework/ios-arm64_i386_x86_64-simulator/libAPSAnalytics.a
  iphone/TitaniumKit/TitaniumKit/Libraries/APSAnalytics/APSAnalytics.xcframework/ios-arm64_x86_64-maccatalyst/Headers/APSAnalytics.h
  iphone/TitaniumKit/TitaniumKit/Libraries/APSAnalytics/APSAnalytics.xcframework/ios-arm64_x86_64-maccatalyst/libAPSAnalytics.a
Labels: backport 9_2_X, bug 🐜, in-qe-testing 🕵, ios, no tests

#12226 [Backport 9_2_X] chore(ios): update APSAnalytics
  iphone/TitaniumKit/TitaniumKit/Libraries/APSAnalytics/APSAnalytics.xcframework/Info.plist
  iphone/TitaniumKit/TitaniumKit/Libraries/APSAnalytics/APSAnalytics.xcframework/ios-arm64_armv7/Headers/APSAnalytics.h
  iphone/TitaniumKit/TitaniumKit/Libraries/APSAnalytics/APSAnalytics.xcframework/ios-arm64_armv7/libAPSAnalytics.a
  iphone/TitaniumKit/TitaniumKit/Libraries/APSAnalytics/APSAnalytics.xcframework/ios-arm64_i386_x86_64-simulator/Headers/APSAnalytics.h
  iphone/TitaniumKit/TitaniumKit/Libraries/APSAnalytics/APSAnalytics.xcframework/ios-arm64_i386_x86_64-simulator/libAPSAnalytics.a
  iphone/TitaniumKit/TitaniumKit/Libraries/APSAnalytics/APSAnalytics.xcframework/ios-arm64_x86_64-maccatalyst/Headers/APSAnalytics.h
  iphone/TitaniumKit/TitaniumKit/Libraries/APSAnalytics/APSAnalytics.xcframework/ios-arm64_x86_64-maccatalyst/libAPSAnalytics.a
Labels: bug 🐜, in-qe-testing 🕵, ios, needs jira 🚨, no tests

#12227 fix: silence aca load failure
  common/Resources/ti.internal/aca.js
Labels: backport 9_2_X, bug 🐜, in-qe-testing 🕵, no tests

#12229 [Backport 9_2_X] fix: silence aca load failure
  common/Resources/ti.internal/aca.js
Labels: bug 🐜, in-qe-testing 🕵, no tests

#12232 chore(android): delete unused "TiAuthentication" java code
  android/modules/network/src/java/ti/modules/titanium/network/TiAuthenticator.java
Labels: android, improvement, no tests
