Repository tidev/titanium-sdk, pull requests merged in 2020-07, with the labels that each got.

#11717 feat: add "isTrusted" property to Slider "change" event
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/TiUISlider.java
  apidoc/Titanium/UI/Slider.yml
  iphone/Classes/TiUISlider.m
  tests/Resources/ti.ui.slider.addontest.js
Labels: android, community 🔥, docs 📔, feature 🚀, in-qe-testing 🕵, ios

#11772 fix(ios): add fallback for countryCode in reverseGeocoder method
  iphone/Classes/GeolocationModule.m
Labels: community 🔥, in-qe-testing 🕵, ios, no tests

#11778 fix(ios): setting TextField.value to wrong type triggers change event
  iphone/Classes/TiUITextWidgetProxy.m
  tests/Resources/ti.ui.textfield.addontest.js
Labels: bug 🐜, in-qe-testing 🕵, ios

#11797 fix(ios): view in a tab window goes under tabs in a tabgroup on Ipad
  iphone/TitaniumKit/TitaniumKit/Sources/Modules/TiUIWindowProxy.m
Labels: bug 🐜, in-qe-testing 🕵, ios, no tests

#11754 docs: updated tls version support for iOS
  apidoc/Titanium/Network/HTTPClient.yml
Labels: docs 📔

#11782 fix(ios): event sessioncompleted does not get all specified values
  apidoc/Titanium/App/iOS/iOS.yml
  iphone/TitaniumKit/TitaniumKit/Sources/API/TiApp.m
Labels: bug 🐜, docs 📔, in-qe-testing 🕵, ios, no tests

#11680 feat(android): add getScaledTouchSlop() to ListView
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/listview/TiListView.java
  apidoc/Titanium/UI/ListView.yml
Labels: android, community 🔥, docs 📔, in-qe-testing 🕵, needs tests 🚨

#11759 feat(android): implement Shortcut proxy
  android/modules/ui/src/java/ti/modules/titanium/ui/ShortcutItemProxy.java
  android/modules/ui/src/java/ti/modules/titanium/ui/ShortcutModule.java
  android/modules/ui/src/java/ti/modules/titanium/ui/ShortcutProxy.java
  android/modules/ui/src/java/ti/modules/titanium/ui/UIModule.java
  android/titanium/src/java/org/appcelerator/titanium/TiRootActivity.java
  apidoc/Titanium/UI/Shortcut.yml
  apidoc/Titanium/UI/ShortcutItem.yml
  tests/Resources/ti.ui.shortcut.addontest.js
  tests/Resources/ti.ui.shortcutitem.test.js
Labels: android, docs 📔, feature 🚀, in-qe-testing 🕵

#11513 fix(ios): instead of ignoring call give error in case of nil url passed to Ti.Network.HTTPClient
  iphone/TitaniumKit/TitaniumKit/Libraries/APSAnalytics/libAPSAnalytics.a
  iphone/TitaniumKit/TitaniumKit/Libraries/APSHTTPClient/libAPSHTTPClient.a
  tests/Resources/ti.network.httpclient.addontest.js
Labels: bug 🐜, in-qe-testing 🕵, ios

#11747 fix(android): changing picker row color should update selected text
  android/modules/ui/src/java/ti/modules/titanium/ui/PickerRowProxy.java
Labels: android, bug 🐜, in-qe-testing 🕵, no tests

#11805 fix(ios): itemclick event its firing instead of a move event when ordering items in a list iOS 13+
  iphone/Classes/TiUIListView.m
Labels: bug 🐜, in-qe-testing 🕵, ios, no tests

#11812 docs(api): add note about unsupported progress indicator style
  apidoc/Titanium/UI/Android/ProgressIndicator.yml
Labels: docs 📔

#11683 feat: add Ti.Local.parseDecimal() method
  android/modules/locale/src/java/ti/modules/titanium/locale/LocaleModule.java
  apidoc/Global/String/String.yml
  apidoc/Titanium/Locale/Locale.yml
  iphone/Classes/LocaleModule.h
  iphone/Classes/LocaleModule.m
  tests/Resources/ti.locale.addontest.js
Labels: android, docs 📔, feature 🚀, in-qe-testing 🕵, ios, work in progress 🚧

#11809 fix(ios): setting TableView row layout to "horizontal" or "vertical" crashes
  iphone/TitaniumKit/TitaniumKit/Sources/API/TiViewProxy.m
  tests/Resources/ti.ui.tableview.addontest.js
Labels: bug 🐜, in-qe-testing 🕵, ios

#11662 refactor(android): keyboard handling for TextField and TextArea
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/TiUIEditText.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/TiUIText.java
  apidoc/Titanium/UI/UI.yml
Labels: android, bug 🐜, docs 📔, improvement, in-qe-testing 🕵, no tests, parity 👯‍♀️

#11824 fix(ios): Ti.Locale.parseDecimal() whitespace separator handling
  iphone/Classes/LocaleModule.m
Labels: bug 🐜, ios, no tests

#11823 fix(android): shortcut click event payload parity
  android/titanium/src/java/org/appcelerator/titanium/TiC.java
  android/titanium/src/java/org/appcelerator/titanium/TiRootActivity.java
Labels: android, bug 🐜, in-qe-testing 🕵, needs tests 🚨, parity 👯‍♀️

#11049 chore(android): detailed getter and setter deprecation warning
  android/kroll-apt/src/main/resources/org/appcelerator/kroll/annotations/generator/ProxyBindingV8.cpp.fm
  android/runtime/v8/src/native/Proxy.cpp
  android/runtime/v8/src/native/Proxy.h
  android/runtime/v8/src/native/V8Util.cpp
  android/runtime/v8/src/native/V8Util.h
Labels: android, cli 📟, improvement, in-qe-testing 🕵, no tests

#11833 docs: Intl API edits
  apidoc/Global/Intl/Collator.yml
  apidoc/Global/Intl/DateTimeFormat.yml
  apidoc/Global/Intl/Intl.yml
  apidoc/Global/Intl/NumberFormat.yml
Labels: android, docs 📔

#11495 fix(android): fix TabbedBar Click loop
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/TiUITabbedBar.java
Labels: android, backport 9_1_X, backport 9_3_X, community 🔥, in-qe-testing 🕵, needs tests 🚨

#11838 fix(android)(9_1_X): fix TabbedBar Click loop
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/TiUITabbedBar.java
Labels: android, backport 9_3_X, bug 🐜, no tests

#11847 feat(android): add passcode fallback to "ti.identity" module
  support/module/packaged/modules.json
Labels: android, backport 9_1_X, backport 9_3_X, improvement, no tests, parity 👯‍♀️

#11851 build: select the latest ga sdk after removing builds
  build/lib/utils.js
Labels: backport 9_1_X, backport 9_3_X, in-qe-testing 🕵, needs jira 🚨
