Repository tidev/titanium-sdk, pull requests merged in 2020-02, with the labels that each got.

#11446 fix(ios): behaviour of toString function of TiBlob fixed
  common/Resources/ti.internal/extensions/ti/ti.blob.js
Labels: bug 🐜, in-qe-testing 🕵, ios, no tests

#11460 chore(package): update ti.facebook ios module to 7.0.1
  support/module/packaged/modules.json
Labels: bug 🐜, ios, no tests

#11437 chore(ios): removed custom asset image hashing
  iphone/Classes/FilesystemModule.m
  iphone/Classes/TiUIApplicationShortcutsProxy.m
  iphone/Classes/TiUIImageView.m
  iphone/Classes/TiUIiOSApplicationShortcutsProxy.m
  iphone/TitaniumKit/TitaniumKit/Sources/API/ImageLoader.m
  iphone/cli/commands/_build.js
  tests/Resources/image folder/Logo.png
  tests/Resources/ti.ui.imageview.addontest.js
Labels: BREAKING CHANGES ⚠️, in-qe-testing 🕵, ios

#11458 fix(ios): statusbar ui issue fixed
  iphone/Classes/TiUIiOSProxy.m
Labels: bug 🐜, in-qe-testing 🕵, ios, no tests

#11462 fix(android): strip xmlns definitions from child elements in AndroidManifest.xml
  android/cli/lib/android-manifest.js
Labels: android, bug 🐜, in-qe-testing 🕵, no tests

#11463 fix(android): crash with old "ti.playservices" in 9.0.0
  android/titanium/lib/titanium-verify.jar
Labels: android, bug 🐜, in-qe-testing 🕵, no tests

#11465 feat: update hyperloop for 9.0.0 and gradle
  support/module/packaged/modules.json
Labels: android, bug 🐜, improvement, no tests

#11455 chore: extend get/set property method removal from 9.0.0 to 10.0.0
  android/kroll-apt/src/main/resources/org/appcelerator/kroll/annotations/generator/ProxyBindingV8.cpp.fm
  android/runtime/v8/src/native/Proxy.cpp
  iphone/TitaniumKit/TitaniumKit/Sources/API/ObjcProxy.h
  iphone/TitaniumKit/TitaniumKit/Sources/Kroll/KrollMethod.m
  iphone/TitaniumKit/TitaniumKit/Sources/Kroll/KrollObject.m
Labels: android, improvement, ios, no tests

#11448 chore: update ti.identity module
  support/module/packaged/modules.json
Labels: android, in-qe-testing 🕵, no tests

#11468 docs: add "repeatable" property on methods parameters
  apidoc/Global/Console/Console.yml
  apidoc/Titanium/Database/DB.yml
  apidoc/Titanium/Filesystem/Filesystem.yml
Labels: community 🔥, docs 📔, needs jira 🚨

#11469 fix(ios): skip compiled plist lookup for watchOS framework compatibility
  iphone/cli/commands/_build.js
Labels: community 🔥, in-qe-testing 🕵

#11466 feat(android): exclude x86/x86_64 in production builds by default
  android/cli/commands/_build.js
Labels: android, improvement, in-qe-testing 🕵, no tests

#11467 fix(android): firebase upload issue with "ti.map" and "ti.playservices"
  support/module/packaged/modules.json
Labels: android, bug 🐜, in-qe-testing 🕵, no tests

#10542 [TIMOB-26662] Android: TableViewRow bugs
  android/modules/ui/src/java/ti/modules/titanium/ui/TableViewRowProxy.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/tableview/TiTableViewRowProxyItem.java
  android/titanium/src/java/org/appcelerator/titanium/proxy/TiViewProxy.java
  tests/Resources/ti.ui.tableview.addontest.js
Labels: android, community 🔥, in-qe-testing 🕵

#11444 chore(android): update aps-analytics to aar
  android/titanium/lib/aps-analytics.jar
Labels: android, in-qe-testing 🕵, no tests

#11474 feat(android)(9_0_X): module builds should fail with aar in lib folder in 9.0.0
  android/templates/module/generated/build.gradle
Labels: BREAKING CHANGES ⚠️, android, improvement, no tests

#11445 chore(android): update ti.cloudpush module
  support/module/packaged/modules.json
Labels: android, in-qe-testing 🕵, no tests

#11472 feat(android): module builds should fail with aar in lib folder in 9.0.0
  android/templates/module/generated/build.gradle
Labels: BREAKING CHANGES ⚠️, android, improvement, in-qe-testing 🕵, no tests

#11478 chore(android)(9_0_X): update ti.cloudpush
  support/module/packaged/modules.json
Labels: android, no tests

#11476 (9_0_X) fix(ios): usernotificationsettings event missing success property
  iphone/Classes/TiAppiOSProxy.m
Labels: bug 🐜, in-qe-testing 🕵, ios, no tests

#11477 fix(ios): usernotificationsettings event has no success property
  iphone/Classes/TiAppiOSProxy.m
Labels: bug 🐜, in-qe-testing 🕵, ios, no tests

#11470 docs: remove a very outdated statement
  apidoc/Titanium/UI/TextField.yml
Labels: docs 📔, in-qe-testing 🕵

#11481 docs: update changelog
  CHANGELOG.md
Labels: needs jira 🚨

#11486 fix(android): hyperloop build fails if NDK not installed
  support/module/packaged/modules.json
Labels: android, bug 🐜, no tests

#11487 fix(android)(9_0_X): hyperloop build fails if NDK not installed
  support/module/packaged/modules.json
Labels: android, bug 🐜, no tests
