Repository tidev/titanium-sdk, pull requests merged in 2020-05, with the labels that each got.

#11678 chore(ios): deprecated statusbar constant
  apidoc/Titanium/UI/iOS/StatusBar.yml
  iphone/Classes/TiUIiOSStatusBarProxy.m
Labels: docs 📔, ios, needs tests 🚨

#11670 fix(iOS)(9_0_X): Ti.UI.Window.barColor cannot be changed after it was appeared
  iphone/TitaniumKit/TitaniumKit/Sources/Modules/TiUIWindowProxy.m
Labels: bug 🐜, in-qe-testing 🕵, ios, no tests

#11669 fix(ios): Ti.UI.Window.barColor cannot be changed after it was appeared
  iphone/TitaniumKit/TitaniumKit/Sources/Modules/TiUIWindowProxy.m
Labels: bug 🐜, in-qe-testing 🕵, ios, no tests

#11685 docs(api): loosen type on attributed string attribute value
  apidoc/Titanium/UI/Attribute.yml
Labels: docs 📔, needs jira 🚨

#11655 fix(ios): callback not invoked if missing options dictionary in Ti.Platform.openURL
  iphone/Classes/PlatformModule.h
  iphone/Classes/PlatformModule.m
  iphone/TitaniumKit/TitaniumKit.xcodeproj/project.pbxproj
  iphone/TitaniumKit/TitaniumKit/Sources/API/JSValue+Addons.h
  iphone/TitaniumKit/TitaniumKit/Sources/API/JSValue+Addons.m
  iphone/TitaniumKit/TitaniumKit/TitaniumKit.h
  tests/Resources/ti.platform.addontest.js
Labels: bug 🐜, in-qe-testing 🕵, ios

#11654 fix(ios): callback not invoked if missing options dictionary in Ti.Platform.openURL
  iphone/Classes/PlatformModule.h
  iphone/Classes/PlatformModule.m
  iphone/TitaniumKit/TitaniumKit.xcodeproj/project.pbxproj
  iphone/TitaniumKit/TitaniumKit/Sources/API/JSValue+Addons.h
  iphone/TitaniumKit/TitaniumKit/Sources/API/JSValue+Addons.m
  iphone/TitaniumKit/TitaniumKit/TitaniumKit.h
  tests/Resources/ti.platform.addontest.js
Labels: bug 🐜, in-qe-testing 🕵, ios

#11643 fix(ios): use jsvalue instead of jsmanagedvalue to handle events
  iphone/TitaniumKit/TitaniumKit/Sources/API/ObjcProxy.m
Labels: bug 🐜, in-qe-testing 🕵, ios, no tests

#11648 fix(ios): use jsvalue instead of jsmanagedvalue to handle events
  iphone/TitaniumKit/TitaniumKit/Sources/API/ObjcProxy.m
Labels: bug 🐜, in-qe-testing 🕵, ios, no tests

#11457 feat: cross-platform light/dark mode API
  android/cli/commands/_build.js
  android/modules/ui/src/java/ti/modules/titanium/ui/UIModule.java
  android/titanium/src/java/org/appcelerator/titanium/TiC.java
  apidoc/Titanium/App/iOS/iOS.yml
  apidoc/Titanium/UI/ActivityIndicator.yml
  apidoc/Titanium/UI/AlertDialog.yml
  apidoc/Titanium/UI/Animation.yml
  apidoc/Titanium/UI/Attribute.yml
  apidoc/Titanium/UI/Button.yml
  apidoc/Titanium/UI/ButtonBar.yml
  apidoc/Titanium/UI/Clipboard/Clipboard.yml
  apidoc/Titanium/UI/Color.yml
  apidoc/Titanium/UI/EmailDialog.yml
  apidoc/Titanium/UI/ImageView.yml
  apidoc/Titanium/UI/Label.yml
  apidoc/Titanium/UI/ListItem.yml
  apidoc/Titanium/UI/ListView.yml
  apidoc/Titanium/UI/MaskedImage.yml
  apidoc/Titanium/UI/Picker.yml
  apidoc/Titanium/UI/PickerRow.yml
  apidoc/Titanium/UI/ProgressBar.yml
  apidoc/Titanium/UI/RefreshControl.yml
  apidoc/Titanium/UI/ScrollableView.yml
  apidoc/Titanium/UI/SearchBar.yml
  apidoc/Titanium/UI/Slider.yml
  apidoc/Titanium/UI/Switch.yml
  apidoc/Titanium/UI/Tab.yml
  apidoc/Titanium/UI/TabGroup.yml
  apidoc/Titanium/UI/TableView.yml
  apidoc/Titanium/UI/TableViewRow.yml
  apidoc/Titanium/UI/TextArea.yml
  apidoc/Titanium/UI/TextField.yml
  apidoc/Titanium/UI/Toolbar.yml
  apidoc/Titanium/UI/UI.yml
  apidoc/Titanium/UI/View.yml
  apidoc/Titanium/UI/WebView.yml
  apidoc/Titanium/UI/Window.yml
  apidoc/Titanium/UI/iOS/Stepper.yml
  apidoc/Titanium/UI/iOS/Toolbar.yml
  apidoc/Titanium/UI/iOS/iOS.yml
  common/Resources/ti.internal/extensions/ti/ti.ui.js
  iphone/Classes/TiAppiOSProxy.m
  iphone/Classes/TiUIiOSProxy.m
  iphone/Classes/UIModule.h
  iphone/Classes/UIModule.m
  iphone/TitaniumKit/TitaniumKit/Sources/API/TiColor.m
  iphone/TitaniumKit/TitaniumKit/Sources/API/TiUtils.m
  iphone/iphone/Assets.xcassets/testColor.colorset/Contents.json
  tests/Resources/ti.ui.test.js
Labels: android, cli 📟, community 🔥, deprecation, docs 📔, feature 🚀, in-qe-testing 🕵, ios, parity 👯‍♀️

#11696 fix(android)(9_0_X): amend ImageView tintColor
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/TiImageView.java
Labels: android, bug 🐜, in-qe-testing 🕵, no tests

#11690 fix(android): amend ImageView tintColor
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/TiImageView.java
Labels: android, bug 🐜, in-qe-testing 🕵, no tests

#11684 fix(android): hide/show progress dialog back-to-back puts it in bad state as if 8.1.1
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/TiUIProgressIndicator.java
Labels: android, bug 🐜, in-qe-testing 🕵, no tests

#11668 feat(android): add callback support to Ti.Platform.openURL()
  android/modules/platform/src/java/ti/modules/titanium/platform/PlatformModule.java
  apidoc/Titanium/Platform/Platform.yml
Labels: android, docs 📔, improvement, in-qe-testing 🕵, no tests, parity 👯‍♀️

#11704 fix(ios): navigationbar flicker issue
  iphone/TitaniumKit/TitaniumKit/Sources/Modules/TiUIWindowProxy.m
Labels: bug 🐜, in-qe-testing 🕵, ios, no tests

#11705 chore(deps): update ioslib
  package-lock.json
  package.json
Labels: cli 📟, ios

#11703 fix(ios): navigationbar flicker issue
  iphone/TitaniumKit/TitaniumKit/Sources/Modules/TiUIWindowProxy.m
Labels: bug 🐜, in-qe-testing 🕵, ios, no tests

#11706 fix(android)(9_0_X): reuse old TableViewRow when applicable
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/tableview/TiTableView.java
Labels: android, bug 🐜, in-qe-testing 🕵, no tests

#11718 chore(ios): update libAPSHTTPClient
  iphone/TitaniumKit/TitaniumKit/Libraries/APSHTTPClient/libAPSHTTPClient.a
Labels: bug 🐜, in-qe-testing 🕵, ios

#11719 chore(ios): update libAPSHTTPClient
  iphone/TitaniumKit/TitaniumKit/Libraries/APSHTTPClient/libAPSHTTPClient.a
Labels: bug 🐜, in-qe-testing 🕵, ios

#11711 fix(ios) : build issue for XCode < 11
  apidoc/Titanium/UI/UI.yml
  iphone/Classes/UIModule.h
  iphone/Classes/UIModule.m
Labels: bug 🐜, docs 📔, ios, no tests

#11679 fix(android): Blob imageAsX() methods ignore EXIF orientation from non-file types
  android/titanium/src/java/org/appcelerator/titanium/TiBlob.java
Labels: android, bug 🐜, in-qe-testing 🕵, no tests

#11583 build(android): update v8 download logic
  android/package.json
  android/titanium/build.gradle
  android/titanium/libv8-services.js
  build/lib/packager.js
  build/lib/utils.js
  package-lock.json
  package.json
Labels: android, needs jira 🚨, work in progress 🚧

#11666 feat: update view properties after animation
  android/titanium/src/java/org/appcelerator/titanium/util/TiAnimationBuilder.java
  apidoc/Titanium/UI/Animation.yml
  apidoc/Titanium/UI/View.yml
  iphone/TitaniumKit/TitaniumKit/Sources/API/TiAnimation.h
  iphone/TitaniumKit/TitaniumKit/Sources/API/TiAnimation.m
  tests/Resources/ti.ui.label.addontest.js
  tests/Resources/ti.ui.view.test.js
Labels: android, docs 📔, feature 🚀, in-qe-testing 🕵, ios, parity 👯‍♀️

#11738 fix(android): update debugging prefix for chrome
  android/runtime/v8/src/java/org/appcelerator/kroll/runtime/v8/JSDebugger.java
Labels: android, needs tests 🚨
