Repository tidev/titanium-sdk, pull requests merged in 2021-10, with the labels that each got.

#13057 fix(ios): photogallery cancel callback not called if swiped down
  iphone/Classes/MediaModule.m
Labels: ios, community 🔥, bug 🐜, in-qe-testing 🕵, no tests

#13104 fix(ios): update ioslib
  package-lock.json
  package.json
Labels: ios, in-qe-testing 🕵, cli 📟

#13092 fix(ios): selectedBackgroundGradient deprecation shown when not using it
  iphone/Classes/TiUITableViewRowProxy.m
Labels: ios, community 🔥, in-qe-testing 🕵, no tests

#13137 fix(ios): redraw CGColor when changing trait collection
  iphone/TitaniumKit/TitaniumKit/Sources/API/TiUIView.m
Labels: ios, community 🔥, bug 🐜, in-qe-testing 🕵, no tests

#13149 refactor(android): add "homeAsUpIndicator" and "res/drawable" icon support to ActionBar
  android/titanium/src/java/org/appcelerator/titanium/proxy/ActionBarProxy.java
  apidoc/Titanium/Android/ActionBar.yml
  tests/Resources/app.js
  tests/Resources/ti.android.actionbar.test.js
Labels: android, feature 🚀, improvement, docs 📔
