Repository tidev/titanium-sdk, pull requests merged in 2021-09, with the labels that each got.

#13011 fix(ios): amend TiMediaVideoPlayer parent controller
  iphone/Classes/TiMediaVideoPlayer.m
Labels: ios, bug 🐜, in-qe-testing 🕵, no tests

#12986 chore: update ti.cloudpush
  support/module/packaged/modules.json
Labels: android, improvement, in-qe-testing 🕵, no tests

#13038 Improve reporting of failed test runs
  Jenkinsfile
  build/lib/test/index.js
  build/lib/test/test.js
  build/scons-test.js
  dangerfile.js
  package-lock.json
  package.json
Labels: needs jira 🚨, in-qe-testing 🕵

#13029 fix(ios): allow apps with non-arm64 modules to be built on Apple Silicon
  iphone/cli/commands/_build.js
Labels: ios, community 🔥, bug 🐜, in-qe-testing 🕵

#12967 feat: update "ti.map" module
  support/module/packaged/modules.json
Labels: ios, android, improvement, parity 👯‍♀️, no tests

#13058 test: remove axway and appcelerator domains in tests
  Jenkinsfile
  tests/Resources/ti.android.test.js
  tests/Resources/ti.network.httpclient.test.js
  tests/Resources/ti.network.socket.tcp.test.js
  tests/Resources/ti.platform.test.js
  tests/Resources/ti.ui.webview.test.js
Labels: needs jira 🚨

#12774 chore(android): optimize proxy constructor lookup
  android/kroll-apt/src/main/resources/org/appcelerator/kroll/annotations/generator/ProxyBindingV8.cpp.fm
  android/runtime/v8/src/native/ProxyFactory.cpp
  tests/Resources/core.runtime.test.js
Labels: android, improvement, in-qe-testing 🕵, no tests

#13067 fix(ios): navigation bar jumps at end of open animation on iOS15
  iphone/Classes/TiUINavigationWindowProxy.m
  iphone/Classes/TiUITabGroupProxy.m
Labels: ios, bug 🐜, no tests

#13072 fix(ios): cleanup search controller on close
  iphone/Classes/TiUITableView.m
  iphone/Classes/TiUITableViewProxy.m
Labels: ios, bug 🐜, in-qe-testing 🕵, no tests

#13078 refactor(android): optimize ImageView image download peformance
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/TiUIImageView.java
  android/titanium/src/java/org/appcelerator/titanium/TiApplication.java
  android/titanium/src/java/org/appcelerator/titanium/io/TiBaseFile.java
  android/titanium/src/java/org/appcelerator/titanium/util/TiBlobLruCache.java
  android/titanium/src/java/org/appcelerator/titanium/util/TiDownloadManager.java
  android/titanium/src/java/org/appcelerator/titanium/util/TiFileHelper.java
  android/titanium/src/java/org/appcelerator/titanium/util/TiImageCache.java
  android/titanium/src/java/org/appcelerator/titanium/util/TiImageInfo.java
  android/titanium/src/java/org/appcelerator/titanium/util/TiImageLruCache.java
  android/titanium/src/java/org/appcelerator/titanium/util/TiLoadImageListener.java
  android/titanium/src/java/org/appcelerator/titanium/util/TiLoadImageManager.java
  android/titanium/src/java/org/appcelerator/titanium/view/TiDrawableReference.java
  apidoc/Titanium/Android/BigPictureStyle.yml
  apidoc/Titanium/UI/ImageView.yml
  tests/Resources/ti.ui.imageview.test.js
Labels: android, improvement, docs 📔, in-qe-testing 🕵, no tests

#13077 fix(android): auto-scaling mode must stretch ImageView if both width/height set
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/TiImageView.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/TiUIImageView.java
Labels: android, bug 🐜, in-qe-testing 🕵, no tests
