Repository tidev/titanium-sdk, pull requests merged in 2021-06, with the labels that each got.

#12860 fix(android): correctly process bootstrap paths
  cli/lib/tasks/process-js-task.js
Labels: android, backport 10_0_X, bug 🐜, in-qe-testing 🕵, no tests

#12857 fix(android): improve marker detection
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/listview/ListViewAdapter.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/listview/ListViewHolder.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/listview/ListViewProxy.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/listview/TiListView.java
Labels: android, backport 10_0_X, bug 🐜, in-qe-testing 🕵, no tests

#12864 [Backport 10_0_X] fix(android): improve marker detection
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/listview/ListViewAdapter.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/listview/ListViewHolder.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/listview/ListViewProxy.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/listview/TiListView.java
Labels: android, bug 🐜, in-qe-testing 🕵, no tests

#12657 feat: add property "enableCopy" to TextField/TextArea
  android/modules/ui/src/java/ti/modules/titanium/ui/TextAreaProxy.java
  android/modules/ui/src/java/ti/modules/titanium/ui/TextFieldProxy.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/TiUIEditText.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/TiUIText.java
  android/titanium/src/java/org/appcelerator/titanium/TiC.java
  apidoc/Titanium/UI/TextArea.yml
  apidoc/Titanium/UI/TextField.yml
  iphone/Classes/TiUITextArea.h
  iphone/Classes/TiUITextArea.m
  iphone/Classes/TiUITextField.h
  iphone/Classes/TiUITextField.m
  iphone/Classes/TiUITextWidgetProxy.m
  tests/Resources/ti.ui.textarea.test.js
  tests/Resources/ti.ui.textfield.test.js
Labels: android, backport 10_0_X, docs 📔, feature 🚀, in-qe-testing 🕵, ios

#12781 fix(android): improve pre-loading optimization of ListView and TableView
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/listview/ListItemProxy.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/listview/ListViewHolder.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/listview/TiListView.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/tableview/TiTableView.java
  android/runtime/v8/src/java/org/appcelerator/kroll/runtime/v8/ReferenceTable.java
  android/titanium/src/java/org/appcelerator/titanium/util/TiDownloadManager.java
Labels: android, backport 10_0_X, bug 🐜, in-qe-testing 🕵, no tests

#12870 [Backport 10_0_X] fix(android): improve pre-loading optimization of ListView and TableView
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/listview/ListItemProxy.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/listview/ListViewHolder.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/listview/TiListView.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/tableview/TiTableView.java
  android/runtime/v8/src/java/org/appcelerator/kroll/runtime/v8/ReferenceTable.java
  android/titanium/src/java/org/appcelerator/titanium/util/TiDownloadManager.java
Labels: android, bug 🐜, in-qe-testing 🕵, needs jira 🚨, no tests

#12883 ci: update backport action to fix missing commits issue
  .github/workflows/backport.yml
Labels: needs jira 🚨

#12832 fix(ios): animating view width/height from zero
  iphone/TitaniumKit/TitaniumKit/Sources/API/TiViewProxy.m
  tests/Resources/ti.ui.view.test.js
Labels: backport 10_0_X, bug 🐜, in-qe-testing 🕵, ios

#12708 refactor(android): remove "WebViewClient.jar" from SDK
  android/modules/ui/lib/WebViewClient.jar
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/webview/TiWebViewClient.java
  android/titanium/build.gradle
Labels: android, backport 10_0_X, improvement, in-qe-testing 🕵, no tests

#12878 fix(android): ProgressBar tintColor/trackTintColor ignored as of 10.0.0
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/TiUIProgressBar.java
Labels: android, backport 10_0_X, bug 🐜, in-qe-testing 🕵, no tests

#12893 [Backport 10_0_X] refactor(android): remove "WebViewClient.jar" from SDK
  android/modules/ui/lib/WebViewClient.jar
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/webview/TiWebViewClient.java
  android/titanium/build.gradle
Labels: android, improvement, in-qe-testing 🕵, needs jira 🚨, no tests

#12892 [Backport 10_0_X] fix(ios): animating view width/height from zero
  iphone/TitaniumKit/TitaniumKit/Sources/API/TiViewProxy.m
  tests/Resources/ti.ui.view.test.js
Labels: bug 🐜, in-qe-testing 🕵, ios, needs jira 🚨

#12894 [Backport 10_0_X] fix(android): ProgressBar tintColor/trackTintColor ignored as of 10.0.0
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/TiUIProgressBar.java
Labels: android, bug 🐜, in-qe-testing 🕵, needs jira 🚨, no tests

#12865 fix(adb): check err.code instead of err.errno on socket error
  package-lock.json
  package.json
Labels: backport 10_0_X, in-qe-testing 🕵

#12896 [Backport 10_0_X] fix(adb): check err.code instead of err.errno on socket error
  package-lock.json
  package.json
Labels: in-qe-testing 🕵

#12879 fix(ios): top section can disappear in grouped ListView
  iphone/Classes/TiUIListView.m
Labels: backport 10_0_X, bug 🐜, in-qe-testing 🕵, ios, no tests

#12721 fix(ios): unhandled native exceptions should show an error dialog
  iphone/TitaniumKit/TitaniumKit/Sources/API/TiExceptionHandler.m
Labels: backport 10_0_X, bug 🐜, in-qe-testing 🕵, ios, no tests, parity 👯‍♀️

#12898 [Backport 10_0_X] fix(ios): top section can disappear in grouped ListView
  iphone/Classes/TiUIListView.m
Labels: bug 🐜, in-qe-testing 🕵, ios, needs jira 🚨, no tests

#12899 [Backport 10_0_X] fix(ios): unhandled native exceptions should show an error dialog
  iphone/TitaniumKit/TitaniumKit/Sources/API/TiExceptionHandler.m
Labels: bug 🐜, in-qe-testing 🕵, ios, needs jira 🚨, no tests, parity 👯‍♀️

#12684 refactor(ios): optimize promise creation on iOS 12
  iphone/TitaniumKit/TitaniumKit/Sources/Kroll/KrollPromise.m
Labels: backport 10_0_X, improvement, in-qe-testing 🕵, ios, no tests

#12901 [Backport 10_0_X] refactor(ios): optimize promise creation on iOS 12
  iphone/TitaniumKit/TitaniumKit/Sources/Kroll/KrollPromise.m
Labels: improvement, in-qe-testing 🕵, ios, needs jira 🚨, no tests

#12903 test(macos): disable animate width/height unit test
  tests/Resources/ti.ui.view.test.js
Labels: backport 10_0_X, ios, needs jira 🚨

#12617 fix: convertPointToView() to apply ScrollView contentOffset
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/TiUIScrollView.java
  android/titanium/src/java/org/appcelerator/titanium/proxy/TiViewProxy.java
  android/titanium/src/java/org/appcelerator/titanium/view/TiUIView.java
  iphone/TitaniumKit/TitaniumKit/Sources/API/TiPoint.h
  iphone/TitaniumKit/TitaniumKit/Sources/API/TiPoint.m
  iphone/TitaniumKit/TitaniumKit/Sources/API/TiViewProxy.h
  iphone/TitaniumKit/TitaniumKit/Sources/API/TiViewProxy.m
Labels: android, backport 10_0_X, bug 🐜, in-qe-testing 🕵, ios, no tests

#12907 [Backport 10_0_X] fix: convertPointToView() to apply ScrollView contentOffset
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/TiUIScrollView.java
  android/titanium/src/java/org/appcelerator/titanium/proxy/TiViewProxy.java
  android/titanium/src/java/org/appcelerator/titanium/view/TiUIView.java
  iphone/TitaniumKit/TitaniumKit/Sources/API/TiPoint.h
  iphone/TitaniumKit/TitaniumKit/Sources/API/TiPoint.m
  iphone/TitaniumKit/TitaniumKit/Sources/API/TiViewProxy.h
  iphone/TitaniumKit/TitaniumKit/Sources/API/TiViewProxy.m
Labels: android, bug 🐜, in-qe-testing 🕵, ios, needs jira 🚨, no tests

#12900 fix(ios): export original native module object
  common/Resources/ti.internal/kernel/module.js
Labels: backport 10_0_X, bug 🐜, in-qe-testing 🕵, ios, needs tests 🚨

#12904 [Backport 10_0_X] test(macos): disable animate width/height unit test
  tests/Resources/ti.ui.view.test.js
Labels: ios, needs jira 🚨

#12916 [Backport 10_0_X] fix(ios): export original native module object
  common/Resources/ti.internal/kernel/module.js
Labels: bug 🐜, in-qe-testing 🕵, ios, needs jira 🚨, needs tests 🚨

#12906 fix(ios): properly dismiss search controller after editing
  iphone/Classes/TiUIListView.m
  iphone/Classes/TiUITableView.m
Labels: backport 10_0_X, bug 🐜, in-qe-testing 🕵, ios, no tests

#12918 [Backport 10_0_X] fix(ios): properly dismiss search controller after editing
  iphone/Classes/TiUIListView.m
  iphone/Classes/TiUITableView.m
Labels: bug 🐜, in-qe-testing 🕵, ios, no tests

#12919 fix(android): logged theme error in "ti.map" module
  support/module/packaged/modules.json
Labels: android, backport 10_0_X, bug 🐜, in-qe-testing 🕵, no tests

#12839 fix(android): minor Ti.UI.ScrollableView refactor
  android/modules/ui/src/java/ti/modules/titanium/ui/ScrollableViewProxy.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/TiUIScrollableView.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/listview/ListSectionProxy.java
Labels: android, backport 10_0_X, bug 🐜, in-qe-testing 🕵, no tests

#12928 [Backport 10_0_X] fix(android): logged theme error in "ti.map" module
  support/module/packaged/modules.json
Labels: android, bug 🐜, in-qe-testing 🕵, needs jira 🚨, no tests

#12909 fix(android): improve ListView scroll performance
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/listview/ListItemProxy.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/listview/ListViewAdapter.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/listview/TiListView.java
  android/titanium/src/java/org/appcelerator/titanium/proxy/TiViewProxy.java
Labels: android, backport 10_0_X, bug 🐜, in-qe-testing 🕵, no tests
