Repository tidev/titanium-sdk, pull requests merged in 2021-03, with the labels that each got.

#12515 fix(android): expose builder property for hyperloop to mark js files not to process
  android/cli/commands/_build.js
  cli/lib/gather.js
Labels: android, backport 10_0_X, bug 🐜, cli 📟, needs jira 🚨

#12518 chore(android): build snapshots in CI
  .github/workflows/build.yml
  android/titanium/libv8-services.js
  android/titanium/prebuild.js
  build/lib/builder.js
  package.json
Labels: in-qe-testing 🕵, needs jira 🚨

#12534 chore(deps-dev): update titanium-docgen to 4.10.3
  .husky/.gitignore
  package-lock.json
  package.json
Labels: docs 📔, needs jira 🚨

#12510 feat: add Ti.UI.OptionBar
  android/modules/ui/src/java/ti/modules/titanium/ui/OptionBarProxy.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/TiUIOptionBar.java
  apidoc/Titanium/UI/OptionBar.yml
  iphone/Classes/TiUIButtonBar.m
  iphone/Classes/TiUIOptionBarProxy.h
  iphone/Classes/TiUIOptionBarProxy.m
  iphone/Classes/UIModule.m
  iphone/cli/commands/_build.js
  iphone/iphone/Titanium.xcodeproj/project.pbxproj
  iphone/iphone/project.xcconfig
  tests/Resources/app.js
  tests/Resources/ti.ui.optionbar.test.js
Labels: android, backport 10_0_X, docs 📔, feature 🚀, in-qe-testing 🕵, ios, parity 👯‍♀️, test

#12513 fix: deprecate selectedBackgroundColor and selectedBackgroundImage
  apidoc/Titanium/UI/ListItem.yml
  apidoc/Titanium/UI/TableViewRow.yml
  iphone/Classes/TiUIListItem.m
  iphone/Classes/TiUITableView.h
  iphone/Classes/TiUITableView.m
  iphone/Classes/TiUITableViewRowProxy.m
Labels: backport 10_0_X, docs 📔, improvement, in-qe-testing 🕵, ios, no tests, parity 👯‍♀️

#12446 fix(android): support transparent backgrounds with touchFeedback
  android/titanium/src/java/org/appcelerator/titanium/view/TiUIView.java
Labels: android, bug 🐜, in-qe-testing 🕵, no tests

#12539 [Backport 10_0_X] fix(android): support transparent backgrounds with touchFeedback
  android/titanium/src/java/org/appcelerator/titanium/view/TiUIView.java
Labels: android, needs jira 🚨, needs tests 🚨

#12540 chore(deps): update hyperloop to 7.0.1
  support/module/packaged/modules.json
Labels: android, backport 10_0_X, bug 🐜, in-qe-testing 🕵

#12553 [Backport 10_0_X] chore(deps): update hyperloop to 7.0.1
  support/module/packaged/modules.json
Labels: android, bug 🐜, in-qe-testing 🕵

#12524 fix(android): fragments in children of header/footerview
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/listview/ListItemProxy.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/listview/ListSectionProxy.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/listview/ListViewHolder.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/tableview/TableViewHolder.java
Labels: android, backport 10_0_X, community 🔥, in-qe-testing 🕵, needs tests 🚨

#12554 chore(deps): run npm dedupe
  package-lock.json
Labels: needs jira 🚨

#12555 chore(deps): run npm dedupe
  package-lock.json
Labels: in-qe-testing 🕵, needs jira 🚨

#12547 chore: update the create-a-bug template to point to GitHub Discussions
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/report-a-bug.md
Labels: in-qe-testing 🕵, needs jira 🚨

#12541 fix(android): Check proxy on TiDrawableReference fromUrl
  android/titanium/src/java/org/appcelerator/titanium/view/TiDrawableReference.java
Labels: android, backport 10_0_X, backport master, bug 🐜, community 🔥, in-qe-testing 🕵, no tests

#12440 fix(android): touchFeedback support for ListView and TableView
  android/modules/ui/res/layout/titanium_ui_listview_holder.xml
  android/modules/ui/res/layout/titanium_ui_tableview_holder.xml
  android/modules/ui/src/java/ti/modules/titanium/ui/TableViewProxy.java
  android/modules/ui/src/java/ti/modules/titanium/ui/TableViewRowProxy.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/TiUIListView.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/TiUITableView.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/listview/ItemTouchHandler.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/listview/ListItemProxy.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/listview/ListViewHolder.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/listview/ListViewProxy.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/listview/TiRecyclerViewHolder.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/tableview/TableViewHolder.java
  android/titanium/src/java/org/appcelerator/titanium/view/TiUIView.java
  apidoc/Titanium/UI/ListView.yml
  apidoc/Titanium/UI/TableView.yml
Labels: android, bug 🐜, docs 📔, in-qe-testing 🕵, no tests

#12561 chore(deps): update node-ios-device to 1.9.1
  package-lock.json
  package.json
Labels: cli 📟, ios, needs jira 🚨

#12563 chore(deps): update node-ios-device to 1.9.1
  package-lock.json
  package.json
Labels: cli 📟, ios, needs jira 🚨

#12578 revert: chore(deps): update node-ios-device to 1.9.1
  package-lock.json
  package.json
Labels: needs jira 🚨

#12558 fix(android): TableView regressions
  android/modules/ui/src/java/ti/modules/titanium/ui/TableViewRowProxy.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/listview/TiListView.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/listview/TiRecyclerViewHolder.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/tableview/TableViewHolder.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/tableview/TiTableView.java
  android/titanium/src/java/org/appcelerator/titanium/TiC.java
  android/titanium/src/java/org/appcelerator/titanium/proxy/TiViewProxy.java
Labels: android, backport 10_0_X, backport 9_3_X, bug 🐜, in-qe-testing 🕵, no tests

#12522 fix(ios): fix list-view crash
  iphone/Classes/TiUIListItem.m
Labels: backport 10_0_X, bug 🐜, community 🔥, in-qe-testing 🕵, ios, needs jira 🚨, needs tests 🚨

#12583 fix(android): TableView regressions (#12558)
  android/modules/ui/src/java/ti/modules/titanium/ui/TableViewRowProxy.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/listview/TiListView.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/listview/TiRecyclerViewHolder.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/tableview/TableViewHolder.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/tableview/TiTableView.java
  android/titanium/src/java/org/appcelerator/titanium/TiC.java
  android/titanium/src/java/org/appcelerator/titanium/proxy/TiViewProxy.java
Labels: android, needs jira 🚨, needs tests 🚨

#12584 fix(android): TableView regressions (#12558)
  android/modules/ui/src/java/ti/modules/titanium/ui/TableViewRowProxy.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/listview/TiListView.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/listview/TiRecyclerViewHolder.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/tableview/TableViewHolder.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/tableview/TiTableView.java
  android/titanium/src/java/org/appcelerator/titanium/TiC.java
  android/titanium/src/java/org/appcelerator/titanium/proxy/TiViewProxy.java
Labels: android, needs jira 🚨, needs tests 🚨

#12562 chore(deps): update liveview to 1.5.5
  package-lock.json
  package.json
Labels: bug 🐜, cli 📟, in-qe-testing 🕵

#12590 [Backport 10_0_X] fix(ios): fix list-view crash
  iphone/Classes/TiUIListItem.m
Labels: bug 🐜, community 🔥, in-qe-testing 🕵, ios, needs jira 🚨, needs tests 🚨

#12591 [Backport 10_0_X] chore(deps): update liveview to 1.5.5
  package-lock.json
  package.json
Labels: needs jira 🚨

#12596 chore(deps): update node-ios-device dependencies
  package-lock.json
  package.json
Labels: needs jira 🚨

#12496 fix(ios): documentViewer setAnnotation method causing a crash
  apidoc/Titanium/UI/iOS/DocumentViewer.yml
  iphone/Classes/TiUIiOSDocumentViewerProxy.m
  tests/Resources/app.js
  tests/Resources/ti.ui.ios.documentviewer.test.js
Labels: backport 10_0_X, bug 🐜, docs 📔, in-qe-testing 🕵, ios

#12609 [Backport 10_0_X] fix(ios): documentViewer setAnnotation method causing a crash
  apidoc/Titanium/UI/iOS/DocumentViewer.yml
  iphone/Classes/TiUIiOSDocumentViewerProxy.m
  tests/Resources/app.js
  tests/Resources/ti.ui.ios.documentviewer.test.js
Labels: bug 🐜, docs 📔, in-qe-testing 🕵, ios, needs jira 🚨

#12610 [Backport 9_3_X] fix(ios): documentViewer setAnnotation method causing a crash
  apidoc/Titanium/UI/iOS/DocumentViewer.yml
  iphone/Classes/TiUIiOSDocumentViewerProxy.m
  tests/Resources/app.js
  tests/Resources/ti.ui.ios.documentviewer.test.js
Labels: docs 📔, ios, needs jira 🚨

#12580 refactor(android): use Geocoder for forward and reverse lookup
  android/modules/geolocation/src/java/ti/modules/titanium/geolocation/GeolocationModule.java
  android/modules/geolocation/src/java/ti/modules/titanium/geolocation/TiLocation.java
Labels: android, backport 10_0_X, backport 9_3_X, improvement, in-qe-testing 🕵, no tests

#12612 [Backport 10_0_X] refactor(android): use Geocoder for forward and reverse lookup
  android/modules/geolocation/src/java/ti/modules/titanium/geolocation/GeolocationModule.java
  android/modules/geolocation/src/java/ti/modules/titanium/geolocation/TiLocation.java
Labels: android, improvement, in-qe-testing 🕵, needs jira 🚨, no tests

#12611 [Backport 10_0_X] style: fix eslint warnings
  .eslintrc
  android/cli/lib/gradle-wrapper.js
  build/lib/test/generator.js
  build/lib/test/index.js
  build/lib/test/test.js
  changelog/config.js
  cli/hooks/webpack.js
  common/Resources/ti.internal/aca.js
  common/Resources/ti.internal/extensions/node/string_decoder.js
  iphone/cli/commands/_build.js
  iphone/cli/commands/_buildModule.js
  iphone/cli/hooks/frameworks.js
  iphone/cli/hooks/storyboard.js
  tests/Resources/ti.contacts.group.test.js
  tests/Resources/ti.database.test.js
  tests/Resources/ti.geolocation.test.js
  tests/Resources/ti.ui.attributedstring.test.js
  tests/Resources/ti.ui.clipboard.test.js
  tests/Resources/ti.ui.navigationwindow.test.js
  tests/Resources/ti.ui.tabgroup.test.js
  tests/Resources/ti.ui.view.test.js
  tests/Resources/ti.ui.webview.test.js
  tests/Resources/ti.ui.window.test.js
Labels: improvement, needs jira 🚨

#12581 chore(ios): use CLGeocoder APIs to reverse geocode and forward geocode
  apidoc/Titanium/Geolocation/Geolocation.yml
  iphone/Classes/GeolocationModule.m
  tests/Resources/ti.geolocation.test.js
Labels: backport 10_0_X, backport 9_3_X, docs 📔, in-qe-testing 🕵, ios

#12619 [Backport 10_0_X] chore(ios): use CLGeocoder APIs to reverse geocode and forward geocode
  apidoc/Titanium/Geolocation/Geolocation.yml
  iphone/Classes/GeolocationModule.m
  tests/Resources/ti.geolocation.test.js
Labels: docs 📔, in-qe-testing 🕵, ios, needs jira 🚨

#12565 feat(android): update Ti.UI.SearchBar to use native SearchView
  android/modules/ui/src/java/ti/modules/titanium/ui/SearchBarProxy.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/searchbar/TiUISearchBar.java
  android/titanium/src/java/org/appcelerator/titanium/TiC.java
  apidoc/Titanium/UI/SearchBar.yml
  apidoc/Titanium/UI/searchbar_android.png
Labels: BREAKING CHANGES ⚠️, android, backport 10_0_X, docs 📔, improvement, in-qe-testing 🕵, no tests

#12620 fix(android): amend TableViewRow reuse
  android/modules/ui/src/java/ti/modules/titanium/ui/TableViewProxy.java
  android/modules/ui/src/java/ti/modules/titanium/ui/TableViewRowProxy.java
  android/modules/ui/src/java/ti/modules/titanium/ui/TableViewSectionProxy.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/listview/TiRecyclerViewHolder.java
  android/titanium/src/java/org/appcelerator/titanium/proxy/TiViewProxy.java
Labels: android, backport 10_0_X, backport 9_3_X, bug 🐜, in-qe-testing 🕵, no tests

#12642 [Backport 10_0_X] fix(android): amend TableViewRow reuse
  android/modules/ui/src/java/ti/modules/titanium/ui/TableViewProxy.java
  android/modules/ui/src/java/ti/modules/titanium/ui/TableViewRowProxy.java
  android/modules/ui/src/java/ti/modules/titanium/ui/TableViewSectionProxy.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/listview/TiRecyclerViewHolder.java
  android/titanium/src/java/org/appcelerator/titanium/proxy/TiViewProxy.java
Labels: android, bug 🐜, in-qe-testing 🕵, needs jira 🚨, no tests

#12624 [Backport 10_0_X] feat(android): update Ti.UI.SearchBar to use native SearchView
  android/modules/ui/src/java/ti/modules/titanium/ui/SearchBarProxy.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/searchbar/TiUISearchBar.java
  android/titanium/src/java/org/appcelerator/titanium/TiC.java
  apidoc/Titanium/UI/SearchBar.yml
  apidoc/Titanium/UI/searchbar_android.png
Labels: BREAKING CHANGES ⚠️, android, docs 📔, improvement, in-qe-testing 🕵, needs jira 🚨, no tests

#12526 fix(ios): update layout after assigning label property
  iphone/Classes/TiUIButtonBar.m
Labels: backport 10_0_X, backport 9_3_X, in-qe-testing 🕵, ios, needs tests 🚨

#12542 fix(ios): removing eventListener in location event will freeze app
  iphone/TitaniumKit/TitaniumKit/Sources/API/ObjcProxy.m
Labels: backport 10_0_X, backport 9_3_X, in-qe-testing 🕵, ios, no tests

#12616 fix(ios): set executionContext of TiStreamProxy
  iphone/Classes/FilesystemModule.m
  tests/Resources/ti.stream.test.js
Labels: backport 10_0_X, backport 9_3_X, in-qe-testing 🕵, ios

#12643 [Backport 10_0_X] fix(ios): update layout after assigning label property
  iphone/Classes/TiUIButtonBar.m
Labels: in-qe-testing 🕵, ios, needs jira 🚨, needs tests 🚨

#12644 [Backport 9_3_X] fix(ios): update layout after assigning label property
  iphone/Classes/TiUIButtonBar.m
Labels: in-qe-testing 🕵, ios, needs jira 🚨, needs tests 🚨

#12647 [Backport 10_0_X] fix(ios): set executionContext of TiStreamProxy
  iphone/Classes/FilesystemModule.m
  tests/Resources/ti.stream.test.js
Labels: in-qe-testing 🕵, ios, needs jira 🚨

#12648 [Backport 9_3_X] fix(ios): set executionContext of TiStreamProxy
  iphone/Classes/FilesystemModule.m
  tests/Resources/ti.stream.test.js
Labels: in-qe-testing 🕵, ios, needs jira 🚨

#12645 [Backport 10_0_X] fix(ios): removing eventListener in location event will freeze app
  iphone/TitaniumKit/TitaniumKit/Sources/API/ObjcProxy.m
Labels: in-qe-testing 🕵, ios, needs jira 🚨, no tests

#12646 [Backport 9_3_X] fix(ios): removing eventListener in location event will freeze app
  iphone/TitaniumKit/TitaniumKit/Sources/API/ObjcProxy.m
Labels: in-qe-testing 🕵, ios, needs jira 🚨, no tests

#12649 [Backport 10_0_X] feat(android): implement delete event for ListView and TableView
  android/modules/ui/src/java/ti/modules/titanium/ui/TableViewProxy.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/listview/ListViewProxy.java
  android/titanium/src/java/org/appcelerator/titanium/TiC.java
  apidoc/Titanium/UI/ListView.yml
  apidoc/Titanium/UI/TableView.yml
Labels: android, docs 📔, improvement, in-qe-testing 🕵, needs jira 🚨, no tests, parity 👯‍♀️

#12622 chore(android): TableViewRow/ListItem added after theme switch should use current theme
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/listview/ListViewHolder.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/tableview/TableViewHolder.java
Labels: android, backport 10_0_X, improvement, in-qe-testing 🕵, no tests

#12653 [Backport 10_0_X] chore(android): TableViewRow/ListItem added after theme switch should use current theme
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/listview/ListViewHolder.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/tableview/TableViewHolder.java
Labels: android, improvement, in-qe-testing 🕵, needs jira 🚨, no tests

#12654 fix(ios): fixed setSelection issue of textfield
  apidoc/Titanium/UI/TabGroup.yml
  iphone/Classes/TiUITextWidget.h
  iphone/Classes/TiUITextWidget.m
  iphone/Classes/TiUITextWidgetProxy.m
  tests/Resources/ti.ui.textfield.test.js
Labels: backport 10_0_X, bug 🐜, docs 📔, ios

#12666 [Backport 10_0_X] fix(ios): fixed setSelection issue of textfield
  apidoc/Titanium/UI/TabGroup.yml
  iphone/Classes/TiUITextWidget.h
  iphone/Classes/TiUITextWidget.m
  iphone/Classes/TiUITextWidgetProxy.m
  tests/Resources/ti.ui.textfield.test.js
Labels: bug 🐜, docs 📔, ios, needs jira 🚨

#12652 chore: update APSAnalytics
  android/titanium/lib/aps-analytics.jar
  iphone/TitaniumKit/TitaniumKit/Libraries/APSAnalytics/APSAnalytics.xcframework/Info.plist
  iphone/TitaniumKit/TitaniumKit/Libraries/APSAnalytics/APSAnalytics.xcframework/ios-arm64/libAPSAnalytics.a
  iphone/TitaniumKit/TitaniumKit/Libraries/APSAnalytics/APSAnalytics.xcframework/ios-arm64_x86_64-maccatalyst/libAPSAnalytics.a
  iphone/TitaniumKit/TitaniumKit/Libraries/APSAnalytics/APSAnalytics.xcframework/ios-arm64_x86_64-simulator/libAPSAnalytics.a
Labels: android, backport 10_0_X, improvement, in-qe-testing 🕵, ios, no tests

#12674 [Backport 10_0_X] chore: update APSAnalytics
  android/titanium/lib/aps-analytics.jar
  iphone/TitaniumKit/TitaniumKit/Libraries/APSAnalytics/APSAnalytics.xcframework/Info.plist
  iphone/TitaniumKit/TitaniumKit/Libraries/APSAnalytics/APSAnalytics.xcframework/ios-arm64/libAPSAnalytics.a
  iphone/TitaniumKit/TitaniumKit/Libraries/APSAnalytics/APSAnalytics.xcframework/ios-arm64_x86_64-maccatalyst/libAPSAnalytics.a
  iphone/TitaniumKit/TitaniumKit/Libraries/APSAnalytics/APSAnalytics.xcframework/ios-arm64_x86_64-simulator/libAPSAnalytics.a
Labels: android, improvement, in-qe-testing 🕵, ios, no tests
