Repository tidev/titanium-sdk, pull requests merged in 2021-01, with the labels that each got.

#12354 fix(ios): add workspace workaround
  iphone/iphone/Titanium.xcodeproj/project.pbxproj
Labels: backport 9_2_X, backport 9_3_X, bug 🐜, community 🔥, in-qe-testing 🕵, ios

#12366 [Backport 9_3_X] fix(ios): add workspace workaround
  iphone/iphone/Titanium.xcodeproj/project.pbxproj
Labels: bug 🐜, community 🔥, in-qe-testing 🕵, ios

#12350 fix(android): amend ListView marker behaviour
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/listview/ListSectionProxy.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/listview/ListViewProxy.java
Labels: android, backport 9_3_X, bug 🐜, in-qe-testing 🕵, no tests

#12282 feat(android): add missing options to Intl.DateTimeFormat.resolvedOptions()
  android/modules/locale/src/java/ti/modules/titanium/locale/DateTimeFormatProxy.java
  tests/Resources/intl.datetimeformat.test.js
Labels: android, backport 9_3_X, improvement, in-qe-testing 🕵

#12376 [Backport 9_3_X] fix(android): amend ListView marker behaviour
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/listview/ListSectionProxy.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/listview/ListViewProxy.java
Labels: android, bug 🐜, in-qe-testing 🕵, needs jira 🚨, no tests

#12377 [Backport 9_3_X] feat(android): add missing options to Intl.DateTimeFormat.resolvedOptions()
  android/modules/locale/src/java/ti/modules/titanium/locale/DateTimeFormatProxy.java
  tests/Resources/intl.datetimeformat.test.js
Labels: android, improvement, in-qe-testing 🕵, needs jira 🚨

#12367 docs(api): add missing parameter in NotificationChannel
  apidoc/Titanium/Android/NotificationChannel.yml
Labels: community 🔥, docs 📔, in-qe-testing 🕵, needs jira 🚨

#12268 fix(angular): production builds using aot compiler
  templates/app/angular-default/template/package.json
  templates/app/angular-default/template/src/app/app.module.ts
  templates/app/angular-default/template/src/assets/semantic.colors.json
  templates/app/angular-default/template/src/environments/environment.prod.ts
  templates/app/angular-default/template/src/environments/environment.ts
  templates/app/angular-default/template/src/main.aot.ts
  templates/app/angular-default/template/src/main.ts
Labels: backport 9_3_X, bug 🐜, in-qe-testing 🕵

#12381 [Backport 9_3_X] fix(angular): production builds using aot compiler
  templates/app/angular-default/template/package.json
  templates/app/angular-default/template/src/app/app.module.ts
  templates/app/angular-default/template/src/assets/semantic.colors.json
  templates/app/angular-default/template/src/environments/environment.prod.ts
  templates/app/angular-default/template/src/environments/environment.ts
  templates/app/angular-default/template/src/main.aot.ts
  templates/app/angular-default/template/src/main.ts
Labels: bug 🐜, in-qe-testing 🕵, needs jira 🚨

#12384 chore(android): update V8 to 8.7.220.31
  android/package.json
  android/runtime/v8/src/native/CMakeLists.txt
Labels: android, improvement, no tests

#12233 fix(iOS): set parent view controller for detached view controllers
  iphone/Classes/TiMediaVideoPlayer.h
  iphone/Classes/TiMediaVideoPlayer.m
  iphone/Classes/TiMediaVideoPlayerProxy.m
  iphone/Classes/TiUIListView.m
  iphone/Classes/TiUINavigationWindowProxy.m
  iphone/Classes/TiUITabGroupProxy.m
  iphone/Classes/TiUITableView.m
  iphone/TitaniumKit/TitaniumKit/Sources/API/TiWindowProxy.m
Labels: bug 🐜, in-qe-testing 🕵, ios, needs tests 🚨

#12386 fix(android): amend method to obtain view in TableViewRowProxy.releaseViews()
  android/modules/ui/src/java/ti/modules/titanium/ui/TableViewRowProxy.java
Labels: android, backport 9_3_X, bug 🐜, in-qe-testing 🕵, no tests

#12387 [Backport 9_3_X] fix(android): amend method to obtain view in TableViewRowProxy.releaseViews()
  android/modules/ui/src/java/ti/modules/titanium/ui/TableViewRowProxy.java
Labels: android, bug 🐜, in-qe-testing 🕵, needs jira 🚨, no tests

#12382 fix(android): decimal comma TextField handling on some devices
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/TiUIText.java
Labels: android, backport 9_3_X, bug 🐜, in-qe-testing 🕵, no tests

#12401 [Backport 9_3_X] fix(android): decimal comma TextField handling on some devices
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/TiUIText.java
Labels: android, bug 🐜, in-qe-testing 🕵, needs jira 🚨, no tests

#12363 fix(android): optimize list view updates
  android/modules/ui/src/java/ti/modules/titanium/ui/TableViewRowProxy.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/listview/ListItemProxy.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/listview/ListSectionProxy.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/listview/ListViewProxy.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/listview/TiListView.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/tableview/TiTableView.java
Labels: android, backport 9_3_X, bug 🐜, in-qe-testing 🕵, no tests

#12405 [Backport 9_3_X] fix(android): optimize list view updates
  android/modules/ui/src/java/ti/modules/titanium/ui/TableViewRowProxy.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/listview/ListItemProxy.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/listview/ListSectionProxy.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/listview/ListViewProxy.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/listview/TiListView.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/tableview/TiTableView.java
Labels: android, bug 🐜, in-qe-testing 🕵, needs jira 🚨, no tests

#12402 fix(iOS): set statusbar height to top of safearea view
  iphone/TitaniumKit/TitaniumKit/Sources/Modules/TiUIWindowProxy.m
Labels: backport 9_3_X, in-qe-testing 🕵, ios, no tests

#12408 [Backport 9_3_X] fix(iOS): set statusbar height to top of safearea view
  iphone/TitaniumKit/TitaniumKit/Sources/Modules/TiUIWindowProxy.m
Labels: in-qe-testing 🕵, ios, needs jira 🚨, no tests

#12412 chore(ios): update facebook to 10.0.0
  support/module/packaged/modules.json
Labels: backport 9_3_X, ios, no tests

#12414 [Backport 9_3_X] chore(ios): update facebook to 10.0.0
  support/module/packaged/modules.json
Labels: ios, needs jira 🚨, no tests

#12410 chore(android): update ti.facebook to 11.0.2
  support/module/packaged/modules.json
Labels: android, backport 9_3_X, needs jira 🚨, no tests

#12415 [Backport 9_3_X] chore(android): update ti.facebook to 11.0.2
  support/module/packaged/modules.json
Labels: android, needs jira 🚨, no tests

#12418 Modernize some ListView examples
  apidoc/Titanium/UI/ListView.yml
Labels: docs 📔, needs jira 🚨
