Repository tidev/titanium-sdk, pull requests merged in 2021-11, with the labels that each got.

#13146 feat(android): add pinch zoom and double-tap zoom support to ImageView
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/TiImageView.java
Labels: android, bug 🐜, improvement, in-qe-testing 🕵, no tests

#13163 fix(android): ListView/TableView scroll performance for complex items added after window open
  android/titanium/src/java/org/appcelerator/kroll/KrollProxy.java
Labels: android, bug 🐜, no tests

#12891 impr(android): optimize RecyclerView adapter
  android/modules/ui/src/java/ti/modules/titanium/ui/TableViewProxy.java
  android/modules/ui/src/java/ti/modules/titanium/ui/TableViewSectionProxy.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/TiUIListView.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/TiUITableView.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/listview/ListSectionProxy.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/listview/ListViewAdapter.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/listview/ListViewHolder.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/listview/ListViewProxy.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/listview/TiListView.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/listview/TiRecyclerViewAdapter.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/listview/TiRecyclerViewHolder.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/tableview/TableViewAdapter.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/tableview/TableViewHolder.java
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/tableview/TiTableView.java
Labels: android, improvement, in-qe-testing 🕵, no tests

#13165 fix(ios): window.setToolbar() background color alway transparent on iOS 15
  iphone/TitaniumKit/TitaniumKit/Sources/Modules/TiUIWindowProxy.m
Labels: ios, bug 🐜, in-qe-testing 🕵, no tests

#13166 feat(android): ActionBar menu text should not be all-caps by default
  android/titanium/res/values/values.xml
Labels: android, improvement, no tests

#13167 fix(android): Ti.UI.Android.ProgressIndicator dialog not using theme's "colorPrimary"
  android/modules/ui/src/java/ti/modules/titanium/ui/widget/TiUIProgressIndicator.java
  android/titanium/res/values/values.xml
Labels: android, bug 🐜, no tests

#13172 fix(ios): use correct iOS destination platform during build
  iphone/cli/commands/_build.js
Labels: needs jira 🚨

#13176 fix(ios): tab background color on iOS 15 when setting title color
  iphone/Classes/TiUITabGroup.m
  iphone/Classes/TiUITabProxy.h
  iphone/Classes/TiUITabProxy.m
Labels: ios, bug 🐜, no tests

#13171 chore: convert issue templates to issue forms
  .github/ISSUE_TEMPLATE/1.bug_report.yml
  .github/ISSUE_TEMPLATE/2.docs_issue.yml
  .github/ISSUE_TEMPLATE/3.feature_proposal.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/propose-a-feature.md
  .github/issue_template.md
Labels: needs jira 🚨

#13190 docs: add 10.1.1. changelog
  CHANGELOG.md
Labels: needs jira 🚨, backport 10_1_X

#13191 [Backport 10_1_X] docs: add 10.1.1. changelog
  CHANGELOG.md
Labels: needs jira 🚨
