Repository tidev/titanium-sdk, pull requests merged in 2022-01, with the labels that each got.

#13224 docs: Titanium.UI.iOS.Toolbar was removed in 10.0.0
  apidoc/Titanium/UI/TextArea.yml
  apidoc/Titanium/UI/TextField.yml
Labels: community 🔥, needs jira 🚨, docs 📔

#13209 fix(android): drop-down picker to never accept keyboard input
  android/modules/ui/src/java/ti/modules/titanium/ui/PickerProxy.java
Labels: android, bug, no tests

#13253 docs: update documentation links in readme
  README.md
Labels: community 🔥, needs jira 🚨
